// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// SystemFilesystemInodesUsageMetricAttributeKey specifies the key of an attribute for the system.filesystem.inodes.usage metric.
type SystemFilesystemInodesUsageMetricAttributeKey string

const (
	SystemFilesystemInodesUsageMetricAttributeKeyDevice     SystemFilesystemInodesUsageMetricAttributeKey = "device"
	SystemFilesystemInodesUsageMetricAttributeKeyMode       SystemFilesystemInodesUsageMetricAttributeKey = "mode"
	SystemFilesystemInodesUsageMetricAttributeKeyMountpoint SystemFilesystemInodesUsageMetricAttributeKey = "mountpoint"
	SystemFilesystemInodesUsageMetricAttributeKeyType       SystemFilesystemInodesUsageMetricAttributeKey = "type"
	SystemFilesystemInodesUsageMetricAttributeKeyState      SystemFilesystemInodesUsageMetricAttributeKey = "state"
)

// SystemFilesystemInodesUsageMetricConfig provides config for the system.filesystem.inodes.usage metric.
type SystemFilesystemInodesUsageMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemFilesystemInodesUsageMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemFilesystemInodesUsageMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemFilesystemInodesUsageMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// SystemFilesystemUsageMetricAttributeKey specifies the key of an attribute for the system.filesystem.usage metric.
type SystemFilesystemUsageMetricAttributeKey string

const (
	SystemFilesystemUsageMetricAttributeKeyDevice     SystemFilesystemUsageMetricAttributeKey = "device"
	SystemFilesystemUsageMetricAttributeKeyMode       SystemFilesystemUsageMetricAttributeKey = "mode"
	SystemFilesystemUsageMetricAttributeKeyMountpoint SystemFilesystemUsageMetricAttributeKey = "mountpoint"
	SystemFilesystemUsageMetricAttributeKeyType       SystemFilesystemUsageMetricAttributeKey = "type"
	SystemFilesystemUsageMetricAttributeKeyState      SystemFilesystemUsageMetricAttributeKey = "state"
)

// SystemFilesystemUsageMetricConfig provides config for the system.filesystem.usage metric.
type SystemFilesystemUsageMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemFilesystemUsageMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemFilesystemUsageMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemFilesystemUsageMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// SystemFilesystemUtilizationMetricAttributeKey specifies the key of an attribute for the system.filesystem.utilization metric.
type SystemFilesystemUtilizationMetricAttributeKey string

const (
	SystemFilesystemUtilizationMetricAttributeKeyDevice     SystemFilesystemUtilizationMetricAttributeKey = "device"
	SystemFilesystemUtilizationMetricAttributeKeyMode       SystemFilesystemUtilizationMetricAttributeKey = "mode"
	SystemFilesystemUtilizationMetricAttributeKeyMountpoint SystemFilesystemUtilizationMetricAttributeKey = "mountpoint"
	SystemFilesystemUtilizationMetricAttributeKeyType       SystemFilesystemUtilizationMetricAttributeKey = "type"
)

// SystemFilesystemUtilizationMetricConfig provides config for the system.filesystem.utilization metric.
type SystemFilesystemUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemFilesystemUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemFilesystemUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemFilesystemUtilizationMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// MetricsConfig provides config for filesystem metrics.
type MetricsConfig struct {
	SystemFilesystemInodesUsage SystemFilesystemInodesUsageMetricConfig `mapstructure:"system.filesystem.inodes.usage"`
	SystemFilesystemUsage       SystemFilesystemUsageMetricConfig       `mapstructure:"system.filesystem.usage"`
	SystemFilesystemUtilization SystemFilesystemUtilizationMetricConfig `mapstructure:"system.filesystem.utilization"`
}

func DefaultMetricsConfig() MetricsConfig { _ = "STUB: not implemented"; return *new(MetricsConfig) }

// MetricsBuilderConfig is a configuration for filesystem metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}
