// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeBindType specifies the value bind_type attribute.
type AttributeBindType int

const (
	_ AttributeBindType = iota
	AttributeBindTypeServer
	AttributeBindTypeClient
)

// String returns the string representation of the AttributeBindType.
func (av AttributeBindType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeBindType is a helper map of string to AttributeBindType attribute value.
var MapAttributeBindType = map[string]AttributeBindType{
	"server": AttributeBindTypeServer,
	"client": AttributeBindTypeClient,
}

// AttributeDirection specifies the value direction attribute.
type AttributeDirection int

const (
	_ AttributeDirection = iota
	AttributeDirectionSent
	AttributeDirectionReceived
)

// String returns the string representation of the AttributeDirection.
func (av AttributeDirection) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeDirection is a helper map of string to AttributeDirection attribute value.
var MapAttributeDirection = map[string]AttributeDirection{
	"sent":     AttributeDirectionSent,
	"received": AttributeDirectionReceived,
}

// AttributeNetworkDataType specifies the value network_data_type attribute.
type AttributeNetworkDataType int

const (
	_ AttributeNetworkDataType = iota
	AttributeNetworkDataTypeCompressed
	AttributeNetworkDataTypeUncompressed
)

// String returns the string representation of the AttributeNetworkDataType.
func (av AttributeNetworkDataType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeNetworkDataType is a helper map of string to AttributeNetworkDataType attribute value.
var MapAttributeNetworkDataType = map[string]AttributeNetworkDataType{
	"compressed":   AttributeNetworkDataTypeCompressed,
	"uncompressed": AttributeNetworkDataTypeUncompressed,
}

// AttributeOperationType specifies the value operation_type attribute.
type AttributeOperationType int

const (
	_ AttributeOperationType = iota
	AttributeOperationTypeRead
	AttributeOperationTypeWrite
	AttributeOperationTypeSearch
)

// String returns the string representation of the AttributeOperationType.
func (av AttributeOperationType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeOperationType is a helper map of string to AttributeOperationType attribute value.
var MapAttributeOperationType = map[string]AttributeOperationType{
	"read":   AttributeOperationTypeRead,
	"write":  AttributeOperationTypeWrite,
	"search": AttributeOperationTypeSearch,
}

// AttributeSuboperationType specifies the value suboperation_type attribute.
type AttributeSuboperationType int

const (
	_ AttributeSuboperationType = iota
	AttributeSuboperationTypeSecurityDescriptorPropagationsEvent
	AttributeSuboperationTypeSearch
)

// String returns the string representation of the AttributeSuboperationType.
func (av AttributeSuboperationType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeSuboperationType is a helper map of string to AttributeSuboperationType attribute value.
var MapAttributeSuboperationType = map[string]AttributeSuboperationType{
	"security_descriptor_propagations_event": AttributeSuboperationTypeSecurityDescriptorPropagationsEvent,
	"search":                                 AttributeSuboperationTypeSearch,
}

// AttributeSyncResult specifies the value sync_result attribute.
type AttributeSyncResult int

const (
	_ AttributeSyncResult = iota
	AttributeSyncResultSuccess
	AttributeSyncResultSchemaMismatch
	AttributeSyncResultOther
)

// String returns the string representation of the AttributeSyncResult.
func (av AttributeSyncResult) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeSyncResult is a helper map of string to AttributeSyncResult attribute value.
var MapAttributeSyncResult = map[string]AttributeSyncResult{
	"success":         AttributeSyncResultSuccess,
	"schema_mismatch": AttributeSyncResultSchemaMismatch,
	"other":           AttributeSyncResultOther,
}

// AttributeValueType specifies the value value_type attribute.
type AttributeValueType int

const (
	_ AttributeValueType = iota
	AttributeValueTypeDistinguishedNames
	AttributeValueTypeOther
)

// String returns the string representation of the AttributeValueType.
func (av AttributeValueType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeValueType is a helper map of string to AttributeValueType attribute value.
var MapAttributeValueType = map[string]AttributeValueType{
	"distinguished_names": AttributeValueTypeDistinguishedNames,
	"other":               AttributeValueTypeOther,
}

var MetricsInfo = metricsInfo{
	ActiveDirectoryDsBindRate: metricInfo{
		Name: "active_directory.ds.bind.rate",
	},
	ActiveDirectoryDsLdapBindLastSuccessfulTime: metricInfo{
		Name: "active_directory.ds.ldap.bind.last_successful.time",
	},
	ActiveDirectoryDsLdapBindRate: metricInfo{
		Name: "active_directory.ds.ldap.bind.rate",
	},
	ActiveDirectoryDsLdapClientSessionCount: metricInfo{
		Name: "active_directory.ds.ldap.client.session.count",
	},
	ActiveDirectoryDsLdapSearchRate: metricInfo{
		Name: "active_directory.ds.ldap.search.rate",
	},
	ActiveDirectoryDsNameCacheHitRate: metricInfo{
		Name: "active_directory.ds.name_cache.hit_rate",
	},
	ActiveDirectoryDsNotificationQueued: metricInfo{
		Name: "active_directory.ds.notification.queued",
	},
	ActiveDirectoryDsOperationRate: metricInfo{
		Name: "active_directory.ds.operation.rate",
	},
	ActiveDirectoryDsReplicationNetworkIo: metricInfo{
		Name: "active_directory.ds.replication.network.io",
	},
	ActiveDirectoryDsReplicationObjectRate: metricInfo{
		Name: "active_directory.ds.replication.object.rate",
	},
	ActiveDirectoryDsReplicationOperationPending: metricInfo{
		Name: "active_directory.ds.replication.operation.pending",
	},
	ActiveDirectoryDsReplicationPropertyRate: metricInfo{
		Name: "active_directory.ds.replication.property.rate",
	},
	ActiveDirectoryDsReplicationSyncObjectPending: metricInfo{
		Name: "active_directory.ds.replication.sync.object.pending",
	},
	ActiveDirectoryDsReplicationSyncRequestCount: metricInfo{
		Name: "active_directory.ds.replication.sync.request.count",
	},
	ActiveDirectoryDsReplicationValueRate: metricInfo{
		Name: "active_directory.ds.replication.value.rate",
	},
	ActiveDirectoryDsSecurityDescriptorPropagationsEventQueued: metricInfo{
		Name: "active_directory.ds.security_descriptor_propagations_event.queued",
	},
	ActiveDirectoryDsSuboperationRate: metricInfo{
		Name: "active_directory.ds.suboperation.rate",
	},
	ActiveDirectoryDsThreadCount: metricInfo{
		Name: "active_directory.ds.thread.count",
	},
}

type metricsInfo struct {
	ActiveDirectoryDsBindRate                                  metricInfo
	ActiveDirectoryDsLdapBindLastSuccessfulTime                metricInfo
	ActiveDirectoryDsLdapBindRate                              metricInfo
	ActiveDirectoryDsLdapClientSessionCount                    metricInfo
	ActiveDirectoryDsLdapSearchRate                            metricInfo
	ActiveDirectoryDsNameCacheHitRate                          metricInfo
	ActiveDirectoryDsNotificationQueued                        metricInfo
	ActiveDirectoryDsOperationRate                             metricInfo
	ActiveDirectoryDsReplicationNetworkIo                      metricInfo
	ActiveDirectoryDsReplicationObjectRate                     metricInfo
	ActiveDirectoryDsReplicationOperationPending               metricInfo
	ActiveDirectoryDsReplicationPropertyRate                   metricInfo
	ActiveDirectoryDsReplicationSyncObjectPending              metricInfo
	ActiveDirectoryDsReplicationSyncRequestCount               metricInfo
	ActiveDirectoryDsReplicationValueRate                      metricInfo
	ActiveDirectoryDsSecurityDescriptorPropagationsEventQueued metricInfo
	ActiveDirectoryDsSuboperationRate                          metricInfo
	ActiveDirectoryDsThreadCount                               metricInfo
}

type metricInfo struct {
	Name string
}

type metricActiveDirectoryDsBindRate struct {
	data          pmetric.Metric                        // data buffer for generated metric.
	config        ActiveDirectoryDsBindRateMetricConfig // metric config provided by user.
	capacity      int                                   // max observed number of data points added to the metric.
	aggDataPoints []float64                             // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.bind.rate metric with initial data.
func (m *metricActiveDirectoryDsBindRate) init() {
	m.data.SetName("active_directory.ds.bind.rate")
	m.data.SetDescription("The number of binds per second serviced by this domain controller.")
	m.data.SetUnit("{binds}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsBindRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, bindTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsBindRate) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsBindRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsBindRate(cfg ActiveDirectoryDsBindRateMetricConfig) metricActiveDirectoryDsBindRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsBindRate)
}

type metricActiveDirectoryDsLdapBindLastSuccessfulTime struct {
	data     pmetric.Metric                                          // data buffer for generated metric.
	config   ActiveDirectoryDsLdapBindLastSuccessfulTimeMetricConfig // metric config provided by user.
	capacity int                                                     // max observed number of data points added to the metric.
}

// init fills active_directory.ds.ldap.bind.last_successful.time metric with initial data.
func (m *metricActiveDirectoryDsLdapBindLastSuccessfulTime) init() {
	m.data.SetName("active_directory.ds.ldap.bind.last_successful.time")
	m.data.SetDescription("The amount of time taken for the last successful LDAP bind.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
}

func (m *metricActiveDirectoryDsLdapBindLastSuccessfulTime) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsLdapBindLastSuccessfulTime) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsLdapBindLastSuccessfulTime) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsLdapBindLastSuccessfulTime(cfg ActiveDirectoryDsLdapBindLastSuccessfulTimeMetricConfig) metricActiveDirectoryDsLdapBindLastSuccessfulTime {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsLdapBindLastSuccessfulTime)
}

type metricActiveDirectoryDsLdapBindRate struct {
	data     pmetric.Metric                            // data buffer for generated metric.
	config   ActiveDirectoryDsLdapBindRateMetricConfig // metric config provided by user.
	capacity int                                       // max observed number of data points added to the metric.
}

// init fills active_directory.ds.ldap.bind.rate metric with initial data.
func (m *metricActiveDirectoryDsLdapBindRate) init() {
	m.data.SetName("active_directory.ds.ldap.bind.rate")
	m.data.SetDescription("The number of successful LDAP binds per second.")
	m.data.SetUnit("{binds}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsLdapBindRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsLdapBindRate) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsLdapBindRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsLdapBindRate(cfg ActiveDirectoryDsLdapBindRateMetricConfig) metricActiveDirectoryDsLdapBindRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsLdapBindRate)
}

type metricActiveDirectoryDsLdapClientSessionCount struct {
	data     pmetric.Metric                                      // data buffer for generated metric.
	config   ActiveDirectoryDsLdapClientSessionCountMetricConfig // metric config provided by user.
	capacity int                                                 // max observed number of data points added to the metric.
}

// init fills active_directory.ds.ldap.client.session.count metric with initial data.
func (m *metricActiveDirectoryDsLdapClientSessionCount) init() {
	m.data.SetName("active_directory.ds.ldap.client.session.count")
	m.data.SetDescription("The number of connected LDAP client sessions.")
	m.data.SetUnit("{sessions}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsLdapClientSessionCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsLdapClientSessionCount) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsLdapClientSessionCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsLdapClientSessionCount(cfg ActiveDirectoryDsLdapClientSessionCountMetricConfig) metricActiveDirectoryDsLdapClientSessionCount {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsLdapClientSessionCount)
}

type metricActiveDirectoryDsLdapSearchRate struct {
	data     pmetric.Metric                              // data buffer for generated metric.
	config   ActiveDirectoryDsLdapSearchRateMetricConfig // metric config provided by user.
	capacity int                                         // max observed number of data points added to the metric.
}

// init fills active_directory.ds.ldap.search.rate metric with initial data.
func (m *metricActiveDirectoryDsLdapSearchRate) init() {
	m.data.SetName("active_directory.ds.ldap.search.rate")
	m.data.SetDescription("The number of LDAP searches per second.")
	m.data.SetUnit("{searches}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsLdapSearchRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsLdapSearchRate) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsLdapSearchRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsLdapSearchRate(cfg ActiveDirectoryDsLdapSearchRateMetricConfig) metricActiveDirectoryDsLdapSearchRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsLdapSearchRate)
}

type metricActiveDirectoryDsNameCacheHitRate struct {
	data     pmetric.Metric                                // data buffer for generated metric.
	config   ActiveDirectoryDsNameCacheHitRateMetricConfig // metric config provided by user.
	capacity int                                           // max observed number of data points added to the metric.
}

// init fills active_directory.ds.name_cache.hit_rate metric with initial data.
func (m *metricActiveDirectoryDsNameCacheHitRate) init() {
	m.data.SetName("active_directory.ds.name_cache.hit_rate")
	m.data.SetDescription("The percentage of directory object name component lookups that are satisfied by the Directory System Agent's name cache.")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
}

func (m *metricActiveDirectoryDsNameCacheHitRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsNameCacheHitRate) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsNameCacheHitRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsNameCacheHitRate(cfg ActiveDirectoryDsNameCacheHitRateMetricConfig) metricActiveDirectoryDsNameCacheHitRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsNameCacheHitRate)
}

type metricActiveDirectoryDsNotificationQueued struct {
	data     pmetric.Metric                                  // data buffer for generated metric.
	config   ActiveDirectoryDsNotificationQueuedMetricConfig // metric config provided by user.
	capacity int                                             // max observed number of data points added to the metric.
}

// init fills active_directory.ds.notification.queued metric with initial data.
func (m *metricActiveDirectoryDsNotificationQueued) init() {
	m.data.SetName("active_directory.ds.notification.queued")
	m.data.SetDescription("The number of pending update notifications that have been queued to push to clients.")
	m.data.SetUnit("{notifications}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsNotificationQueued) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsNotificationQueued) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsNotificationQueued) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsNotificationQueued(cfg ActiveDirectoryDsNotificationQueuedMetricConfig) metricActiveDirectoryDsNotificationQueued {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsNotificationQueued)
}

type metricActiveDirectoryDsOperationRate struct {
	data          pmetric.Metric                             // data buffer for generated metric.
	config        ActiveDirectoryDsOperationRateMetricConfig // metric config provided by user.
	capacity      int                                        // max observed number of data points added to the metric.
	aggDataPoints []float64                                  // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.operation.rate metric with initial data.
func (m *metricActiveDirectoryDsOperationRate) init() {
	m.data.SetName("active_directory.ds.operation.rate")
	m.data.SetDescription("The number of operations performed per second.")
	m.data.SetUnit("{operations}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsOperationRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, operationTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsOperationRate) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsOperationRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsOperationRate(cfg ActiveDirectoryDsOperationRateMetricConfig) metricActiveDirectoryDsOperationRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsOperationRate)
}

type metricActiveDirectoryDsReplicationNetworkIo struct {
	data          pmetric.Metric                                    // data buffer for generated metric.
	config        ActiveDirectoryDsReplicationNetworkIoMetricConfig // metric config provided by user.
	capacity      int                                               // max observed number of data points added to the metric.
	aggDataPoints []int64                                           // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.replication.network.io metric with initial data.
func (m *metricActiveDirectoryDsReplicationNetworkIo) init() {
	m.data.SetName("active_directory.ds.replication.network.io")
	m.data.SetDescription("The amount of network data transmitted by the Directory Replication Agent.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsReplicationNetworkIo) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, directionAttributeValue string, networkDataTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsReplicationNetworkIo) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsReplicationNetworkIo) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsReplicationNetworkIo(cfg ActiveDirectoryDsReplicationNetworkIoMetricConfig) metricActiveDirectoryDsReplicationNetworkIo {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsReplicationNetworkIo)
}

type metricActiveDirectoryDsReplicationObjectRate struct {
	data          pmetric.Metric                                     // data buffer for generated metric.
	config        ActiveDirectoryDsReplicationObjectRateMetricConfig // metric config provided by user.
	capacity      int                                                // max observed number of data points added to the metric.
	aggDataPoints []float64                                          // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.replication.object.rate metric with initial data.
func (m *metricActiveDirectoryDsReplicationObjectRate) init() {
	m.data.SetName("active_directory.ds.replication.object.rate")
	m.data.SetDescription("The number of objects transmitted by the Directory Replication Agent per second.")
	m.data.SetUnit("{objects}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsReplicationObjectRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, directionAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsReplicationObjectRate) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsReplicationObjectRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsReplicationObjectRate(cfg ActiveDirectoryDsReplicationObjectRateMetricConfig) metricActiveDirectoryDsReplicationObjectRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsReplicationObjectRate)
}

type metricActiveDirectoryDsReplicationOperationPending struct {
	data     pmetric.Metric                                           // data buffer for generated metric.
	config   ActiveDirectoryDsReplicationOperationPendingMetricConfig // metric config provided by user.
	capacity int                                                      // max observed number of data points added to the metric.
}

// init fills active_directory.ds.replication.operation.pending metric with initial data.
func (m *metricActiveDirectoryDsReplicationOperationPending) init() {
	m.data.SetName("active_directory.ds.replication.operation.pending")
	m.data.SetDescription("The number of pending replication operations for the Directory Replication Agent.")
	m.data.SetUnit("{operations}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsReplicationOperationPending) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsReplicationOperationPending) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsReplicationOperationPending) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsReplicationOperationPending(cfg ActiveDirectoryDsReplicationOperationPendingMetricConfig) metricActiveDirectoryDsReplicationOperationPending {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsReplicationOperationPending)
}

type metricActiveDirectoryDsReplicationPropertyRate struct {
	data          pmetric.Metric                                       // data buffer for generated metric.
	config        ActiveDirectoryDsReplicationPropertyRateMetricConfig // metric config provided by user.
	capacity      int                                                  // max observed number of data points added to the metric.
	aggDataPoints []float64                                            // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.replication.property.rate metric with initial data.
func (m *metricActiveDirectoryDsReplicationPropertyRate) init() {
	m.data.SetName("active_directory.ds.replication.property.rate")
	m.data.SetDescription("The number of properties transmitted by the Directory Replication Agent per second.")
	m.data.SetUnit("{properties}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsReplicationPropertyRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, directionAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsReplicationPropertyRate) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsReplicationPropertyRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsReplicationPropertyRate(cfg ActiveDirectoryDsReplicationPropertyRateMetricConfig) metricActiveDirectoryDsReplicationPropertyRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsReplicationPropertyRate)
}

type metricActiveDirectoryDsReplicationSyncObjectPending struct {
	data     pmetric.Metric                                            // data buffer for generated metric.
	config   ActiveDirectoryDsReplicationSyncObjectPendingMetricConfig // metric config provided by user.
	capacity int                                                       // max observed number of data points added to the metric.
}

// init fills active_directory.ds.replication.sync.object.pending metric with initial data.
func (m *metricActiveDirectoryDsReplicationSyncObjectPending) init() {
	m.data.SetName("active_directory.ds.replication.sync.object.pending")
	m.data.SetDescription("The number of objects remaining until the full sync completes for the Directory Replication Agent.")
	m.data.SetUnit("{objects}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsReplicationSyncObjectPending) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsReplicationSyncObjectPending) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsReplicationSyncObjectPending) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsReplicationSyncObjectPending(cfg ActiveDirectoryDsReplicationSyncObjectPendingMetricConfig) metricActiveDirectoryDsReplicationSyncObjectPending {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsReplicationSyncObjectPending)
}

type metricActiveDirectoryDsReplicationSyncRequestCount struct {
	data          pmetric.Metric                                           // data buffer for generated metric.
	config        ActiveDirectoryDsReplicationSyncRequestCountMetricConfig // metric config provided by user.
	capacity      int                                                      // max observed number of data points added to the metric.
	aggDataPoints []int64                                                  // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.replication.sync.request.count metric with initial data.
func (m *metricActiveDirectoryDsReplicationSyncRequestCount) init() {
	m.data.SetName("active_directory.ds.replication.sync.request.count")
	m.data.SetDescription("The number of sync requests made by the Directory Replication Agent.")
	m.data.SetUnit("{requests}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsReplicationSyncRequestCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, syncResultAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsReplicationSyncRequestCount) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsReplicationSyncRequestCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsReplicationSyncRequestCount(cfg ActiveDirectoryDsReplicationSyncRequestCountMetricConfig) metricActiveDirectoryDsReplicationSyncRequestCount {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsReplicationSyncRequestCount)
}

type metricActiveDirectoryDsReplicationValueRate struct {
	data          pmetric.Metric                                    // data buffer for generated metric.
	config        ActiveDirectoryDsReplicationValueRateMetricConfig // metric config provided by user.
	capacity      int                                               // max observed number of data points added to the metric.
	aggDataPoints []float64                                         // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.replication.value.rate metric with initial data.
func (m *metricActiveDirectoryDsReplicationValueRate) init() {
	m.data.SetName("active_directory.ds.replication.value.rate")
	m.data.SetDescription("The number of values transmitted by the Directory Replication Agent per second.")
	m.data.SetUnit("{values}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsReplicationValueRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, directionAttributeValue string, valueTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsReplicationValueRate) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsReplicationValueRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsReplicationValueRate(cfg ActiveDirectoryDsReplicationValueRateMetricConfig) metricActiveDirectoryDsReplicationValueRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsReplicationValueRate)
}

type metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued struct {
	data     pmetric.Metric                                                         // data buffer for generated metric.
	config   ActiveDirectoryDsSecurityDescriptorPropagationsEventQueuedMetricConfig // metric config provided by user.
	capacity int                                                                    // max observed number of data points added to the metric.
}

// init fills active_directory.ds.security_descriptor_propagations_event.queued metric with initial data.
func (m *metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued) init() {
	m.data.SetName("active_directory.ds.security_descriptor_propagations_event.queued")
	m.data.SetDescription("The number of security descriptor propagation events that are queued for processing.")
	m.data.SetUnit("{events}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued(cfg ActiveDirectoryDsSecurityDescriptorPropagationsEventQueuedMetricConfig) metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued)
}

type metricActiveDirectoryDsSuboperationRate struct {
	data          pmetric.Metric                                // data buffer for generated metric.
	config        ActiveDirectoryDsSuboperationRateMetricConfig // metric config provided by user.
	capacity      int                                           // max observed number of data points added to the metric.
	aggDataPoints []float64                                     // slice containing number of aggregated datapoints at each index
}

// init fills active_directory.ds.suboperation.rate metric with initial data.
func (m *metricActiveDirectoryDsSuboperationRate) init() {
	m.data.SetName("active_directory.ds.suboperation.rate")
	m.data.SetDescription("The rate of sub-operations performed.")
	m.data.SetUnit("{suboperations}/s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricActiveDirectoryDsSuboperationRate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, suboperationTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsSuboperationRate) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsSuboperationRate) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsSuboperationRate(cfg ActiveDirectoryDsSuboperationRateMetricConfig) metricActiveDirectoryDsSuboperationRate {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsSuboperationRate)
}

type metricActiveDirectoryDsThreadCount struct {
	data     pmetric.Metric                           // data buffer for generated metric.
	config   ActiveDirectoryDsThreadCountMetricConfig // metric config provided by user.
	capacity int                                      // max observed number of data points added to the metric.
}

// init fills active_directory.ds.thread.count metric with initial data.
func (m *metricActiveDirectoryDsThreadCount) init() {
	m.data.SetName("active_directory.ds.thread.count")
	m.data.SetDescription("The number of threads in use by the directory service.")
	m.data.SetUnit("{threads}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricActiveDirectoryDsThreadCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricActiveDirectoryDsThreadCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricActiveDirectoryDsThreadCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricActiveDirectoryDsThreadCount(cfg ActiveDirectoryDsThreadCountMetricConfig) metricActiveDirectoryDsThreadCount {
	_ = "STUB: not implemented"
	return *new(metricActiveDirectoryDsThreadCount)
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                                           MetricsBuilderConfig // config of the metrics builder.
	startTime                                                        pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                                                  int                  // maximum observed number of metrics per resource.
	metricsBuffer                                                    pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                                        component.BuildInfo  // contains version information.
	metricActiveDirectoryDsBindRate                                  metricActiveDirectoryDsBindRate
	metricActiveDirectoryDsLdapBindLastSuccessfulTime                metricActiveDirectoryDsLdapBindLastSuccessfulTime
	metricActiveDirectoryDsLdapBindRate                              metricActiveDirectoryDsLdapBindRate
	metricActiveDirectoryDsLdapClientSessionCount                    metricActiveDirectoryDsLdapClientSessionCount
	metricActiveDirectoryDsLdapSearchRate                            metricActiveDirectoryDsLdapSearchRate
	metricActiveDirectoryDsNameCacheHitRate                          metricActiveDirectoryDsNameCacheHitRate
	metricActiveDirectoryDsNotificationQueued                        metricActiveDirectoryDsNotificationQueued
	metricActiveDirectoryDsOperationRate                             metricActiveDirectoryDsOperationRate
	metricActiveDirectoryDsReplicationNetworkIo                      metricActiveDirectoryDsReplicationNetworkIo
	metricActiveDirectoryDsReplicationObjectRate                     metricActiveDirectoryDsReplicationObjectRate
	metricActiveDirectoryDsReplicationOperationPending               metricActiveDirectoryDsReplicationOperationPending
	metricActiveDirectoryDsReplicationPropertyRate                   metricActiveDirectoryDsReplicationPropertyRate
	metricActiveDirectoryDsReplicationSyncObjectPending              metricActiveDirectoryDsReplicationSyncObjectPending
	metricActiveDirectoryDsReplicationSyncRequestCount               metricActiveDirectoryDsReplicationSyncRequestCount
	metricActiveDirectoryDsReplicationValueRate                      metricActiveDirectoryDsReplicationValueRate
	metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued metricActiveDirectoryDsSecurityDescriptorPropagationsEventQueued
	metricActiveDirectoryDsSuboperationRate                          metricActiveDirectoryDsSuboperationRate
	metricActiveDirectoryDsThreadCount                               metricActiveDirectoryDsThreadCount
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	_ = "STUB: not implemented"

	// WithStartTime sets startTime on the metrics builder.
	return
}

func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	_ = "STUB: not implemented"
	return *new(MetricBuilderOption)
}

func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	_ = "STUB: not implemented"
	return nil
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"
	return
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"

	// WithResource sets the provided resource on the emitted ResourceMetrics.
	// It's recommended to use ResourceBuilder to create the resource.
	return
}

func WithResource(res pcommon.Resource) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	_ = "STUB: not implemented"
	return
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	_ = "STUB: not implemented"
	return *new(pmetric.Metrics)
}

// RecordActiveDirectoryDsBindRateDataPoint adds a data point to active_directory.ds.bind.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsBindRateDataPoint(ts pcommon.Timestamp, val float64, bindTypeAttributeValue AttributeBindType) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsLdapBindLastSuccessfulTimeDataPoint adds a data point to active_directory.ds.ldap.bind.last_successful.time metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsLdapBindLastSuccessfulTimeDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsLdapBindRateDataPoint adds a data point to active_directory.ds.ldap.bind.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsLdapBindRateDataPoint(ts pcommon.Timestamp, val float64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsLdapClientSessionCountDataPoint adds a data point to active_directory.ds.ldap.client.session.count metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsLdapClientSessionCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsLdapSearchRateDataPoint adds a data point to active_directory.ds.ldap.search.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsLdapSearchRateDataPoint(ts pcommon.Timestamp, val float64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsNameCacheHitRateDataPoint adds a data point to active_directory.ds.name_cache.hit_rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsNameCacheHitRateDataPoint(ts pcommon.Timestamp, val float64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsNotificationQueuedDataPoint adds a data point to active_directory.ds.notification.queued metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsNotificationQueuedDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsOperationRateDataPoint adds a data point to active_directory.ds.operation.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsOperationRateDataPoint(ts pcommon.Timestamp, val float64, operationTypeAttributeValue AttributeOperationType) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsReplicationNetworkIoDataPoint adds a data point to active_directory.ds.replication.network.io metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsReplicationNetworkIoDataPoint(ts pcommon.Timestamp, val int64, directionAttributeValue AttributeDirection, networkDataTypeAttributeValue AttributeNetworkDataType) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsReplicationObjectRateDataPoint adds a data point to active_directory.ds.replication.object.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsReplicationObjectRateDataPoint(ts pcommon.Timestamp, val float64, directionAttributeValue AttributeDirection) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsReplicationOperationPendingDataPoint adds a data point to active_directory.ds.replication.operation.pending metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsReplicationOperationPendingDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsReplicationPropertyRateDataPoint adds a data point to active_directory.ds.replication.property.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsReplicationPropertyRateDataPoint(ts pcommon.Timestamp, val float64, directionAttributeValue AttributeDirection) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsReplicationSyncObjectPendingDataPoint adds a data point to active_directory.ds.replication.sync.object.pending metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsReplicationSyncObjectPendingDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsReplicationSyncRequestCountDataPoint adds a data point to active_directory.ds.replication.sync.request.count metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsReplicationSyncRequestCountDataPoint(ts pcommon.Timestamp, val int64, syncResultAttributeValue AttributeSyncResult) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsReplicationValueRateDataPoint adds a data point to active_directory.ds.replication.value.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsReplicationValueRateDataPoint(ts pcommon.Timestamp, val float64, directionAttributeValue AttributeDirection, valueTypeAttributeValue AttributeValueType) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsSecurityDescriptorPropagationsEventQueuedDataPoint adds a data point to active_directory.ds.security_descriptor_propagations_event.queued metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsSecurityDescriptorPropagationsEventQueuedDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsSuboperationRateDataPoint adds a data point to active_directory.ds.suboperation.rate metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsSuboperationRateDataPoint(ts pcommon.Timestamp, val float64, suboperationTypeAttributeValue AttributeSuboperationType) {
	_ = "STUB: not implemented"
	return
}

// RecordActiveDirectoryDsThreadCountDataPoint adds a data point to active_directory.ds.thread.count metric.
func (mb *MetricsBuilder) RecordActiveDirectoryDsThreadCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) { _ = "STUB: not implemented"; return }
