// Code generated by MockGen. DO NOT EDIT.
// Source: google.golang.org/grpc/credentials (interfaces: PerRPCCredentials)
//
// Generated by this command:
//
//	mockgen -package grpcmock google.golang.org/grpc/credentials PerRPCCredentials
//

// Package grpcmock is a generated GoMock package.
package grpcmock

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockPerRPCCredentials is a mock of PerRPCCredentials interface.
type MockPerRPCCredentials struct {
	ctrl     *gomock.Controller
	recorder *MockPerRPCCredentialsMockRecorder
}

// MockPerRPCCredentialsMockRecorder is the mock recorder for MockPerRPCCredentials.
type MockPerRPCCredentialsMockRecorder struct {
	mock *MockPerRPCCredentials
}

// NewMockPerRPCCredentials creates a new mock instance.
func NewMockPerRPCCredentials(ctrl *gomock.Controller) *MockPerRPCCredentials {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPerRPCCredentials) EXPECT() *MockPerRPCCredentialsMockRecorder {
	_ = "STUB: not implemented"

	// GetRequestMetadata mocks base method.
	return nil
}

func (m *MockPerRPCCredentials) GetRequestMetadata(arg0 context.Context, arg1 ...string) (map[string]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRequestMetadata indicates an expected call of GetRequestMetadata.
func (mr *MockPerRPCCredentialsMockRecorder) GetRequestMetadata(arg0 any, arg1 ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RequireTransportSecurity mocks base method.
func (m *MockPerRPCCredentials) RequireTransportSecurity() bool {
	_ = "STUB: not implemented"
	return false
}

// RequireTransportSecurity indicates an expected call of RequireTransportSecurity.
func (mr *MockPerRPCCredentialsMockRecorder) RequireTransportSecurity() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
