// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// NfsClientNetCountMetricAttributeKey specifies the key of an attribute for the nfs.client.net.count metric.
type NfsClientNetCountMetricAttributeKey string

const (
	NfsClientNetCountMetricAttributeKeyNetworkTransport NfsClientNetCountMetricAttributeKey = "network.transport"
)

// NfsClientNetCountMetricConfig provides config for the nfs.client.net.count metric.
type NfsClientNetCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsClientNetCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsClientNetCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsClientNetCountMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// NfsClientNetTCPConnectionAcceptedMetricConfig provides config for the nfs.client.net.tcp.connection.accepted metric.
type NfsClientNetTCPConnectionAcceptedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsClientNetTCPConnectionAcceptedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NfsClientOperationCountMetricAttributeKey specifies the key of an attribute for the nfs.client.operation.count metric.
type NfsClientOperationCountMetricAttributeKey string

const (
	NfsClientOperationCountMetricAttributeKeyOncRPCVersion    NfsClientOperationCountMetricAttributeKey = "onc_rpc.version"
	NfsClientOperationCountMetricAttributeKeyNfsOperationName NfsClientOperationCountMetricAttributeKey = "nfs.operation.name"
)

// NfsClientOperationCountMetricConfig provides config for the nfs.client.operation.count metric.
type NfsClientOperationCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsClientOperationCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsClientOperationCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsClientOperationCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// NfsClientProcedureCountMetricAttributeKey specifies the key of an attribute for the nfs.client.procedure.count metric.
type NfsClientProcedureCountMetricAttributeKey string

const (
	NfsClientProcedureCountMetricAttributeKeyOncRPCVersion       NfsClientProcedureCountMetricAttributeKey = "onc_rpc.version"
	NfsClientProcedureCountMetricAttributeKeyOncRPCProcedureName NfsClientProcedureCountMetricAttributeKey = "onc_rpc.procedure.name"
)

// NfsClientProcedureCountMetricConfig provides config for the nfs.client.procedure.count metric.
type NfsClientProcedureCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsClientProcedureCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsClientProcedureCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsClientProcedureCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// NfsClientRPCAuthrefreshCountMetricConfig provides config for the nfs.client.rpc.authrefresh.count metric.
type NfsClientRPCAuthrefreshCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsClientRPCAuthrefreshCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NfsClientRPCCountMetricConfig provides config for the nfs.client.rpc.count metric.
type NfsClientRPCCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsClientRPCCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NfsClientRPCRetransmitCountMetricConfig provides config for the nfs.client.rpc.retransmit.count metric.
type NfsClientRPCRetransmitCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsClientRPCRetransmitCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NfsServerFhStaleCountMetricConfig provides config for the nfs.server.fh.stale.count metric.
type NfsServerFhStaleCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsServerFhStaleCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NfsServerIoMetricAttributeKey specifies the key of an attribute for the nfs.server.io metric.
type NfsServerIoMetricAttributeKey string

const (
	NfsServerIoMetricAttributeKeyNetworkIoDirection NfsServerIoMetricAttributeKey = "network.io.direction"
)

// NfsServerIoMetricConfig provides config for the nfs.server.io metric.
type NfsServerIoMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsServerIoMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsServerIoMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsServerIoMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// NfsServerNetCountMetricAttributeKey specifies the key of an attribute for the nfs.server.net.count metric.
type NfsServerNetCountMetricAttributeKey string

const (
	NfsServerNetCountMetricAttributeKeyNetworkTransport NfsServerNetCountMetricAttributeKey = "network.transport"
)

// NfsServerNetCountMetricConfig provides config for the nfs.server.net.count metric.
type NfsServerNetCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsServerNetCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsServerNetCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsServerNetCountMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// NfsServerNetTCPConnectionAcceptedMetricConfig provides config for the nfs.server.net.tcp.connection.accepted metric.
type NfsServerNetTCPConnectionAcceptedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsServerNetTCPConnectionAcceptedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NfsServerOperationCountMetricAttributeKey specifies the key of an attribute for the nfs.server.operation.count metric.
type NfsServerOperationCountMetricAttributeKey string

const (
	NfsServerOperationCountMetricAttributeKeyOncRPCVersion    NfsServerOperationCountMetricAttributeKey = "onc_rpc.version"
	NfsServerOperationCountMetricAttributeKeyNfsOperationName NfsServerOperationCountMetricAttributeKey = "nfs.operation.name"
)

// NfsServerOperationCountMetricConfig provides config for the nfs.server.operation.count metric.
type NfsServerOperationCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsServerOperationCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsServerOperationCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsServerOperationCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// NfsServerProcedureCountMetricAttributeKey specifies the key of an attribute for the nfs.server.procedure.count metric.
type NfsServerProcedureCountMetricAttributeKey string

const (
	NfsServerProcedureCountMetricAttributeKeyOncRPCVersion       NfsServerProcedureCountMetricAttributeKey = "onc_rpc.version"
	NfsServerProcedureCountMetricAttributeKeyOncRPCProcedureName NfsServerProcedureCountMetricAttributeKey = "onc_rpc.procedure.name"
)

// NfsServerProcedureCountMetricConfig provides config for the nfs.server.procedure.count metric.
type NfsServerProcedureCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsServerProcedureCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsServerProcedureCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsServerProcedureCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// NfsServerRepcacheRequestsMetricAttributeKey specifies the key of an attribute for the nfs.server.repcache.requests metric.
type NfsServerRepcacheRequestsMetricAttributeKey string

const (
	NfsServerRepcacheRequestsMetricAttributeKeyNfsServerRepcacheStatus NfsServerRepcacheRequestsMetricAttributeKey = "nfs.server.repcache.status"
)

// NfsServerRepcacheRequestsMetricConfig provides config for the nfs.server.repcache.requests metric.
type NfsServerRepcacheRequestsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                        `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsServerRepcacheRequestsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsServerRepcacheRequestsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsServerRepcacheRequestsMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// NfsServerRPCCountMetricAttributeKey specifies the key of an attribute for the nfs.server.rpc.count metric.
type NfsServerRPCCountMetricAttributeKey string

const (
	NfsServerRPCCountMetricAttributeKeyErrorType NfsServerRPCCountMetricAttributeKey = "error.type"
)

// NfsServerRPCCountMetricConfig provides config for the nfs.server.rpc.count metric.
type NfsServerRPCCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NfsServerRPCCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NfsServerRPCCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NfsServerRPCCountMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// NfsServerThreadCountMetricConfig provides config for the nfs.server.thread.count metric.
type NfsServerThreadCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NfsServerThreadCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// MetricsConfig provides config for nfs metrics.
type MetricsConfig struct {
	NfsClientNetCount                 NfsClientNetCountMetricConfig                 `mapstructure:"nfs.client.net.count"`
	NfsClientNetTCPConnectionAccepted NfsClientNetTCPConnectionAcceptedMetricConfig `mapstructure:"nfs.client.net.tcp.connection.accepted"`
	NfsClientOperationCount           NfsClientOperationCountMetricConfig           `mapstructure:"nfs.client.operation.count"`
	NfsClientProcedureCount           NfsClientProcedureCountMetricConfig           `mapstructure:"nfs.client.procedure.count"`
	NfsClientRPCAuthrefreshCount      NfsClientRPCAuthrefreshCountMetricConfig      `mapstructure:"nfs.client.rpc.authrefresh.count"`
	NfsClientRPCCount                 NfsClientRPCCountMetricConfig                 `mapstructure:"nfs.client.rpc.count"`
	NfsClientRPCRetransmitCount       NfsClientRPCRetransmitCountMetricConfig       `mapstructure:"nfs.client.rpc.retransmit.count"`
	NfsServerFhStaleCount             NfsServerFhStaleCountMetricConfig             `mapstructure:"nfs.server.fh.stale.count"`
	NfsServerIo                       NfsServerIoMetricConfig                       `mapstructure:"nfs.server.io"`
	NfsServerNetCount                 NfsServerNetCountMetricConfig                 `mapstructure:"nfs.server.net.count"`
	NfsServerNetTCPConnectionAccepted NfsServerNetTCPConnectionAcceptedMetricConfig `mapstructure:"nfs.server.net.tcp.connection.accepted"`
	NfsServerOperationCount           NfsServerOperationCountMetricConfig           `mapstructure:"nfs.server.operation.count"`
	NfsServerProcedureCount           NfsServerProcedureCountMetricConfig           `mapstructure:"nfs.server.procedure.count"`
	NfsServerRepcacheRequests         NfsServerRepcacheRequestsMetricConfig         `mapstructure:"nfs.server.repcache.requests"`
	NfsServerRPCCount                 NfsServerRPCCountMetricConfig                 `mapstructure:"nfs.server.rpc.count"`
	NfsServerThreadCount              NfsServerThreadCountMetricConfig              `mapstructure:"nfs.server.thread.count"`
}

func DefaultMetricsConfig() MetricsConfig { _ = "STUB: not implemented"; return *new(MetricsConfig) }

// MetricsBuilderConfig is a configuration for nfs metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}
