// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/scraper"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeErrorType specifies the value error.type attribute.
type AttributeErrorType int

const (
	_ AttributeErrorType = iota
	AttributeErrorTypeFormat
	AttributeErrorTypeAuth
	AttributeErrorTypeClient
)

// String returns the string representation of the AttributeErrorType.
func (av AttributeErrorType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeErrorType is a helper map of string to AttributeErrorType attribute value.
var MapAttributeErrorType = map[string]AttributeErrorType{
	"format": AttributeErrorTypeFormat,
	"auth":   AttributeErrorTypeAuth,
	"client": AttributeErrorTypeClient,
}

// AttributeNetworkIoDirection specifies the value network.io.direction attribute.
type AttributeNetworkIoDirection int

const (
	_ AttributeNetworkIoDirection = iota
	AttributeNetworkIoDirectionTransmit
	AttributeNetworkIoDirectionReceive
)

// String returns the string representation of the AttributeNetworkIoDirection.
func (av AttributeNetworkIoDirection) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeNetworkIoDirection is a helper map of string to AttributeNetworkIoDirection attribute value.
var MapAttributeNetworkIoDirection = map[string]AttributeNetworkIoDirection{
	"transmit": AttributeNetworkIoDirectionTransmit,
	"receive":  AttributeNetworkIoDirectionReceive,
}

// AttributeNetworkTransport specifies the value network.transport attribute.
type AttributeNetworkTransport int

const (
	_ AttributeNetworkTransport = iota
	AttributeNetworkTransportUdp
	AttributeNetworkTransportTcp
)

// String returns the string representation of the AttributeNetworkTransport.
func (av AttributeNetworkTransport) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeNetworkTransport is a helper map of string to AttributeNetworkTransport attribute value.
var MapAttributeNetworkTransport = map[string]AttributeNetworkTransport{
	"udp": AttributeNetworkTransportUdp,
	"tcp": AttributeNetworkTransportTcp,
}

// AttributeNfsServerRepcacheStatus specifies the value nfs.server.repcache.status attribute.
type AttributeNfsServerRepcacheStatus int

const (
	_ AttributeNfsServerRepcacheStatus = iota
	AttributeNfsServerRepcacheStatusHit
	AttributeNfsServerRepcacheStatusMiss
	AttributeNfsServerRepcacheStatusNocache
)

// String returns the string representation of the AttributeNfsServerRepcacheStatus.
func (av AttributeNfsServerRepcacheStatus) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeNfsServerRepcacheStatus is a helper map of string to AttributeNfsServerRepcacheStatus attribute value.
var MapAttributeNfsServerRepcacheStatus = map[string]AttributeNfsServerRepcacheStatus{
	"hit":     AttributeNfsServerRepcacheStatusHit,
	"miss":    AttributeNfsServerRepcacheStatusMiss,
	"nocache": AttributeNfsServerRepcacheStatusNocache,
}

var MetricsInfo = metricsInfo{
	NfsClientNetCount: metricInfo{
		Name: "nfs.client.net.count",
	},
	NfsClientNetTCPConnectionAccepted: metricInfo{
		Name: "nfs.client.net.tcp.connection.accepted",
	},
	NfsClientOperationCount: metricInfo{
		Name: "nfs.client.operation.count",
	},
	NfsClientProcedureCount: metricInfo{
		Name: "nfs.client.procedure.count",
	},
	NfsClientRPCAuthrefreshCount: metricInfo{
		Name: "nfs.client.rpc.authrefresh.count",
	},
	NfsClientRPCCount: metricInfo{
		Name: "nfs.client.rpc.count",
	},
	NfsClientRPCRetransmitCount: metricInfo{
		Name: "nfs.client.rpc.retransmit.count",
	},
	NfsServerFhStaleCount: metricInfo{
		Name: "nfs.server.fh.stale.count",
	},
	NfsServerIo: metricInfo{
		Name: "nfs.server.io",
	},
	NfsServerNetCount: metricInfo{
		Name: "nfs.server.net.count",
	},
	NfsServerNetTCPConnectionAccepted: metricInfo{
		Name: "nfs.server.net.tcp.connection.accepted",
	},
	NfsServerOperationCount: metricInfo{
		Name: "nfs.server.operation.count",
	},
	NfsServerProcedureCount: metricInfo{
		Name: "nfs.server.procedure.count",
	},
	NfsServerRepcacheRequests: metricInfo{
		Name: "nfs.server.repcache.requests",
	},
	NfsServerRPCCount: metricInfo{
		Name: "nfs.server.rpc.count",
	},
	NfsServerThreadCount: metricInfo{
		Name: "nfs.server.thread.count",
	},
}

type metricsInfo struct {
	NfsClientNetCount                 metricInfo
	NfsClientNetTCPConnectionAccepted metricInfo
	NfsClientOperationCount           metricInfo
	NfsClientProcedureCount           metricInfo
	NfsClientRPCAuthrefreshCount      metricInfo
	NfsClientRPCCount                 metricInfo
	NfsClientRPCRetransmitCount       metricInfo
	NfsServerFhStaleCount             metricInfo
	NfsServerIo                       metricInfo
	NfsServerNetCount                 metricInfo
	NfsServerNetTCPConnectionAccepted metricInfo
	NfsServerOperationCount           metricInfo
	NfsServerProcedureCount           metricInfo
	NfsServerRepcacheRequests         metricInfo
	NfsServerRPCCount                 metricInfo
	NfsServerThreadCount              metricInfo
}

type metricInfo struct {
	Name string
}

type metricNfsClientNetCount struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        NfsClientNetCountMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills nfs.client.net.count metric with initial data.
func (m *metricNfsClientNetCount) init() {
	m.data.SetName("nfs.client.net.count")
	m.data.SetDescription("Reports the count of kernel NFS client TCP segments and UDP datagrams handled.")
	m.data.SetUnit("{record}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsClientNetCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, networkTransportAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsClientNetCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsClientNetCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsClientNetCount(cfg NfsClientNetCountMetricConfig) metricNfsClientNetCount {
	_ = "STUB: not implemented"
	return *new(metricNfsClientNetCount)
}

type metricNfsClientNetTCPConnectionAccepted struct {
	data     pmetric.Metric                                // data buffer for generated metric.
	config   NfsClientNetTCPConnectionAcceptedMetricConfig // metric config provided by user.
	capacity int                                           // max observed number of data points added to the metric.
}

// init fills nfs.client.net.tcp.connection.accepted metric with initial data.
func (m *metricNfsClientNetTCPConnectionAccepted) init() {
	m.data.SetName("nfs.client.net.tcp.connection.accepted")
	m.data.SetDescription("Reports the count of kernel NFS client TCP connections accepted")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsClientNetTCPConnectionAccepted) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsClientNetTCPConnectionAccepted) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsClientNetTCPConnectionAccepted) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsClientNetTCPConnectionAccepted(cfg NfsClientNetTCPConnectionAcceptedMetricConfig) metricNfsClientNetTCPConnectionAccepted {
	_ = "STUB: not implemented"
	return *new(metricNfsClientNetTCPConnectionAccepted)
}

type metricNfsClientOperationCount struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        NfsClientOperationCountMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills nfs.client.operation.count metric with initial data.
func (m *metricNfsClientOperationCount) init() {
	m.data.SetName("nfs.client.operation.count")
	m.data.SetDescription("Reports the count of kernel NFSv4+ client operations")
	m.data.SetUnit("{operation}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsClientOperationCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, nfsOperationNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsClientOperationCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsClientOperationCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsClientOperationCount(cfg NfsClientOperationCountMetricConfig) metricNfsClientOperationCount {
	_ = "STUB: not implemented"
	return *new(metricNfsClientOperationCount)
}

type metricNfsClientProcedureCount struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        NfsClientProcedureCountMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills nfs.client.procedure.count metric with initial data.
func (m *metricNfsClientProcedureCount) init() {
	m.data.SetName("nfs.client.procedure.count")
	m.data.SetDescription("Reports the count of kernel NFS client procedures")
	m.data.SetUnit("{procedure}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsClientProcedureCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, oncRPCProcedureNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsClientProcedureCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsClientProcedureCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsClientProcedureCount(cfg NfsClientProcedureCountMetricConfig) metricNfsClientProcedureCount {
	_ = "STUB: not implemented"
	return *new(metricNfsClientProcedureCount)
}

type metricNfsClientRPCAuthrefreshCount struct {
	data     pmetric.Metric                           // data buffer for generated metric.
	config   NfsClientRPCAuthrefreshCountMetricConfig // metric config provided by user.
	capacity int                                      // max observed number of data points added to the metric.
}

// init fills nfs.client.rpc.authrefresh.count metric with initial data.
func (m *metricNfsClientRPCAuthrefreshCount) init() {
	m.data.SetName("nfs.client.rpc.authrefresh.count")
	m.data.SetDescription("Reports the count of kernel NFS client RPC authentication refreshes")
	m.data.SetUnit("{authrefresh}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsClientRPCAuthrefreshCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsClientRPCAuthrefreshCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsClientRPCAuthrefreshCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsClientRPCAuthrefreshCount(cfg NfsClientRPCAuthrefreshCountMetricConfig) metricNfsClientRPCAuthrefreshCount {
	_ = "STUB: not implemented"
	return *new(metricNfsClientRPCAuthrefreshCount)
}

type metricNfsClientRPCCount struct {
	data     pmetric.Metric                // data buffer for generated metric.
	config   NfsClientRPCCountMetricConfig // metric config provided by user.
	capacity int                           // max observed number of data points added to the metric.
}

// init fills nfs.client.rpc.count metric with initial data.
func (m *metricNfsClientRPCCount) init() {
	m.data.SetName("nfs.client.rpc.count")
	m.data.SetDescription("Reports the count of kernel NFS client RPCs sent, regardless of whether they're accepted/rejected by the server.")
	m.data.SetUnit("{request}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsClientRPCCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsClientRPCCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsClientRPCCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsClientRPCCount(cfg NfsClientRPCCountMetricConfig) metricNfsClientRPCCount {
	_ = "STUB: not implemented"
	return *new(metricNfsClientRPCCount)
}

type metricNfsClientRPCRetransmitCount struct {
	data     pmetric.Metric                          // data buffer for generated metric.
	config   NfsClientRPCRetransmitCountMetricConfig // metric config provided by user.
	capacity int                                     // max observed number of data points added to the metric.
}

// init fills nfs.client.rpc.retransmit.count metric with initial data.
func (m *metricNfsClientRPCRetransmitCount) init() {
	m.data.SetName("nfs.client.rpc.retransmit.count")
	m.data.SetDescription("Reports the count of kernel NFS client RPC retransmits")
	m.data.SetUnit("{retransmit}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsClientRPCRetransmitCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsClientRPCRetransmitCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsClientRPCRetransmitCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsClientRPCRetransmitCount(cfg NfsClientRPCRetransmitCountMetricConfig) metricNfsClientRPCRetransmitCount {
	_ = "STUB: not implemented"
	return *new(metricNfsClientRPCRetransmitCount)
}

type metricNfsServerFhStaleCount struct {
	data     pmetric.Metric                    // data buffer for generated metric.
	config   NfsServerFhStaleCountMetricConfig // metric config provided by user.
	capacity int                               // max observed number of data points added to the metric.
}

// init fills nfs.server.fh.stale.count metric with initial data.
func (m *metricNfsServerFhStaleCount) init() {
	m.data.SetName("nfs.server.fh.stale.count")
	m.data.SetDescription("Reports the cumulative count of kernel NFS server stale file handles.")
	m.data.SetUnit("{fh}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsServerFhStaleCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerFhStaleCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerFhStaleCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerFhStaleCount(cfg NfsServerFhStaleCountMetricConfig) metricNfsServerFhStaleCount {
	_ = "STUB: not implemented"
	return *new(metricNfsServerFhStaleCount)
}

type metricNfsServerIo struct {
	data          pmetric.Metric          // data buffer for generated metric.
	config        NfsServerIoMetricConfig // metric config provided by user.
	capacity      int                     // max observed number of data points added to the metric.
	aggDataPoints []int64                 // slice containing number of aggregated datapoints at each index
}

// init fills nfs.server.io metric with initial data.
func (m *metricNfsServerIo) init() {
	m.data.SetName("nfs.server.io")
	m.data.SetDescription("Reports the count of kernel NFS server bytes returned to receive and transmit (read and write) requests.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsServerIo) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, networkIoDirectionAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerIo) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerIo) emit(metrics pmetric.MetricSlice) { _ = "STUB: not implemented"; return }

func newMetricNfsServerIo(cfg NfsServerIoMetricConfig) metricNfsServerIo {
	_ = "STUB: not implemented"
	return *new(metricNfsServerIo)
}

type metricNfsServerNetCount struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        NfsServerNetCountMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills nfs.server.net.count metric with initial data.
func (m *metricNfsServerNetCount) init() {
	m.data.SetName("nfs.server.net.count")
	m.data.SetDescription("Reports the count of kernel NFS server TCP segments and UDP datagrams handled.")
	m.data.SetUnit("{request}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsServerNetCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, networkTransportAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerNetCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerNetCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerNetCount(cfg NfsServerNetCountMetricConfig) metricNfsServerNetCount {
	_ = "STUB: not implemented"
	return *new(metricNfsServerNetCount)
}

type metricNfsServerNetTCPConnectionAccepted struct {
	data     pmetric.Metric                                // data buffer for generated metric.
	config   NfsServerNetTCPConnectionAcceptedMetricConfig // metric config provided by user.
	capacity int                                           // max observed number of data points added to the metric.
}

// init fills nfs.server.net.tcp.connection.accepted metric with initial data.
func (m *metricNfsServerNetTCPConnectionAccepted) init() {
	m.data.SetName("nfs.server.net.tcp.connection.accepted")
	m.data.SetDescription("Reports the count of kernel NFS server TCP connections accepted")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsServerNetTCPConnectionAccepted) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerNetTCPConnectionAccepted) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerNetTCPConnectionAccepted) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerNetTCPConnectionAccepted(cfg NfsServerNetTCPConnectionAcceptedMetricConfig) metricNfsServerNetTCPConnectionAccepted {
	_ = "STUB: not implemented"
	return *new(metricNfsServerNetTCPConnectionAccepted)
}

type metricNfsServerOperationCount struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        NfsServerOperationCountMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills nfs.server.operation.count metric with initial data.
func (m *metricNfsServerOperationCount) init() {
	m.data.SetName("nfs.server.operation.count")
	m.data.SetDescription("Reports the count of kernel NFSv4+ server operations")
	m.data.SetUnit("{operation}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsServerOperationCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, nfsOperationNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerOperationCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerOperationCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerOperationCount(cfg NfsServerOperationCountMetricConfig) metricNfsServerOperationCount {
	_ = "STUB: not implemented"
	return *new(metricNfsServerOperationCount)
}

type metricNfsServerProcedureCount struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        NfsServerProcedureCountMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills nfs.server.procedure.count metric with initial data.
func (m *metricNfsServerProcedureCount) init() {
	m.data.SetName("nfs.server.procedure.count")
	m.data.SetDescription("Reports the count of kernel NFS server procedures")
	m.data.SetUnit("{procedure}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsServerProcedureCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, oncRPCProcedureNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerProcedureCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerProcedureCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerProcedureCount(cfg NfsServerProcedureCountMetricConfig) metricNfsServerProcedureCount {
	_ = "STUB: not implemented"
	return *new(metricNfsServerProcedureCount)
}

type metricNfsServerRepcacheRequests struct {
	data          pmetric.Metric                        // data buffer for generated metric.
	config        NfsServerRepcacheRequestsMetricConfig // metric config provided by user.
	capacity      int                                   // max observed number of data points added to the metric.
	aggDataPoints []int64                               // slice containing number of aggregated datapoints at each index
}

// init fills nfs.server.repcache.requests metric with initial data.
func (m *metricNfsServerRepcacheRequests) init() {
	m.data.SetName("nfs.server.repcache.requests")
	m.data.SetDescription("Reports the kernel NFS server reply cache request count by cache hit status.")
	m.data.SetUnit("{request}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsServerRepcacheRequests) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, nfsServerRepcacheStatusAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerRepcacheRequests) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerRepcacheRequests) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerRepcacheRequests(cfg NfsServerRepcacheRequestsMetricConfig) metricNfsServerRepcacheRequests {
	_ = "STUB: not implemented"
	return *new(metricNfsServerRepcacheRequests)
}

type metricNfsServerRPCCount struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        NfsServerRPCCountMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills nfs.server.rpc.count metric with initial data.
func (m *metricNfsServerRPCCount) init() {
	m.data.SetName("nfs.server.rpc.count")
	m.data.SetDescription("Reports the count of kernel NFS server RPCs handled.")
	m.data.SetUnit("{request}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNfsServerRPCCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, errorTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerRPCCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerRPCCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerRPCCount(cfg NfsServerRPCCountMetricConfig) metricNfsServerRPCCount {
	_ = "STUB: not implemented"
	return *new(metricNfsServerRPCCount)
}

type metricNfsServerThreadCount struct {
	data     pmetric.Metric                   // data buffer for generated metric.
	config   NfsServerThreadCountMetricConfig // metric config provided by user.
	capacity int                              // max observed number of data points added to the metric.
}

// init fills nfs.server.thread.count metric with initial data.
func (m *metricNfsServerThreadCount) init() {
	m.data.SetName("nfs.server.thread.count")
	m.data.SetDescription("Reports the count of kernel NFS server available threads")
	m.data.SetUnit("{thread}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNfsServerThreadCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNfsServerThreadCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNfsServerThreadCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricNfsServerThreadCount(cfg NfsServerThreadCountMetricConfig) metricNfsServerThreadCount {
	_ = "STUB: not implemented"
	return *new(metricNfsServerThreadCount)
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                  MetricsBuilderConfig // config of the metrics builder.
	startTime                               pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                         int                  // maximum observed number of metrics per resource.
	metricsBuffer                           pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                               component.BuildInfo  // contains version information.
	metricNfsClientNetCount                 metricNfsClientNetCount
	metricNfsClientNetTCPConnectionAccepted metricNfsClientNetTCPConnectionAccepted
	metricNfsClientOperationCount           metricNfsClientOperationCount
	metricNfsClientProcedureCount           metricNfsClientProcedureCount
	metricNfsClientRPCAuthrefreshCount      metricNfsClientRPCAuthrefreshCount
	metricNfsClientRPCCount                 metricNfsClientRPCCount
	metricNfsClientRPCRetransmitCount       metricNfsClientRPCRetransmitCount
	metricNfsServerFhStaleCount             metricNfsServerFhStaleCount
	metricNfsServerIo                       metricNfsServerIo
	metricNfsServerNetCount                 metricNfsServerNetCount
	metricNfsServerNetTCPConnectionAccepted metricNfsServerNetTCPConnectionAccepted
	metricNfsServerOperationCount           metricNfsServerOperationCount
	metricNfsServerProcedureCount           metricNfsServerProcedureCount
	metricNfsServerRepcacheRequests         metricNfsServerRepcacheRequests
	metricNfsServerRPCCount                 metricNfsServerRPCCount
	metricNfsServerThreadCount              metricNfsServerThreadCount
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	_ = "STUB: not implemented"

	// WithStartTime sets startTime on the metrics builder.
	return
}

func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	_ = "STUB: not implemented"
	return *new(MetricBuilderOption)
}

func NewMetricsBuilder(mbc MetricsBuilderConfig, settings scraper.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	_ = "STUB: not implemented"
	return nil
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"
	return
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"

	// WithResource sets the provided resource on the emitted ResourceMetrics.
	// It's recommended to use ResourceBuilder to create the resource.
	return
}

func WithResource(res pcommon.Resource) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	_ = "STUB: not implemented"
	return
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	_ = "STUB: not implemented"
	return *new(pmetric.Metrics)
}

// RecordNfsClientNetCountDataPoint adds a data point to nfs.client.net.count metric.
func (mb *MetricsBuilder) RecordNfsClientNetCountDataPoint(ts pcommon.Timestamp, val int64, networkTransportAttributeValue AttributeNetworkTransport) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsClientNetTCPConnectionAcceptedDataPoint adds a data point to nfs.client.net.tcp.connection.accepted metric.
func (mb *MetricsBuilder) RecordNfsClientNetTCPConnectionAcceptedDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsClientOperationCountDataPoint adds a data point to nfs.client.operation.count metric.
func (mb *MetricsBuilder) RecordNfsClientOperationCountDataPoint(ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, nfsOperationNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsClientProcedureCountDataPoint adds a data point to nfs.client.procedure.count metric.
func (mb *MetricsBuilder) RecordNfsClientProcedureCountDataPoint(ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, oncRPCProcedureNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsClientRPCAuthrefreshCountDataPoint adds a data point to nfs.client.rpc.authrefresh.count metric.
func (mb *MetricsBuilder) RecordNfsClientRPCAuthrefreshCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsClientRPCCountDataPoint adds a data point to nfs.client.rpc.count metric.
func (mb *MetricsBuilder) RecordNfsClientRPCCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsClientRPCRetransmitCountDataPoint adds a data point to nfs.client.rpc.retransmit.count metric.
func (mb *MetricsBuilder) RecordNfsClientRPCRetransmitCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerFhStaleCountDataPoint adds a data point to nfs.server.fh.stale.count metric.
func (mb *MetricsBuilder) RecordNfsServerFhStaleCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerIoDataPoint adds a data point to nfs.server.io metric.
func (mb *MetricsBuilder) RecordNfsServerIoDataPoint(ts pcommon.Timestamp, val int64, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerNetCountDataPoint adds a data point to nfs.server.net.count metric.
func (mb *MetricsBuilder) RecordNfsServerNetCountDataPoint(ts pcommon.Timestamp, val int64, networkTransportAttributeValue AttributeNetworkTransport) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerNetTCPConnectionAcceptedDataPoint adds a data point to nfs.server.net.tcp.connection.accepted metric.
func (mb *MetricsBuilder) RecordNfsServerNetTCPConnectionAcceptedDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerOperationCountDataPoint adds a data point to nfs.server.operation.count metric.
func (mb *MetricsBuilder) RecordNfsServerOperationCountDataPoint(ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, nfsOperationNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerProcedureCountDataPoint adds a data point to nfs.server.procedure.count metric.
func (mb *MetricsBuilder) RecordNfsServerProcedureCountDataPoint(ts pcommon.Timestamp, val int64, oncRPCVersionAttributeValue int64, oncRPCProcedureNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerRepcacheRequestsDataPoint adds a data point to nfs.server.repcache.requests metric.
func (mb *MetricsBuilder) RecordNfsServerRepcacheRequestsDataPoint(ts pcommon.Timestamp, val int64, nfsServerRepcacheStatusAttributeValue AttributeNfsServerRepcacheStatus) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerRPCCountDataPoint adds a data point to nfs.server.rpc.count metric.
func (mb *MetricsBuilder) RecordNfsServerRPCCountDataPoint(ts pcommon.Timestamp, val int64, errorTypeAttributeValue AttributeErrorType) {
	_ = "STUB: not implemented"
	return
}

// RecordNfsServerThreadCountDataPoint adds a data point to nfs.server.thread.count metric.
func (mb *MetricsBuilder) RecordNfsServerThreadCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) { _ = "STUB: not implemented"; return }
