// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package githubscraper

import (
	"context"
	"encoding/json"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// BranchHistory includes the requested fields of the GraphQL type Ref.
// The GraphQL type's documentation follows.
//
// Represents a Git reference.
type BranchHistory struct {
	// The object the ref points to. Returns null when object does not exist.
	Target BranchHistoryTargetGitObject `json:"-"`
}

// GetTarget returns BranchHistory.Target, and is useful for accessing the field via an interface.
func (v *BranchHistory) GetTarget() BranchHistoryTargetGitObject {
	_ = "STUB: not implemented"
	return *new(BranchHistoryTargetGitObject)
}

func (v *BranchHistory) UnmarshalJSON(b []byte) error { _ = "STUB: not implemented"; return nil }

type __premarshalBranchHistory struct {
	Target json.RawMessage `json:"target"`
}

func (v *BranchHistory) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (v *BranchHistory) __premarshalJSON() (*__premarshalBranchHistory, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BranchHistoryTargetBlob includes the requested fields of the GraphQL type Blob.
// The GraphQL type's documentation follows.
//
// Represents a Git blob.
type BranchHistoryTargetBlob struct {
	Typename string `json:"__typename"`
}

// GetTypename returns BranchHistoryTargetBlob.Typename, and is useful for accessing the field via an interface.
func (v *BranchHistoryTargetBlob) GetTypename() string {
	_ = "STUB: not implemented"

	// BranchHistoryTargetCommit includes the requested fields of the GraphQL type Commit.
	// The GraphQL type's documentation follows.
	//
	// Represents a Git commit.
	return ""
}

type BranchHistoryTargetCommit struct {
	Typename string `json:"__typename"`
	// The Node ID of the Commit object
	Id string `json:"id"`
	// The linear commit history starting from (and including) this commit, in the same order as `git log`.
	History BranchHistoryTargetCommitHistoryCommitHistoryConnection `json:"history"`
}

// GetTypename returns BranchHistoryTargetCommit.Typename, and is useful for accessing the field via an interface.
func (v *BranchHistoryTargetCommit) GetTypename() string {
	_ = "STUB: not implemented"

	// GetId returns BranchHistoryTargetCommit.Id, and is useful for accessing the field via an interface.
	return ""
}

func (v *BranchHistoryTargetCommit) GetId() string {
	_ = "STUB: not implemented"

	// GetHistory returns BranchHistoryTargetCommit.History, and is useful for accessing the field via an interface.
	return ""
}

func (v *BranchHistoryTargetCommit) GetHistory() BranchHistoryTargetCommitHistoryCommitHistoryConnection {
	_ = "STUB: not implemented"

	// BranchHistoryTargetCommitHistoryCommitHistoryConnection includes the requested fields of the GraphQL type CommitHistoryConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for Commit.
	return *new(BranchHistoryTargetCommitHistoryCommitHistoryConnection)
}

type BranchHistoryTargetCommitHistoryCommitHistoryConnection struct {
	// A list of nodes.
	Nodes []CommitNode `json:"nodes"`
	// Information to aid in pagination.
	PageInfo BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns BranchHistoryTargetCommitHistoryCommitHistoryConnection.Nodes, and is useful for accessing the field via an interface.
func (v *BranchHistoryTargetCommitHistoryCommitHistoryConnection) GetNodes() []CommitNode {
	_ = "STUB: not implemented"

	// GetPageInfo returns BranchHistoryTargetCommitHistoryCommitHistoryConnection.PageInfo, and is useful for accessing the field via an interface.
	return nil
}

func (v *BranchHistoryTargetCommitHistoryCommitHistoryConnection) GetPageInfo() BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo {
	_ = "STUB: not implemented"

	// BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
	// The GraphQL type's documentation follows.
	//
	// Information about pagination in a connection.
	return *new(BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo)
}

type BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
}

// GetEndCursor returns BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo) GetEndCursor() string {
	_ = "STUB: not implemented"
	return ""

	// GetHasNextPage returns BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
}

func (v *BranchHistoryTargetCommitHistoryCommitHistoryConnectionPageInfo) GetHasNextPage() bool {
	_ = "STUB: not implemented"
	return false

	// BranchHistoryTargetGitObject includes the requested fields of the GraphQL interface GitObject.
	//
	// BranchHistoryTargetGitObject is implemented by the following types:
	// BranchHistoryTargetBlob
	// BranchHistoryTargetCommit
	// BranchHistoryTargetTag
	// BranchHistoryTargetTree
	// The GraphQL type's documentation follows.
	//
	// Represents a Git object.
}

type BranchHistoryTargetGitObject interface {
	implementsGraphQLInterfaceBranchHistoryTargetGitObject()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *BranchHistoryTargetBlob) implementsGraphQLInterfaceBranchHistoryTargetGitObject() {
	_ = "STUB: not implemented"
	return
}
func (v *BranchHistoryTargetCommit) implementsGraphQLInterfaceBranchHistoryTargetGitObject() {
	_ = "STUB: not implemented"
	return
}
func (v *BranchHistoryTargetTag) implementsGraphQLInterfaceBranchHistoryTargetGitObject() {
	_ = "STUB: not implemented"
	return
}
func (v *BranchHistoryTargetTree) implementsGraphQLInterfaceBranchHistoryTargetGitObject() {
	_ = "STUB: not implemented"
	return
}

func __unmarshalBranchHistoryTargetGitObject(b []byte, v *BranchHistoryTargetGitObject) error {
	_ = "STUB: not implemented"
	return nil
}

func __marshalBranchHistoryTargetGitObject(v *BranchHistoryTargetGitObject) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BranchHistoryTargetTag includes the requested fields of the GraphQL type Tag.
// The GraphQL type's documentation follows.
//
// Represents a Git tag.
type BranchHistoryTargetTag struct {
	Typename string `json:"__typename"`
}

// GetTypename returns BranchHistoryTargetTag.Typename, and is useful for accessing the field via an interface.
func (v *BranchHistoryTargetTag) GetTypename() string {
	_ = "STUB: not implemented"

	// BranchHistoryTargetTree includes the requested fields of the GraphQL type Tree.
	// The GraphQL type's documentation follows.
	//
	// Represents a Git tree.
	return ""
}

type BranchHistoryTargetTree struct {
	Typename string `json:"__typename"`
}

// GetTypename returns BranchHistoryTargetTree.Typename, and is useful for accessing the field via an interface.
func (v *BranchHistoryTargetTree) GetTypename() string {
	_ = "STUB: not implemented"

	// BranchNode includes the requested fields of the GraphQL type Ref.
	// The GraphQL type's documentation follows.
	//
	// Represents a Git reference.
	return ""
}

type BranchNode struct {
	// The ref name.
	Name string `json:"name"`
	// Compares the current ref as a base ref to another head ref, if the comparison can be made.
	Compare BranchNodeCompareComparison `json:"compare"`
	// The repository the ref belongs to.
	Repository BranchNodeRepository `json:"repository"`
}

// GetName returns BranchNode.Name, and is useful for accessing the field via an interface.
func (v *BranchNode) GetName() string {
	_ = "STUB: not implemented"

	// GetCompare returns BranchNode.Compare, and is useful for accessing the field via an interface.
	return ""
}

func (v *BranchNode) GetCompare() BranchNodeCompareComparison {
	_ = "STUB: not implemented"

	// GetRepository returns BranchNode.Repository, and is useful for accessing the field via an interface.
	return *new(BranchNodeCompareComparison)
}

func (v *BranchNode) GetRepository() BranchNodeRepository {
	_ = "STUB: not implemented"
	return *

	// BranchNodeCompareComparison includes the requested fields of the GraphQL type Comparison.
	// The GraphQL type's documentation follows.
	//
	// Represents a comparison between two commit revisions.
	new(BranchNodeRepository)
}

type BranchNodeCompareComparison struct {
	// The number of commits ahead of the base branch.
	AheadBy int `json:"aheadBy"`
	// The number of commits behind the base branch.
	BehindBy int `json:"behindBy"`
}

// GetAheadBy returns BranchNodeCompareComparison.AheadBy, and is useful for accessing the field via an interface.
func (v *BranchNodeCompareComparison) GetAheadBy() int {
	_ = "STUB: not implemented"

	// GetBehindBy returns BranchNodeCompareComparison.BehindBy, and is useful for accessing the field via an interface.
	return 0
}

func (v *BranchNodeCompareComparison) GetBehindBy() int {
	_ = "STUB: not implemented"

	// BranchNodeRepository includes the requested fields of the GraphQL type Repository.
	// The GraphQL type's documentation follows.
	//
	// A repository contains the content for a project.
	return 0
}

type BranchNodeRepository struct {
	// The name of the repository.
	Name string `json:"name"`
	// The Ref associated with the repository's default branch.
	DefaultBranchRef BranchNodeRepositoryDefaultBranchRef `json:"defaultBranchRef"`
}

// GetName returns BranchNodeRepository.Name, and is useful for accessing the field via an interface.
func (v *BranchNodeRepository) GetName() string {
	_ = "STUB: not implemented"

	// GetDefaultBranchRef returns BranchNodeRepository.DefaultBranchRef, and is useful for accessing the field via an interface.
	return ""
}

func (v *BranchNodeRepository) GetDefaultBranchRef() BranchNodeRepositoryDefaultBranchRef {
	_ = "STUB: not implemented"
	return *new(BranchNodeRepositoryDefaultBranchRef)
}

// BranchNodeRepositoryDefaultBranchRef includes the requested fields of the GraphQL type Ref.
// The GraphQL type's documentation follows.
//
// Represents a Git reference.
type BranchNodeRepositoryDefaultBranchRef struct {
	// The ref name.
	Name string `json:"name"`
}

// GetName returns BranchNodeRepositoryDefaultBranchRef.Name, and is useful for accessing the field via an interface.
func (v *BranchNodeRepositoryDefaultBranchRef) GetName() string {
	_ = "STUB: not implemented"

	// CommitNode includes the requested fields of the GraphQL type Commit.
	// The GraphQL type's documentation follows.
	//
	// Represents a Git commit.
	return ""
}

type CommitNode struct {
	// The datetime when this commit was committed.
	CommittedDate time.Time `json:"committedDate"`
	// The number of additions in this commit.
	Additions int `json:"additions"`
	// The number of deletions in this commit.
	Deletions int `json:"deletions"`
}

// GetCommittedDate returns CommitNode.CommittedDate, and is useful for accessing the field via an interface.
func (v *CommitNode) GetCommittedDate() time.Time {
	_ = "STUB: not implemented"
	return *

	// GetAdditions returns CommitNode.Additions, and is useful for accessing the field via an interface.
	new(time.Time)
}

func (v *CommitNode) GetAdditions() int {
	_ = "STUB: not implemented"

	// GetDeletions returns CommitNode.Deletions, and is useful for accessing the field via an interface.
	return 0
}

func (v *CommitNode) GetDeletions() int {
	_ = "STUB: not implemented"

	// MergedPullRequestNode includes the requested fields of the GraphQL type PullRequest.
	// The GraphQL type's documentation follows.
	//
	// A repository pull request.
	return 0
}

type MergedPullRequestNode struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
	// Whether or not the pull request was merged.
	Merged bool `json:"merged"`
	// The date and time that the pull request was merged.
	MergedAt time.Time `json:"mergedAt"`
	// The commit that was created when this pull request was merged.
	MergeCommit MergedPullRequestNodeMergeCommit `json:"mergeCommit"`
	// Identifies the name of the head Ref associated with the pull request, even if the ref has been deleted.
	HeadRefName string `json:"headRefName"`
	// A list of reviews associated with the pull request.
	Reviews MergedPullRequestNodeReviewsPullRequestReviewConnection `json:"reviews"`
}

// GetCreatedAt returns MergedPullRequestNode.CreatedAt, and is useful for accessing the field via an interface.
func (v *MergedPullRequestNode) GetCreatedAt() time.Time {
	_ = "STUB: not implemented"

	// GetMerged returns MergedPullRequestNode.Merged, and is useful for accessing the field via an interface.
	return *new(time.Time)
}

func (v *MergedPullRequestNode) GetMerged() bool {
	_ = "STUB: not implemented"

	// GetMergedAt returns MergedPullRequestNode.MergedAt, and is useful for accessing the field via an interface.
	return false
}

func (v *MergedPullRequestNode) GetMergedAt() time.Time {
	_ = "STUB: not implemented"

	// GetMergeCommit returns MergedPullRequestNode.MergeCommit, and is useful for accessing the field via an interface.
	return *new(time.Time)
}

func (v *MergedPullRequestNode) GetMergeCommit() MergedPullRequestNodeMergeCommit {
	_ = "STUB: not implemented"
	return *

	// GetHeadRefName returns MergedPullRequestNode.HeadRefName, and is useful for accessing the field via an interface.
	new(MergedPullRequestNodeMergeCommit)
}

func (v *MergedPullRequestNode) GetHeadRefName() string { _ = "STUB: not implemented"; return "" }

// GetReviews returns MergedPullRequestNode.Reviews, and is useful for accessing the field via an interface.
func (v *MergedPullRequestNode) GetReviews() MergedPullRequestNodeReviewsPullRequestReviewConnection {
	_ = "STUB: not implemented"

	// MergedPullRequestNodeMergeCommit includes the requested fields of the GraphQL type Commit.
	// The GraphQL type's documentation follows.
	//
	// Represents a Git commit.
	return *new(MergedPullRequestNodeReviewsPullRequestReviewConnection)
}

type MergedPullRequestNodeMergeCommit struct {
	// The deployments associated with a commit.
	Deployments MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection `json:"deployments"`
}

// GetDeployments returns MergedPullRequestNodeMergeCommit.Deployments, and is useful for accessing the field via an interface.
func (v *MergedPullRequestNodeMergeCommit) GetDeployments() MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection {
	_ = "STUB: not implemented"
	return *

	// MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection includes the requested fields of the GraphQL type DeploymentConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for Deployment.
	new(MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection)
}

type MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection struct {
	// A list of nodes.
	Nodes []MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment `json:"nodes"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetNodes returns MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection) GetNodes() []MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment {
	_ = "STUB: not implemented"

	// GetTotalCount returns MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection.TotalCount, and is useful for accessing the field via an interface.
	return nil
}

func (v *MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnection) GetTotalCount() int {
	_ = "STUB: not implemented"
	return 0

	// MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment includes the requested fields of the GraphQL type Deployment.
	// The GraphQL type's documentation follows.
	//
	// Represents triggered deployment instance.
}

type MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetCreatedAt returns MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment.CreatedAt, and is useful for accessing the field via an interface.
func (v *MergedPullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment) GetCreatedAt() time.Time {
	_ = "STUB: not implemented"
	return *

	// MergedPullRequestNodeReviewsPullRequestReviewConnection includes the requested fields of the GraphQL type PullRequestReviewConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for PullRequestReview.
	new(time.Time)
}

type MergedPullRequestNodeReviewsPullRequestReviewConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
	// A list of nodes.
	Nodes []MergedPullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview `json:"nodes"`
}

// GetTotalCount returns MergedPullRequestNodeReviewsPullRequestReviewConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *MergedPullRequestNodeReviewsPullRequestReviewConnection) GetTotalCount() int {
	_ = "STUB: not implemented"
	return 0

	// GetNodes returns MergedPullRequestNodeReviewsPullRequestReviewConnection.Nodes, and is useful for accessing the field via an interface.
}

func (v *MergedPullRequestNodeReviewsPullRequestReviewConnection) GetNodes() []MergedPullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview {
	_ = "STUB: not implemented"

	// MergedPullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview includes the requested fields of the GraphQL type PullRequestReview.
	// The GraphQL type's documentation follows.
	//
	// A review object for a given pull request.
	return nil
}

type MergedPullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetCreatedAt returns MergedPullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview.CreatedAt, and is useful for accessing the field via an interface.
func (v *MergedPullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview) GetCreatedAt() time.Time {
	_ = "STUB: not implemented"
	return *

	// PullRequestNode includes the requested fields of the GraphQL type PullRequest.
	// The GraphQL type's documentation follows.
	//
	// A repository pull request.
	new(time.Time)
}

type PullRequestNode struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
	// Whether or not the pull request was merged.
	Merged bool `json:"merged"`
	// The date and time that the pull request was merged.
	MergedAt time.Time `json:"mergedAt"`
	// The commit that was created when this pull request was merged.
	MergeCommit PullRequestNodeMergeCommit `json:"mergeCommit"`
	// Identifies the name of the head Ref associated with the pull request, even if the ref has been deleted.
	HeadRefName string `json:"headRefName"`
	// A list of reviews associated with the pull request.
	Reviews PullRequestNodeReviewsPullRequestReviewConnection `json:"reviews"`
}

// GetCreatedAt returns PullRequestNode.CreatedAt, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetCreatedAt() time.Time {
	_ = "STUB: not implemented"

	// GetMerged returns PullRequestNode.Merged, and is useful for accessing the field via an interface.
	return *new(time.Time)
}

func (v *PullRequestNode) GetMerged() bool {
	_ = "STUB: not implemented"

	// GetMergedAt returns PullRequestNode.MergedAt, and is useful for accessing the field via an interface.
	return false
}

func (v *PullRequestNode) GetMergedAt() time.Time {
	_ = "STUB: not implemented"

	// GetMergeCommit returns PullRequestNode.MergeCommit, and is useful for accessing the field via an interface.
	return *new(time.Time)
}

func (v *PullRequestNode) GetMergeCommit() PullRequestNodeMergeCommit {
	_ = "STUB: not implemented"
	return *

	// GetHeadRefName returns PullRequestNode.HeadRefName, and is useful for accessing the field via an interface.
	new(PullRequestNodeMergeCommit)
}

func (v *PullRequestNode) GetHeadRefName() string { _ = "STUB: not implemented"; return "" }

// GetReviews returns PullRequestNode.Reviews, and is useful for accessing the field via an interface.
func (v *PullRequestNode) GetReviews() PullRequestNodeReviewsPullRequestReviewConnection {
	_ = "STUB: not implemented"

	// PullRequestNodeMergeCommit includes the requested fields of the GraphQL type Commit.
	// The GraphQL type's documentation follows.
	//
	// Represents a Git commit.
	return *new(PullRequestNodeReviewsPullRequestReviewConnection)
}

type PullRequestNodeMergeCommit struct {
	// The deployments associated with a commit.
	Deployments PullRequestNodeMergeCommitDeploymentsDeploymentConnection `json:"deployments"`
}

// GetDeployments returns PullRequestNodeMergeCommit.Deployments, and is useful for accessing the field via an interface.
func (v *PullRequestNodeMergeCommit) GetDeployments() PullRequestNodeMergeCommitDeploymentsDeploymentConnection {
	_ = "STUB: not implemented"
	return *

	// PullRequestNodeMergeCommitDeploymentsDeploymentConnection includes the requested fields of the GraphQL type DeploymentConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for Deployment.
	new(PullRequestNodeMergeCommitDeploymentsDeploymentConnection)
}

type PullRequestNodeMergeCommitDeploymentsDeploymentConnection struct {
	// A list of nodes.
	Nodes []PullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment `json:"nodes"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetNodes returns PullRequestNodeMergeCommitDeploymentsDeploymentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *PullRequestNodeMergeCommitDeploymentsDeploymentConnection) GetNodes() []PullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment {
	_ = "STUB: not implemented"

	// GetTotalCount returns PullRequestNodeMergeCommitDeploymentsDeploymentConnection.TotalCount, and is useful for accessing the field via an interface.
	return nil
}

func (v *PullRequestNodeMergeCommitDeploymentsDeploymentConnection) GetTotalCount() int {
	_ = "STUB: not implemented"
	return 0

	// PullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment includes the requested fields of the GraphQL type Deployment.
	// The GraphQL type's documentation follows.
	//
	// Represents triggered deployment instance.
}

type PullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetCreatedAt returns PullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment.CreatedAt, and is useful for accessing the field via an interface.
func (v *PullRequestNodeMergeCommitDeploymentsDeploymentConnectionNodesDeployment) GetCreatedAt() time.Time {
	_ = "STUB: not implemented"
	return *

	// PullRequestNodeReviewsPullRequestReviewConnection includes the requested fields of the GraphQL type PullRequestReviewConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for PullRequestReview.
	new(time.Time)
}

type PullRequestNodeReviewsPullRequestReviewConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
	// A list of nodes.
	Nodes []PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview `json:"nodes"`
}

// GetTotalCount returns PullRequestNodeReviewsPullRequestReviewConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *PullRequestNodeReviewsPullRequestReviewConnection) GetTotalCount() int {
	_ = "STUB: not implemented"
	return 0

	// GetNodes returns PullRequestNodeReviewsPullRequestReviewConnection.Nodes, and is useful for accessing the field via an interface.
}

func (v *PullRequestNodeReviewsPullRequestReviewConnection) GetNodes() []PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview {
	_ = "STUB: not implemented"

	// PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview includes the requested fields of the GraphQL type PullRequestReview.
	// The GraphQL type's documentation follows.
	//
	// A review object for a given pull request.
	return nil
}

type PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetCreatedAt returns PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview.CreatedAt, and is useful for accessing the field via an interface.
func (v *PullRequestNodeReviewsPullRequestReviewConnectionNodesPullRequestReview) GetCreatedAt() time.Time {
	_ = "STUB: not implemented"
	return *

	// SearchNode includes the requested fields of the GraphQL interface SearchResultItem.
	//
	// SearchNode is implemented by the following types:
	// SearchNodeApp
	// SearchNodeDiscussion
	// SearchNodeIssue
	// SearchNodeMarketplaceListing
	// SearchNodeOrganization
	// SearchNodePullRequest
	// SearchNodeRepository
	// SearchNodeUser
	// The GraphQL type's documentation follows.
	//
	// The results of a search.
	new(time.Time)
}

type SearchNode interface {
	implementsGraphQLInterfaceSearchNode()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *SearchNodeApp) implementsGraphQLInterfaceSearchNode() { _ = "STUB: not implemented"; return }
func (v *SearchNodeDiscussion) implementsGraphQLInterfaceSearchNode() {
	_ = "STUB: not implemented"
	return
}
func (v *SearchNodeIssue) implementsGraphQLInterfaceSearchNode() { _ = "STUB: not implemented"; return }
func (v *SearchNodeMarketplaceListing) implementsGraphQLInterfaceSearchNode() {
	_ = "STUB: not implemented"
	return
}
func (v *SearchNodeOrganization) implementsGraphQLInterfaceSearchNode() {
	_ = "STUB: not implemented"
	return
}
func (v *SearchNodePullRequest) implementsGraphQLInterfaceSearchNode() {
	_ = "STUB: not implemented"
	return
}
func (v *SearchNodeRepository) implementsGraphQLInterfaceSearchNode() {
	_ = "STUB: not implemented"
	return
}
func (v *SearchNodeUser) implementsGraphQLInterfaceSearchNode() { _ = "STUB: not implemented"; return }

func __unmarshalSearchNode(b []byte, v *SearchNode) error { _ = "STUB: not implemented"; return nil }

func __marshalSearchNode(v *SearchNode) ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// SearchNodeApp includes the requested fields of the GraphQL type App.
// The GraphQL type's documentation follows.
//
// A GitHub App.
type SearchNodeApp struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeApp.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeApp) GetTypename() string {
	_ = "STUB: not implemented"

	// SearchNodeDefaultBranchRef includes the requested fields of the GraphQL type Ref.
	// The GraphQL type's documentation follows.
	//
	// Represents a Git reference.
	return ""
}

type SearchNodeDefaultBranchRef struct {
	// The ref name.
	Name string `json:"name"`
}

// GetName returns SearchNodeDefaultBranchRef.Name, and is useful for accessing the field via an interface.
func (v *SearchNodeDefaultBranchRef) GetName() string {
	_ = "STUB: not implemented"

	// SearchNodeDiscussion includes the requested fields of the GraphQL type Discussion.
	// The GraphQL type's documentation follows.
	//
	// A discussion in a repository.
	return ""
}

type SearchNodeDiscussion struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeDiscussion.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeDiscussion) GetTypename() string {
	_ = "STUB: not implemented"

	// SearchNodeIssue includes the requested fields of the GraphQL type Issue.
	// The GraphQL type's documentation follows.
	//
	// An Issue is a place to discuss ideas, enhancements, tasks, and bugs for a project.
	return ""
}

type SearchNodeIssue struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeIssue.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeIssue) GetTypename() string {
	_ = "STUB: not implemented"

	// SearchNodeMarketplaceListing includes the requested fields of the GraphQL type MarketplaceListing.
	// The GraphQL type's documentation follows.
	//
	// A listing in the GitHub integration marketplace.
	return ""
}

type SearchNodeMarketplaceListing struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeMarketplaceListing.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeMarketplaceListing) GetTypename() string {
	_ = "STUB: not implemented"

	// SearchNodeOrganization includes the requested fields of the GraphQL type Organization.
	// The GraphQL type's documentation follows.
	//
	// An account on GitHub, with one or more owners, that has repositories, members and teams.
	return ""
}

type SearchNodeOrganization struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeOrganization.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeOrganization) GetTypename() string {
	_ = "STUB: not implemented"

	// SearchNodePullRequest includes the requested fields of the GraphQL type PullRequest.
	// The GraphQL type's documentation follows.
	//
	// A repository pull request.
	return ""
}

type SearchNodePullRequest struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodePullRequest.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodePullRequest) GetTypename() string {
	_ = "STUB: not implemented"

	// SearchNodeRepository includes the requested fields of the GraphQL type Repository.
	// The GraphQL type's documentation follows.
	//
	// A repository contains the content for a project.
	return ""
}

type SearchNodeRepository struct {
	Typename string `json:"__typename"`
	// The Node ID of the Repository object
	Id string `json:"id"`
	// The name of the repository.
	Name string `json:"name"`
	// The Ref associated with the repository's default branch.
	DefaultBranchRef SearchNodeDefaultBranchRef `json:"defaultBranchRef"`
	// The HTTP URL for this repository
	Url string `json:"url"`
}

// GetTypename returns SearchNodeRepository.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeRepository) GetTypename() string {
	_ = "STUB: not implemented"

	// GetId returns SearchNodeRepository.Id, and is useful for accessing the field via an interface.
	return ""
}

func (v *SearchNodeRepository) GetId() string {
	_ = "STUB: not implemented"

	// GetName returns SearchNodeRepository.Name, and is useful for accessing the field via an interface.
	return ""
}

func (v *SearchNodeRepository) GetName() string {
	_ = "STUB: not implemented"

	// GetDefaultBranchRef returns SearchNodeRepository.DefaultBranchRef, and is useful for accessing the field via an interface.
	return ""
}

func (v *SearchNodeRepository) GetDefaultBranchRef() SearchNodeDefaultBranchRef {
	_ = "STUB: not implemented"
	return *new(SearchNodeDefaultBranchRef)
}

// GetUrl returns SearchNodeRepository.Url, and is useful for accessing the field via an interface.
func (v *SearchNodeRepository) GetUrl() string {
	_ = "STUB: not implemented"

	// SearchNodeUser includes the requested fields of the GraphQL type User.
	// The GraphQL type's documentation follows.
	//
	// A user is an individual's account on GitHub that owns repositories and can make new content.
	return ""
}

type SearchNodeUser struct {
	Typename string `json:"__typename"`
}

// GetTypename returns SearchNodeUser.Typename, and is useful for accessing the field via an interface.
func (v *SearchNodeUser) GetTypename() string {
	_ = "STUB: not implemented"

	// __checkLoginInput is used internally by genqlient
	return ""
}

type __checkLoginInput struct {
	Login string `json:"login"`
}

// GetLogin returns __checkLoginInput.Login, and is useful for accessing the field via an interface.
func (v *__checkLoginInput) GetLogin() string {
	_ = "STUB: not implemented"

	// __getBranchDataInput is used internally by genqlient
	return ""
}

type __getBranchDataInput struct {
	Name         string  `json:"name"`
	Owner        string  `json:"owner"`
	BranchFirst  int     `json:"branchFirst"`
	TargetBranch string  `json:"targetBranch"`
	BranchCursor *string `json:"branchCursor"`
}

// GetName returns __getBranchDataInput.Name, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetName() string {
	_ = "STUB: not implemented"

	// GetOwner returns __getBranchDataInput.Owner, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getBranchDataInput) GetOwner() string {
	_ = "STUB: not implemented"

	// GetBranchFirst returns __getBranchDataInput.BranchFirst, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getBranchDataInput) GetBranchFirst() int { _ = "STUB: not implemented"; return 0 }

// GetTargetBranch returns __getBranchDataInput.TargetBranch, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetTargetBranch() string { _ = "STUB: not implemented"; return "" }

// GetBranchCursor returns __getBranchDataInput.BranchCursor, and is useful for accessing the field via an interface.
func (v *__getBranchDataInput) GetBranchCursor() *string { _ = "STUB: not implemented"; return nil }

// __getCommitDataInput is used internally by genqlient
type __getCommitDataInput struct {
	Name         string  `json:"name"`
	Owner        string  `json:"owner"`
	BranchFirst  int     `json:"branchFirst"`
	CommitFirst  int     `json:"commitFirst"`
	CommitCursor *string `json:"commitCursor"`
	BranchName   string  `json:"branchName"`
}

// GetName returns __getCommitDataInput.Name, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetName() string {
	_ = "STUB: not implemented"

	// GetOwner returns __getCommitDataInput.Owner, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getCommitDataInput) GetOwner() string {
	_ = "STUB: not implemented"

	// GetBranchFirst returns __getCommitDataInput.BranchFirst, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getCommitDataInput) GetBranchFirst() int { _ = "STUB: not implemented"; return 0 }

// GetCommitFirst returns __getCommitDataInput.CommitFirst, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetCommitFirst() int { _ = "STUB: not implemented"; return 0 }

// GetCommitCursor returns __getCommitDataInput.CommitCursor, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetCommitCursor() *string { _ = "STUB: not implemented"; return nil }

// GetBranchName returns __getCommitDataInput.BranchName, and is useful for accessing the field via an interface.
func (v *__getCommitDataInput) GetBranchName() string {
	_ = "STUB: not implemented"

	// __getMergedPullRequestDataInput is used internally by genqlient
	return ""
}

type __getMergedPullRequestDataInput struct {
	Name     string  `json:"name"`
	Owner    string  `json:"owner"`
	PrLast   int     `json:"prLast"`
	PrCursor *string `json:"prCursor"`
}

// GetName returns __getMergedPullRequestDataInput.Name, and is useful for accessing the field via an interface.
func (v *__getMergedPullRequestDataInput) GetName() string {
	_ = "STUB: not implemented"

	// GetOwner returns __getMergedPullRequestDataInput.Owner, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getMergedPullRequestDataInput) GetOwner() string {
	_ = "STUB: not implemented"

	// GetPrLast returns __getMergedPullRequestDataInput.PrLast, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getMergedPullRequestDataInput) GetPrLast() int {
	_ = "STUB: not implemented"

	// GetPrCursor returns __getMergedPullRequestDataInput.PrCursor, and is useful for accessing the field via an interface.
	return 0
}

func (v *__getMergedPullRequestDataInput) GetPrCursor() *string {
	_ = "STUB: not implemented"

	// __getPullRequestDataInput is used internally by genqlient
	return nil
}

type __getPullRequestDataInput struct {
	Name     string  `json:"name"`
	Owner    string  `json:"owner"`
	PrFirst  int     `json:"prFirst"`
	PrCursor *string `json:"prCursor"`
}

// GetName returns __getPullRequestDataInput.Name, and is useful for accessing the field via an interface.
func (v *__getPullRequestDataInput) GetName() string {
	_ = "STUB: not implemented"

	// GetOwner returns __getPullRequestDataInput.Owner, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getPullRequestDataInput) GetOwner() string {
	_ = "STUB: not implemented"

	// GetPrFirst returns __getPullRequestDataInput.PrFirst, and is useful for accessing the field via an interface.
	return ""
}

func (v *__getPullRequestDataInput) GetPrFirst() int {
	_ = "STUB: not implemented"

	// GetPrCursor returns __getPullRequestDataInput.PrCursor, and is useful for accessing the field via an interface.
	return 0
}

func (v *__getPullRequestDataInput) GetPrCursor() *string {
	_ = "STUB: not implemented"

	// __getRepoDataBySearchInput is used internally by genqlient
	return nil
}

type __getRepoDataBySearchInput struct {
	SearchQuery string  `json:"searchQuery"`
	RepoCursor  *string `json:"repoCursor"`
}

// GetSearchQuery returns __getRepoDataBySearchInput.SearchQuery, and is useful for accessing the field via an interface.
func (v *__getRepoDataBySearchInput) GetSearchQuery() string { _ = "STUB: not implemented"; return "" }

// GetRepoCursor returns __getRepoDataBySearchInput.RepoCursor, and is useful for accessing the field via an interface.
func (v *__getRepoDataBySearchInput) GetRepoCursor() *string {
	_ = "STUB: not implemented"

	// checkLoginOrganization includes the requested fields of the GraphQL type Organization.
	// The GraphQL type's documentation follows.
	//
	// An account on GitHub, with one or more owners, that has repositories, members and teams.
	return nil
}

type checkLoginOrganization struct {
	// The organization's login name.
	Login string `json:"login"`
}

// GetLogin returns checkLoginOrganization.Login, and is useful for accessing the field via an interface.
func (v *checkLoginOrganization) GetLogin() string {
	_ = "STUB: not implemented"

	// checkLoginResponse is returned by checkLogin on success.
	return ""
}

type checkLoginResponse struct {
	// Lookup a user by login.
	User checkLoginUser `json:"user"`
	// Lookup a organization by login.
	Organization checkLoginOrganization `json:"organization"`
}

// GetUser returns checkLoginResponse.User, and is useful for accessing the field via an interface.
func (v *checkLoginResponse) GetUser() checkLoginUser {
	_ = "STUB: not implemented"

	// GetOrganization returns checkLoginResponse.Organization, and is useful for accessing the field via an interface.
	return *new(checkLoginUser)
}

func (v *checkLoginResponse) GetOrganization() checkLoginOrganization {
	_ = "STUB: not implemented"
	return *

	// checkLoginUser includes the requested fields of the GraphQL type User.
	// The GraphQL type's documentation follows.
	//
	// A user is an individual's account on GitHub that owns repositories and can make new content.
	new(checkLoginOrganization)
}

type checkLoginUser struct {
	// The username used to login.
	Login string `json:"login"`
}

// GetLogin returns checkLoginUser.Login, and is useful for accessing the field via an interface.
func (v *checkLoginUser) GetLogin() string {
	_ = "STUB: not implemented"

	// getBranchDataRepository includes the requested fields of the GraphQL type Repository.
	// The GraphQL type's documentation follows.
	//
	// A repository contains the content for a project.
	return ""
}

type getBranchDataRepository struct {
	// Fetch a list of refs from the repository
	Refs getBranchDataRepositoryRefsRefConnection `json:"refs"`
}

// GetRefs returns getBranchDataRepository.Refs, and is useful for accessing the field via an interface.
func (v *getBranchDataRepository) GetRefs() getBranchDataRepositoryRefsRefConnection {
	_ = "STUB: not implemented"

	// getBranchDataRepositoryRefsRefConnection includes the requested fields of the GraphQL type RefConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for Ref.
	return *new(getBranchDataRepositoryRefsRefConnection)
}

type getBranchDataRepositoryRefsRefConnection struct {
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
	// A list of nodes.
	Nodes []BranchNode `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getBranchDataRepositoryRefsRefConnectionPageInfo `json:"pageInfo"`
}

// GetTotalCount returns getBranchDataRepositoryRefsRefConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *getBranchDataRepositoryRefsRefConnection) GetTotalCount() int {
	_ = "STUB: not implemented"
	return 0

	// GetNodes returns getBranchDataRepositoryRefsRefConnection.Nodes, and is useful for accessing the field via an interface.
}

func (v *getBranchDataRepositoryRefsRefConnection) GetNodes() []BranchNode {
	_ = "STUB: not implemented"

	// GetPageInfo returns getBranchDataRepositoryRefsRefConnection.PageInfo, and is useful for accessing the field via an interface.
	return nil
}

func (v *getBranchDataRepositoryRefsRefConnection) GetPageInfo() getBranchDataRepositoryRefsRefConnectionPageInfo {
	_ = "STUB: not implemented"

	// getBranchDataRepositoryRefsRefConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
	// The GraphQL type's documentation follows.
	//
	// Information about pagination in a connection.
	return *new(getBranchDataRepositoryRefsRefConnectionPageInfo)
}

type getBranchDataRepositoryRefsRefConnectionPageInfo struct {
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
}

// GetEndCursor returns getBranchDataRepositoryRefsRefConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *getBranchDataRepositoryRefsRefConnectionPageInfo) GetEndCursor() string {
	_ = "STUB: not implemented"

	// GetHasNextPage returns getBranchDataRepositoryRefsRefConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
	return ""
}

func (v *getBranchDataRepositoryRefsRefConnectionPageInfo) GetHasNextPage() bool {
	_ = "STUB: not implemented"
	return false

	// getBranchDataResponse is returned by getBranchData on success.
}

type getBranchDataResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getBranchDataRepository `json:"repository"`
}

// GetRepository returns getBranchDataResponse.Repository, and is useful for accessing the field via an interface.
func (v *getBranchDataResponse) GetRepository() getBranchDataRepository {
	_ = "STUB: not implemented"
	return *

	// getCommitDataRepository includes the requested fields of the GraphQL type Repository.
	// The GraphQL type's documentation follows.
	//
	// A repository contains the content for a project.
	new(getBranchDataRepository)
}

type getCommitDataRepository struct {
	// Fetch a list of refs from the repository
	Refs getCommitDataRepositoryRefsRefConnection `json:"refs"`
}

// GetRefs returns getCommitDataRepository.Refs, and is useful for accessing the field via an interface.
func (v *getCommitDataRepository) GetRefs() getCommitDataRepositoryRefsRefConnection {
	_ = "STUB: not implemented"

	// getCommitDataRepositoryRefsRefConnection includes the requested fields of the GraphQL type RefConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for Ref.
	return *new(getCommitDataRepositoryRefsRefConnection)
}

type getCommitDataRepositoryRefsRefConnection struct {
	// A list of nodes.
	Nodes []BranchHistory `json:"nodes"`
}

// GetNodes returns getCommitDataRepositoryRefsRefConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getCommitDataRepositoryRefsRefConnection) GetNodes() []BranchHistory {
	_ = "STUB: not implemented"

	// getCommitDataResponse is returned by getCommitData on success.
	return nil
}

type getCommitDataResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getCommitDataRepository `json:"repository"`
}

// GetRepository returns getCommitDataResponse.Repository, and is useful for accessing the field via an interface.
func (v *getCommitDataResponse) GetRepository() getCommitDataRepository {
	_ = "STUB: not implemented"
	return *

	// getMergedPullRequestDataRepository includes the requested fields of the GraphQL type Repository.
	// The GraphQL type's documentation follows.
	//
	// A repository contains the content for a project.
	new(getCommitDataRepository)
}

type getMergedPullRequestDataRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns getMergedPullRequestDataRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getMergedPullRequestDataRepository) GetPullRequests() getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection {
	_ = "STUB: not implemented"
	return *

	// getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for PullRequest.
	new(getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection)
}

type getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection struct {
	// A list of nodes.
	Nodes []MergedPullRequestNode `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection) GetNodes() []MergedPullRequestNode {
	_ = "STUB: not implemented"

	// GetPageInfo returns getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection.PageInfo, and is useful for accessing the field via an interface.
	return nil
}

func (v *getMergedPullRequestDataRepositoryPullRequestsPullRequestConnection) GetPageInfo() getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo {
	_ = "STUB: not implemented"

	// getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
	// The GraphQL type's documentation follows.
	//
	// Information about pagination in a connection.
	return *new(getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo)
}

type getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo struct {
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue.
	StartCursor string `json:"startCursor"`
}

// GetHasPreviousPage returns getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo.HasPreviousPage, and is useful for accessing the field via an interface.
func (v *getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo) GetHasPreviousPage() bool {
	_ = "STUB: not implemented"
	return false

	// GetStartCursor returns getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo.StartCursor, and is useful for accessing the field via an interface.
}

func (v *getMergedPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo) GetStartCursor() string {
	_ = "STUB: not implemented"
	return ""

	// getMergedPullRequestDataResponse is returned by getMergedPullRequestData on success.
}

type getMergedPullRequestDataResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getMergedPullRequestDataRepository `json:"repository"`
}

// GetRepository returns getMergedPullRequestDataResponse.Repository, and is useful for accessing the field via an interface.
func (v *getMergedPullRequestDataResponse) GetRepository() getMergedPullRequestDataRepository {
	_ = "STUB: not implemented"
	return *

	// getPullRequestDataRepository includes the requested fields of the GraphQL type Repository.
	// The GraphQL type's documentation follows.
	//
	// A repository contains the content for a project.
	new(getMergedPullRequestDataRepository)
}

type getPullRequestDataRepository struct {
	// A list of pull requests that have been opened in the repository.
	PullRequests getPullRequestDataRepositoryPullRequestsPullRequestConnection `json:"pullRequests"`
}

// GetPullRequests returns getPullRequestDataRepository.PullRequests, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepository) GetPullRequests() getPullRequestDataRepositoryPullRequestsPullRequestConnection {
	_ = "STUB: not implemented"
	return *

	// getPullRequestDataRepositoryPullRequestsPullRequestConnection includes the requested fields of the GraphQL type PullRequestConnection.
	// The GraphQL type's documentation follows.
	//
	// The connection type for PullRequest.
	new(getPullRequestDataRepositoryPullRequestsPullRequestConnection)
}

type getPullRequestDataRepositoryPullRequestsPullRequestConnection struct {
	// A list of nodes.
	Nodes []PullRequestNode `json:"nodes"`
	// Information to aid in pagination.
	PageInfo getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns getPullRequestDataRepositoryPullRequestsPullRequestConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnection) GetNodes() []PullRequestNode {
	_ = "STUB: not implemented"

	// GetPageInfo returns getPullRequestDataRepositoryPullRequestsPullRequestConnection.PageInfo, and is useful for accessing the field via an interface.
	return nil
}

func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnection) GetPageInfo() getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo {
	_ = "STUB: not implemented"

	// getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
	// The GraphQL type's documentation follows.
	//
	// Information about pagination in a connection.
	return *new(getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo)
}

type getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo) GetHasNextPage() bool {
	_ = "STUB: not implemented"
	return false

	// GetEndCursor returns getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
}

func (v *getPullRequestDataRepositoryPullRequestsPullRequestConnectionPageInfo) GetEndCursor() string {
	_ = "STUB: not implemented"
	return ""

	// getPullRequestDataResponse is returned by getPullRequestData on success.
}

type getPullRequestDataResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestDataRepository `json:"repository"`
}

// GetRepository returns getPullRequestDataResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestDataResponse) GetRepository() getPullRequestDataRepository {
	_ = "STUB: not implemented"
	return *

	// getRepoDataBySearchResponse is returned by getRepoDataBySearch on success.
	new(getPullRequestDataRepository)
}

type getRepoDataBySearchResponse struct {
	// Perform a search across resources, returning a maximum of 1,000 results.
	Search getRepoDataBySearchSearchSearchResultItemConnection `json:"search"`
}

// GetSearch returns getRepoDataBySearchResponse.Search, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchResponse) GetSearch() getRepoDataBySearchSearchSearchResultItemConnection {
	_ = "STUB: not implemented"

	// getRepoDataBySearchSearchSearchResultItemConnection includes the requested fields of the GraphQL type SearchResultItemConnection.
	// The GraphQL type's documentation follows.
	//
	// A list of results that matched against a search query. Regardless of the number
	// of matches, a maximum of 1,000 results will be available across all types,
	// potentially split across many pages.
	return *new(getRepoDataBySearchSearchSearchResultItemConnection)
}

type getRepoDataBySearchSearchSearchResultItemConnection struct {
	// The total number of repositories that matched the search query. Regardless of
	// the total number of matches, a maximum of 1,000 results will be available
	// across all types.
	RepositoryCount int `json:"repositoryCount"`
	// A list of nodes.
	Nodes []SearchNode `json:"-"`
	// Information to aid in pagination.
	PageInfo getRepoDataBySearchSearchSearchResultItemConnectionPageInfo `json:"pageInfo"`
}

// GetRepositoryCount returns getRepoDataBySearchSearchSearchResultItemConnection.RepositoryCount, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnection) GetRepositoryCount() int {
	_ = "STUB: not implemented"
	return 0

	// GetNodes returns getRepoDataBySearchSearchSearchResultItemConnection.Nodes, and is useful for accessing the field via an interface.
}

func (v *getRepoDataBySearchSearchSearchResultItemConnection) GetNodes() []SearchNode {
	_ = "STUB: not implemented"

	// GetPageInfo returns getRepoDataBySearchSearchSearchResultItemConnection.PageInfo, and is useful for accessing the field via an interface.
	return nil
}

func (v *getRepoDataBySearchSearchSearchResultItemConnection) GetPageInfo() getRepoDataBySearchSearchSearchResultItemConnectionPageInfo {
	_ = "STUB: not implemented"
	return *new(getRepoDataBySearchSearchSearchResultItemConnectionPageInfo)
}

func (v *getRepoDataBySearchSearchSearchResultItemConnection) UnmarshalJSON(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

type __premarshalgetRepoDataBySearchSearchSearchResultItemConnection struct {
	RepositoryCount int `json:"repositoryCount"`

	Nodes []json.RawMessage `json:"nodes"`

	PageInfo getRepoDataBySearchSearchSearchResultItemConnectionPageInfo `json:"pageInfo"`
}

func (v *getRepoDataBySearchSearchSearchResultItemConnection) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (v *getRepoDataBySearchSearchSearchResultItemConnection) __premarshalJSON() (*__premarshalgetRepoDataBySearchSearchSearchResultItemConnection, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// getRepoDataBySearchSearchSearchResultItemConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Information about pagination in a connection.
type getRepoDataBySearchSearchSearchResultItemConnectionPageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating forwards, the cursor to continue.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns getRepoDataBySearchSearchSearchResultItemConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *getRepoDataBySearchSearchSearchResultItemConnectionPageInfo) GetHasNextPage() bool {
	_ = "STUB: not implemented"
	return false

	// GetEndCursor returns getRepoDataBySearchSearchSearchResultItemConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
}

func (v *getRepoDataBySearchSearchSearchResultItemConnectionPageInfo) GetEndCursor() string {
	_ = "STUB: not implemented"
	return ""

	// The query executed by checkLogin.
}

const checkLogin_Operation = `
query checkLogin ($login: String!) {
	user(login: $login) {
		login
	}
	organization(login: $login) {
		login
	}
}
`

func checkLogin(
	ctx_ context.Context,
	client_ graphql.Client,
	login string,
) (data_ *checkLoginResponse, err_ error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// The query executed by getBranchData.
const getBranchData_Operation = `
query getBranchData ($name: String!, $owner: String!, $branchFirst: Int!, $targetBranch: String!, $branchCursor: String) {
	repository(name: $name, owner: $owner) {
		refs(refPrefix: "refs/heads/", first: $branchFirst, after: $branchCursor) {
			totalCount
			nodes {
				name
				compare(headRef: $targetBranch) {
					aheadBy
					behindBy
				}
				repository {
					name
					defaultBranchRef {
						name
					}
				}
			}
			pageInfo {
				endCursor
				hasNextPage
			}
		}
	}
}
`

func getBranchData(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	owner string,
	branchFirst int,
	targetBranch string,
	branchCursor *string,
) (data_ *getBranchDataResponse, err_ error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// The query executed by getCommitData.
const getCommitData_Operation = `
query getCommitData ($name: String!, $owner: String!, $branchFirst: Int!, $commitFirst: Int!, $commitCursor: String, $branchName: String!) {
	repository(name: $name, owner: $owner) {
		refs(refPrefix: "refs/heads/", first: $branchFirst, query: $branchName) {
			nodes {
				target {
					__typename
					... on Commit {
						id
						history(first: $commitFirst, after: $commitCursor) {
							nodes {
								committedDate
								additions
								deletions
							}
							pageInfo {
								endCursor
								hasNextPage
							}
						}
					}
				}
			}
		}
	}
}
`

func getCommitData(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	owner string,
	branchFirst int,
	commitFirst int,
	commitCursor *string,
	branchName string,
) (data_ *getCommitDataResponse, err_ error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// The query executed by getMergedPullRequestData.
const getMergedPullRequestData_Operation = `
query getMergedPullRequestData ($name: String!, $owner: String!, $prLast: Int!, $prCursor: String) {
	repository(name: $name, owner: $owner) {
		pullRequests(last: $prLast, before: $prCursor, states: [MERGED]) {
			nodes {
				... on PullRequest {
					createdAt
					merged
					mergedAt
					mergeCommit {
						deployments(last: 1, orderBy: {field:CREATED_AT,direction:ASC}) {
							nodes {
								createdAt
							}
							totalCount
						}
					}
				}
				headRefName
				reviews(states: APPROVED, last: 1) {
					totalCount
					nodes {
						... on PullRequestReview {
							createdAt
						}
					}
				}
			}
			pageInfo {
				hasPreviousPage
				startCursor
			}
		}
	}
}
`

func getMergedPullRequestData(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	owner string,
	prLast int,
	prCursor *string,
) (data_ *getMergedPullRequestDataResponse, err_ error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// The query executed by getPullRequestData.
const getPullRequestData_Operation = `
query getPullRequestData ($name: String!, $owner: String!, $prFirst: Int!, $prCursor: String) {
	repository(name: $name, owner: $owner) {
		pullRequests(first: $prFirst, after: $prCursor, states: [OPEN]) {
			nodes {
				... on PullRequest {
					createdAt
					merged
					mergedAt
					mergeCommit {
						deployments(last: 1, orderBy: {field:CREATED_AT,direction:ASC}) {
							nodes {
								createdAt
							}
							totalCount
						}
					}
				}
				headRefName
				reviews(states: APPROVED, last: 1) {
					totalCount
					nodes {
						... on PullRequestReview {
							createdAt
						}
					}
				}
			}
			pageInfo {
				hasNextPage
				endCursor
			}
		}
	}
}
`

func getPullRequestData(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	owner string,
	prFirst int,
	prCursor *string,
) (data_ *getPullRequestDataResponse, err_ error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// The query executed by getRepoDataBySearch.
const getRepoDataBySearch_Operation = `
query getRepoDataBySearch ($searchQuery: String!, $repoCursor: String) {
	search(query: $searchQuery, type: REPOSITORY, first: 100, after: $repoCursor) {
		repositoryCount
		nodes {
			__typename
			... on Repository {
				id
				name
				defaultBranchRef {
					name
				}
				url
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func getRepoDataBySearch(
	ctx_ context.Context,
	client_ graphql.Client,
	searchQuery string,
	repoCursor *string,
) (data_ *getRepoDataBySearchResponse, err_ error) {
	_ = "STUB: not implemented"
	return nil, nil
}
