// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	_ = "STUB: not implemented"
	return *new(metric.Meter)
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	_ = "STUB: not implemented"
	return *new(trace.Tracer)
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                      metric.Meter
	mu                         sync.Mutex
	registrations              []metric.Registration
	GrafanacloudDatapointCount metric.Int64Counter
	GrafanacloudFlushCount     metric.Int64Counter
	GrafanacloudHostCount      metric.Int64ObservableGauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	_ = "STUB: not implemented"

	// RegisterGrafanacloudHostCountCallback sets callback for observable GrafanacloudHostCount metric.
	return
}

func (builder *TelemetryBuilder) RegisterGrafanacloudHostCountCallback(cb metric.Int64Callback) error {
	_ = "STUB: not implemented"
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	_ = "STUB: not implemented"
	return
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() { _ = "STUB: not implemented"; return }

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
