// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeVcsChangeState specifies the value vcs.change.state attribute.
type AttributeVcsChangeState int

const (
	_ AttributeVcsChangeState = iota
	AttributeVcsChangeStateOpen
	AttributeVcsChangeStateMerged
)

// String returns the string representation of the AttributeVcsChangeState.
func (av AttributeVcsChangeState) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeVcsChangeState is a helper map of string to AttributeVcsChangeState attribute value.
var MapAttributeVcsChangeState = map[string]AttributeVcsChangeState{
	"open":   AttributeVcsChangeStateOpen,
	"merged": AttributeVcsChangeStateMerged,
}

// AttributeVcsLineChangeType specifies the value vcs.line_change.type attribute.
type AttributeVcsLineChangeType int

const (
	_ AttributeVcsLineChangeType = iota
	AttributeVcsLineChangeTypeAdded
	AttributeVcsLineChangeTypeRemoved
)

// String returns the string representation of the AttributeVcsLineChangeType.
func (av AttributeVcsLineChangeType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeVcsLineChangeType is a helper map of string to AttributeVcsLineChangeType attribute value.
var MapAttributeVcsLineChangeType = map[string]AttributeVcsLineChangeType{
	"added":   AttributeVcsLineChangeTypeAdded,
	"removed": AttributeVcsLineChangeTypeRemoved,
}

// AttributeVcsRefBaseType specifies the value vcs.ref.base.type attribute.
type AttributeVcsRefBaseType int

const (
	_ AttributeVcsRefBaseType = iota
	AttributeVcsRefBaseTypeBranch
	AttributeVcsRefBaseTypeTag
)

// String returns the string representation of the AttributeVcsRefBaseType.
func (av AttributeVcsRefBaseType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeVcsRefBaseType is a helper map of string to AttributeVcsRefBaseType attribute value.
var MapAttributeVcsRefBaseType = map[string]AttributeVcsRefBaseType{
	"branch": AttributeVcsRefBaseTypeBranch,
	"tag":    AttributeVcsRefBaseTypeTag,
}

// AttributeVcsRefHeadType specifies the value vcs.ref.head.type attribute.
type AttributeVcsRefHeadType int

const (
	_ AttributeVcsRefHeadType = iota
	AttributeVcsRefHeadTypeBranch
	AttributeVcsRefHeadTypeTag
)

// String returns the string representation of the AttributeVcsRefHeadType.
func (av AttributeVcsRefHeadType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeVcsRefHeadType is a helper map of string to AttributeVcsRefHeadType attribute value.
var MapAttributeVcsRefHeadType = map[string]AttributeVcsRefHeadType{
	"branch": AttributeVcsRefHeadTypeBranch,
	"tag":    AttributeVcsRefHeadTypeTag,
}

// AttributeVcsRefType specifies the value vcs.ref.type attribute.
type AttributeVcsRefType int

const (
	_ AttributeVcsRefType = iota
	AttributeVcsRefTypeBranch
	AttributeVcsRefTypeTag
)

// String returns the string representation of the AttributeVcsRefType.
func (av AttributeVcsRefType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeVcsRefType is a helper map of string to AttributeVcsRefType attribute value.
var MapAttributeVcsRefType = map[string]AttributeVcsRefType{
	"branch": AttributeVcsRefTypeBranch,
	"tag":    AttributeVcsRefTypeTag,
}

// AttributeVcsRevisionDeltaDirection specifies the value vcs.revision_delta.direction attribute.
type AttributeVcsRevisionDeltaDirection int

const (
	_ AttributeVcsRevisionDeltaDirection = iota
	AttributeVcsRevisionDeltaDirectionAhead
	AttributeVcsRevisionDeltaDirectionBehind
)

// String returns the string representation of the AttributeVcsRevisionDeltaDirection.
func (av AttributeVcsRevisionDeltaDirection) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeVcsRevisionDeltaDirection is a helper map of string to AttributeVcsRevisionDeltaDirection attribute value.
var MapAttributeVcsRevisionDeltaDirection = map[string]AttributeVcsRevisionDeltaDirection{
	"ahead":  AttributeVcsRevisionDeltaDirectionAhead,
	"behind": AttributeVcsRevisionDeltaDirectionBehind,
}

var MetricsInfo = metricsInfo{
	VcsChangeCount: metricInfo{
		Name: "vcs.change.count",
	},
	VcsChangeDuration: metricInfo{
		Name: "vcs.change.duration",
	},
	VcsChangeTimeToApproval: metricInfo{
		Name: "vcs.change.time_to_approval",
	},
	VcsChangeTimeToMerge: metricInfo{
		Name: "vcs.change.time_to_merge",
	},
	VcsContributorCount: metricInfo{
		Name: "vcs.contributor.count",
	},
	VcsRefCount: metricInfo{
		Name: "vcs.ref.count",
	},
	VcsRefLinesDelta: metricInfo{
		Name: "vcs.ref.lines_delta",
	},
	VcsRefRevisionsDelta: metricInfo{
		Name: "vcs.ref.revisions_delta",
	},
	VcsRefTime: metricInfo{
		Name: "vcs.ref.time",
	},
	VcsRepositoryCount: metricInfo{
		Name: "vcs.repository.count",
	},
}

type metricsInfo struct {
	VcsChangeCount          metricInfo
	VcsChangeDuration       metricInfo
	VcsChangeTimeToApproval metricInfo
	VcsChangeTimeToMerge    metricInfo
	VcsContributorCount     metricInfo
	VcsRefCount             metricInfo
	VcsRefLinesDelta        metricInfo
	VcsRefRevisionsDelta    metricInfo
	VcsRefTime              metricInfo
	VcsRepositoryCount      metricInfo
}

type metricInfo struct {
	Name string
}

type metricVcsChangeCount struct {
	data          pmetric.Metric             // data buffer for generated metric.
	config        VcsChangeCountMetricConfig // metric config provided by user.
	capacity      int                        // max observed number of data points added to the metric.
	aggDataPoints []int64                    // slice containing number of aggregated datapoints at each index
}

// init fills vcs.change.count metric with initial data.
func (m *metricVcsChangeCount) init() {
	m.data.SetName("vcs.change.count")
	m.data.SetDescription("The number of changes (pull requests) in a repository, categorized by their state (either open or merged).")
	m.data.SetUnit("{change}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsChangeCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsChangeStateAttributeValue string, vcsRepositoryNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsChangeCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsChangeCount) emit(metrics pmetric.MetricSlice) { _ = "STUB: not implemented"; return }

func newMetricVcsChangeCount(cfg VcsChangeCountMetricConfig) metricVcsChangeCount {
	_ = "STUB: not implemented"
	return *new(metricVcsChangeCount)
}

type metricVcsChangeDuration struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        VcsChangeDurationMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills vcs.change.duration metric with initial data.
func (m *metricVcsChangeDuration) init() {
	m.data.SetName("vcs.change.duration")
	m.data.SetDescription("The time duration a change (pull request/merge request/changelist) has been in an open state.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsChangeDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsChangeStateAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsChangeDuration) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsChangeDuration) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricVcsChangeDuration(cfg VcsChangeDurationMetricConfig) metricVcsChangeDuration {
	_ = "STUB: not implemented"
	return *new(metricVcsChangeDuration)
}

type metricVcsChangeTimeToApproval struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        VcsChangeTimeToApprovalMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills vcs.change.time_to_approval metric with initial data.
func (m *metricVcsChangeTimeToApproval) init() {
	m.data.SetName("vcs.change.time_to_approval")
	m.data.SetDescription("The amount of time it took a change (pull request) to go from open to approved.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsChangeTimeToApproval) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsChangeTimeToApproval) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsChangeTimeToApproval) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricVcsChangeTimeToApproval(cfg VcsChangeTimeToApprovalMetricConfig) metricVcsChangeTimeToApproval {
	_ = "STUB: not implemented"
	return *new(metricVcsChangeTimeToApproval)
}

type metricVcsChangeTimeToMerge struct {
	data          pmetric.Metric                   // data buffer for generated metric.
	config        VcsChangeTimeToMergeMetricConfig // metric config provided by user.
	capacity      int                              // max observed number of data points added to the metric.
	aggDataPoints []int64                          // slice containing number of aggregated datapoints at each index
}

// init fills vcs.change.time_to_merge metric with initial data.
func (m *metricVcsChangeTimeToMerge) init() {
	m.data.SetName("vcs.change.time_to_merge")
	m.data.SetDescription("The amount of time it took a change (pull request) to go from open to merged.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsChangeTimeToMerge) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsChangeTimeToMerge) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsChangeTimeToMerge) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricVcsChangeTimeToMerge(cfg VcsChangeTimeToMergeMetricConfig) metricVcsChangeTimeToMerge {
	_ = "STUB: not implemented"
	return *new(metricVcsChangeTimeToMerge)
}

type metricVcsContributorCount struct {
	data          pmetric.Metric                  // data buffer for generated metric.
	config        VcsContributorCountMetricConfig // metric config provided by user.
	capacity      int                             // max observed number of data points added to the metric.
	aggDataPoints []int64                         // slice containing number of aggregated datapoints at each index
}

// init fills vcs.contributor.count metric with initial data.
func (m *metricVcsContributorCount) init() {
	m.data.SetName("vcs.contributor.count")
	m.data.SetDescription("The number of unique contributors to a repository.")
	m.data.SetUnit("{contributor}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsContributorCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsContributorCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsContributorCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricVcsContributorCount(cfg VcsContributorCountMetricConfig) metricVcsContributorCount {
	_ = "STUB: not implemented"
	return *new(metricVcsContributorCount)
}

type metricVcsRefCount struct {
	data          pmetric.Metric          // data buffer for generated metric.
	config        VcsRefCountMetricConfig // metric config provided by user.
	capacity      int                     // max observed number of data points added to the metric.
	aggDataPoints []int64                 // slice containing number of aggregated datapoints at each index
}

// init fills vcs.ref.count metric with initial data.
func (m *metricVcsRefCount) init() {
	m.data.SetName("vcs.ref.count")
	m.data.SetDescription("The number of refs of type branch in a repository.")
	m.data.SetUnit("{ref}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsRefCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsRefCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsRefCount) emit(metrics pmetric.MetricSlice) { _ = "STUB: not implemented"; return }

func newMetricVcsRefCount(cfg VcsRefCountMetricConfig) metricVcsRefCount {
	_ = "STUB: not implemented"
	return *new(metricVcsRefCount)
}

type metricVcsRefLinesDelta struct {
	data          pmetric.Metric               // data buffer for generated metric.
	config        VcsRefLinesDeltaMetricConfig // metric config provided by user.
	capacity      int                          // max observed number of data points added to the metric.
	aggDataPoints []int64                      // slice containing number of aggregated datapoints at each index
}

// init fills vcs.ref.lines_delta metric with initial data.
func (m *metricVcsRefLinesDelta) init() {
	m.data.SetName("vcs.ref.lines_delta")
	m.data.SetDescription("The number of lines added/removed in a ref (branch) relative to the default branch (trunk).")
	m.data.SetUnit("{line}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsRefLinesDelta) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsRefHeadTypeAttributeValue string, vcsRefBaseNameAttributeValue string, vcsRefBaseTypeAttributeValue string, vcsLineChangeTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsRefLinesDelta) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsRefLinesDelta) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricVcsRefLinesDelta(cfg VcsRefLinesDeltaMetricConfig) metricVcsRefLinesDelta {
	_ = "STUB: not implemented"
	return *new(metricVcsRefLinesDelta)
}

type metricVcsRefRevisionsDelta struct {
	data          pmetric.Metric                   // data buffer for generated metric.
	config        VcsRefRevisionsDeltaMetricConfig // metric config provided by user.
	capacity      int                              // max observed number of data points added to the metric.
	aggDataPoints []int64                          // slice containing number of aggregated datapoints at each index
}

// init fills vcs.ref.revisions_delta metric with initial data.
func (m *metricVcsRefRevisionsDelta) init() {
	m.data.SetName("vcs.ref.revisions_delta")
	m.data.SetDescription("The number of revisions (commits) a ref (branch) is ahead/behind the branch from trunk (default).")
	m.data.SetUnit("{revision}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsRefRevisionsDelta) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsRefHeadTypeAttributeValue string, vcsRefBaseNameAttributeValue string, vcsRefBaseTypeAttributeValue string, vcsRevisionDeltaDirectionAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsRefRevisionsDelta) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsRefRevisionsDelta) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricVcsRefRevisionsDelta(cfg VcsRefRevisionsDeltaMetricConfig) metricVcsRefRevisionsDelta {
	_ = "STUB: not implemented"
	return *new(metricVcsRefRevisionsDelta)
}

type metricVcsRefTime struct {
	data          pmetric.Metric         // data buffer for generated metric.
	config        VcsRefTimeMetricConfig // metric config provided by user.
	capacity      int                    // max observed number of data points added to the metric.
	aggDataPoints []int64                // slice containing number of aggregated datapoints at each index
}

// init fills vcs.ref.time metric with initial data.
func (m *metricVcsRefTime) init() {
	m.data.SetName("vcs.ref.time")
	m.data.SetDescription("Time a ref (branch) created from the default branch (trunk) has existed. The `vcs.ref.type` attribute will always be `branch`.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricVcsRefTime) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsRefHeadTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsRefTime) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsRefTime) emit(metrics pmetric.MetricSlice) { _ = "STUB: not implemented"; return }

func newMetricVcsRefTime(cfg VcsRefTimeMetricConfig) metricVcsRefTime {
	_ = "STUB: not implemented"
	return *new(metricVcsRefTime)
}

type metricVcsRepositoryCount struct {
	data     pmetric.Metric                 // data buffer for generated metric.
	config   VcsRepositoryCountMetricConfig // metric config provided by user.
	capacity int                            // max observed number of data points added to the metric.
}

// init fills vcs.repository.count metric with initial data.
func (m *metricVcsRepositoryCount) init() {
	m.data.SetName("vcs.repository.count")
	m.data.SetDescription("The number of repositories in an organization.")
	m.data.SetUnit("{repository}")
	m.data.SetEmptyGauge()
}

func (m *metricVcsRepositoryCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricVcsRepositoryCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricVcsRepositoryCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricVcsRepositoryCount(cfg VcsRepositoryCountMetricConfig) metricVcsRepositoryCount {
	_ = "STUB: not implemented"
	return *new(metricVcsRepositoryCount)
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricVcsChangeCount           metricVcsChangeCount
	metricVcsChangeDuration        metricVcsChangeDuration
	metricVcsChangeTimeToApproval  metricVcsChangeTimeToApproval
	metricVcsChangeTimeToMerge     metricVcsChangeTimeToMerge
	metricVcsContributorCount      metricVcsContributorCount
	metricVcsRefCount              metricVcsRefCount
	metricVcsRefLinesDelta         metricVcsRefLinesDelta
	metricVcsRefRevisionsDelta     metricVcsRefRevisionsDelta
	metricVcsRefTime               metricVcsRefTime
	metricVcsRepositoryCount       metricVcsRepositoryCount
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	_ = "STUB: not implemented"

	// WithStartTime sets startTime on the metrics builder.
	return
}

func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	_ = "STUB: not implemented"
	return *new(MetricBuilderOption)
}

func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	_ = "STUB: not implemented"
	return nil
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	_ = "STUB: not implemented"
	return nil
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"
	return
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"

	// WithResource sets the provided resource on the emitted ResourceMetrics.
	// It's recommended to use ResourceBuilder to create the resource.
	return
}

func WithResource(res pcommon.Resource) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	_ = "STUB: not implemented"
	return
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	_ = "STUB: not implemented"
	return *new(pmetric.Metrics)
}

// RecordVcsChangeCountDataPoint adds a data point to vcs.change.count metric.
func (mb *MetricsBuilder) RecordVcsChangeCountDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsChangeStateAttributeValue AttributeVcsChangeState, vcsRepositoryNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsChangeDurationDataPoint adds a data point to vcs.change.duration metric.
func (mb *MetricsBuilder) RecordVcsChangeDurationDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsChangeStateAttributeValue AttributeVcsChangeState) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsChangeTimeToApprovalDataPoint adds a data point to vcs.change.time_to_approval metric.
func (mb *MetricsBuilder) RecordVcsChangeTimeToApprovalDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsChangeTimeToMergeDataPoint adds a data point to vcs.change.time_to_merge metric.
func (mb *MetricsBuilder) RecordVcsChangeTimeToMergeDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsContributorCountDataPoint adds a data point to vcs.contributor.count metric.
func (mb *MetricsBuilder) RecordVcsContributorCountDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsRefCountDataPoint adds a data point to vcs.ref.count metric.
func (mb *MetricsBuilder) RecordVcsRefCountDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefTypeAttributeValue AttributeVcsRefType) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsRefLinesDeltaDataPoint adds a data point to vcs.ref.lines_delta metric.
func (mb *MetricsBuilder) RecordVcsRefLinesDeltaDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsRefHeadTypeAttributeValue AttributeVcsRefHeadType, vcsRefBaseNameAttributeValue string, vcsRefBaseTypeAttributeValue AttributeVcsRefBaseType, vcsLineChangeTypeAttributeValue AttributeVcsLineChangeType) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsRefRevisionsDeltaDataPoint adds a data point to vcs.ref.revisions_delta metric.
func (mb *MetricsBuilder) RecordVcsRefRevisionsDeltaDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsRefHeadTypeAttributeValue AttributeVcsRefHeadType, vcsRefBaseNameAttributeValue string, vcsRefBaseTypeAttributeValue AttributeVcsRefBaseType, vcsRevisionDeltaDirectionAttributeValue AttributeVcsRevisionDeltaDirection) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsRefTimeDataPoint adds a data point to vcs.ref.time metric.
func (mb *MetricsBuilder) RecordVcsRefTimeDataPoint(ts pcommon.Timestamp, val int64, vcsRepositoryURLFullAttributeValue string, vcsRepositoryNameAttributeValue string, vcsRefHeadNameAttributeValue string, vcsRefHeadTypeAttributeValue AttributeVcsRefHeadType) {
	_ = "STUB: not implemented"
	return
}

// RecordVcsRepositoryCountDataPoint adds a data point to vcs.repository.count metric.
func (mb *MetricsBuilder) RecordVcsRepositoryCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) { _ = "STUB: not implemented"; return }
