// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/scraper"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeState specifies the value state attribute.
type AttributeState int

const (
	_ AttributeState = iota
	AttributeStateIdle
	AttributeStateInterrupt
	AttributeStateNice
	AttributeStateSoftirq
	AttributeStateSteal
	AttributeStateSystem
	AttributeStateUser
	AttributeStateWait
)

// String returns the string representation of the AttributeState.
func (av AttributeState) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeState is a helper map of string to AttributeState attribute value.
var MapAttributeState = map[string]AttributeState{
	"idle":      AttributeStateIdle,
	"interrupt": AttributeStateInterrupt,
	"nice":      AttributeStateNice,
	"softirq":   AttributeStateSoftirq,
	"steal":     AttributeStateSteal,
	"system":    AttributeStateSystem,
	"user":      AttributeStateUser,
	"wait":      AttributeStateWait,
}

var MetricsInfo = metricsInfo{
	SystemCPUFrequency: metricInfo{
		Name: "system.cpu.frequency",
	},
	SystemCPULogicalCount: metricInfo{
		Name: "system.cpu.logical.count",
	},
	SystemCPUPhysicalCount: metricInfo{
		Name: "system.cpu.physical.count",
	},
	SystemCPUTime: metricInfo{
		Name: "system.cpu.time",
	},
	SystemCPUUtilization: metricInfo{
		Name: "system.cpu.utilization",
	},
}

type metricsInfo struct {
	SystemCPUFrequency     metricInfo
	SystemCPULogicalCount  metricInfo
	SystemCPUPhysicalCount metricInfo
	SystemCPUTime          metricInfo
	SystemCPUUtilization   metricInfo
}

type metricInfo struct {
	Name string
}

type metricSystemCPUFrequency struct {
	data          pmetric.Metric                 // data buffer for generated metric.
	config        SystemCPUFrequencyMetricConfig // metric config provided by user.
	capacity      int                            // max observed number of data points added to the metric.
	aggDataPoints []float64                      // slice containing number of aggregated datapoints at each index
}

// init fills system.cpu.frequency metric with initial data.
func (m *metricSystemCPUFrequency) init() {
	m.data.SetName("system.cpu.frequency")
	m.data.SetDescription("Current frequency of the CPU core in Hz.")
	m.data.SetUnit("Hz")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricSystemCPUFrequency) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, cpuAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSystemCPUFrequency) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSystemCPUFrequency) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricSystemCPUFrequency(cfg SystemCPUFrequencyMetricConfig) metricSystemCPUFrequency {
	_ = "STUB: not implemented"
	return *new(metricSystemCPUFrequency)
}

type metricSystemCPULogicalCount struct {
	data     pmetric.Metric                    // data buffer for generated metric.
	config   SystemCPULogicalCountMetricConfig // metric config provided by user.
	capacity int                               // max observed number of data points added to the metric.
}

// init fills system.cpu.logical.count metric with initial data.
func (m *metricSystemCPULogicalCount) init() {
	m.data.SetName("system.cpu.logical.count")
	m.data.SetDescription("Number of available logical CPUs.")
	m.data.SetUnit("{cpu}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricSystemCPULogicalCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSystemCPULogicalCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSystemCPULogicalCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricSystemCPULogicalCount(cfg SystemCPULogicalCountMetricConfig) metricSystemCPULogicalCount {
	_ = "STUB: not implemented"
	return *new(metricSystemCPULogicalCount)
}

type metricSystemCPUPhysicalCount struct {
	data     pmetric.Metric                     // data buffer for generated metric.
	config   SystemCPUPhysicalCountMetricConfig // metric config provided by user.
	capacity int                                // max observed number of data points added to the metric.
}

// init fills system.cpu.physical.count metric with initial data.
func (m *metricSystemCPUPhysicalCount) init() {
	m.data.SetName("system.cpu.physical.count")
	m.data.SetDescription("Number of available physical CPUs.")
	m.data.SetUnit("{cpu}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricSystemCPUPhysicalCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSystemCPUPhysicalCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSystemCPUPhysicalCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricSystemCPUPhysicalCount(cfg SystemCPUPhysicalCountMetricConfig) metricSystemCPUPhysicalCount {
	_ = "STUB: not implemented"
	return *new(metricSystemCPUPhysicalCount)
}

type metricSystemCPUTime struct {
	data          pmetric.Metric            // data buffer for generated metric.
	config        SystemCPUTimeMetricConfig // metric config provided by user.
	capacity      int                       // max observed number of data points added to the metric.
	aggDataPoints []float64                 // slice containing number of aggregated datapoints at each index
}

// init fills system.cpu.time metric with initial data.
func (m *metricSystemCPUTime) init() {
	m.data.SetName("system.cpu.time")
	m.data.SetDescription("Total seconds each logical CPU spent on each mode.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricSystemCPUTime) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, cpuAttributeValue string, stateAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSystemCPUTime) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSystemCPUTime) emit(metrics pmetric.MetricSlice) { _ = "STUB: not implemented"; return }

func newMetricSystemCPUTime(cfg SystemCPUTimeMetricConfig) metricSystemCPUTime {
	_ = "STUB: not implemented"
	return *new(metricSystemCPUTime)
}

type metricSystemCPUUtilization struct {
	data          pmetric.Metric                   // data buffer for generated metric.
	config        SystemCPUUtilizationMetricConfig // metric config provided by user.
	capacity      int                              // max observed number of data points added to the metric.
	aggDataPoints []float64                        // slice containing number of aggregated datapoints at each index
}

// init fills system.cpu.utilization metric with initial data.
func (m *metricSystemCPUUtilization) init() {
	m.data.SetName("system.cpu.utilization")
	m.data.SetDescription("Difference in system.cpu.time since the last measurement per logical CPU, divided by the elapsed time (value in interval [0,1]).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricSystemCPUUtilization) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, cpuAttributeValue string, stateAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSystemCPUUtilization) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSystemCPUUtilization) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricSystemCPUUtilization(cfg SystemCPUUtilizationMetricConfig) metricSystemCPUUtilization {
	_ = "STUB: not implemented"
	return *new(metricSystemCPUUtilization)
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                       MetricsBuilderConfig // config of the metrics builder.
	startTime                    pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity              int                  // maximum observed number of metrics per resource.
	metricsBuffer                pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                    component.BuildInfo  // contains version information.
	metricSystemCPUFrequency     metricSystemCPUFrequency
	metricSystemCPULogicalCount  metricSystemCPULogicalCount
	metricSystemCPUPhysicalCount metricSystemCPUPhysicalCount
	metricSystemCPUTime          metricSystemCPUTime
	metricSystemCPUUtilization   metricSystemCPUUtilization
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	_ = "STUB: not implemented"

	// WithStartTime sets startTime on the metrics builder.
	return
}

func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	_ = "STUB: not implemented"
	return *new(MetricBuilderOption)
}

func NewMetricsBuilder(mbc MetricsBuilderConfig, settings scraper.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	_ = "STUB: not implemented"
	return nil
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"
	return
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"

	// WithResource sets the provided resource on the emitted ResourceMetrics.
	// It's recommended to use ResourceBuilder to create the resource.
	return
}

func WithResource(res pcommon.Resource) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	_ = "STUB: not implemented"
	return
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	_ = "STUB: not implemented"
	return *new(pmetric.Metrics)
}

// RecordSystemCPUFrequencyDataPoint adds a data point to system.cpu.frequency metric.
func (mb *MetricsBuilder) RecordSystemCPUFrequencyDataPoint(ts pcommon.Timestamp, val float64, cpuAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// RecordSystemCPULogicalCountDataPoint adds a data point to system.cpu.logical.count metric.
func (mb *MetricsBuilder) RecordSystemCPULogicalCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordSystemCPUPhysicalCountDataPoint adds a data point to system.cpu.physical.count metric.
func (mb *MetricsBuilder) RecordSystemCPUPhysicalCountDataPoint(ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// RecordSystemCPUTimeDataPoint adds a data point to system.cpu.time metric.
func (mb *MetricsBuilder) RecordSystemCPUTimeDataPoint(ts pcommon.Timestamp, val float64, cpuAttributeValue string, stateAttributeValue AttributeState) {
	_ = "STUB: not implemented"
	return
}

// RecordSystemCPUUtilizationDataPoint adds a data point to system.cpu.utilization metric.
func (mb *MetricsBuilder) RecordSystemCPUUtilizationDataPoint(ts pcommon.Timestamp, val float64, cpuAttributeValue string, stateAttributeValue AttributeState) {
	_ = "STUB: not implemented"
	return
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) { _ = "STUB: not implemented"; return }
