// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	time "time"

	gosnmp "github.com/gosnmp/gosnmp"
	mock "github.com/stretchr/testify/mock"
)

// goSNMPWrapper is an autogenerated mock type for the goSNMPWrapper type
type MockGoSNMPWrapper struct {
	mock.Mock
}

// BulkWalkAll provides a mock function with given fields: rootOid
func (_m *MockGoSNMPWrapper) BulkWalkAll(rootOid string) ([]gosnmp.SnmpPDU, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Close provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) Close() error { _ = "STUB: not implemented"; return nil }

// Connect provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) Connect() error { _ = "STUB: not implemented"; return nil }

// Get provides a mock function with given fields: oids
func (_m *MockGoSNMPWrapper) Get(oids []string) (*gosnmp.SnmpPacket, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetCommunity provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetCommunity() string { _ = "STUB: not implemented"; return "" }

// GetMaxOids provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetMaxOids() int { _ = "STUB: not implemented"; return 0 }

// GetMsgFlags provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetMsgFlags() gosnmp.SnmpV3MsgFlags {
	_ = "STUB: not implemented"
	return *new(gosnmp.SnmpV3MsgFlags)
}

// GetPort provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetPort() uint16 { _ = "STUB: not implemented"; return 0 }

// GetSecurityModel provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetSecurityModel() gosnmp.SnmpV3SecurityModel {
	_ = "STUB: not implemented"
	return *new(gosnmp.SnmpV3SecurityModel)
}

// GetSecurityParameters provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetSecurityParameters() gosnmp.SnmpV3SecurityParameters {
	_ = "STUB: not implemented"
	return *new(gosnmp.SnmpV3SecurityParameters)
}

// GetTarget provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetTarget() string { _ = "STUB: not implemented"; return "" }

// GetTimeout provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetTimeout() time.Duration {
	_ = "STUB: not implemented"
	return *new(time.Duration)
}

// GetTransport provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetTransport() string { _ = "STUB: not implemented"; return "" }

// GetVersion provides a mock function with given fields:
func (_m *MockGoSNMPWrapper) GetVersion() gosnmp.SnmpVersion {
	_ = "STUB: not implemented"
	return *new(gosnmp.SnmpVersion)
}

// SetCommunity provides a mock function with given fields: community
func (_m *MockGoSNMPWrapper) SetCommunity(community string) { _ = "STUB: not implemented"; return }

// SetMaxOids provides a mock function with given fields: maxOids
func (_m *MockGoSNMPWrapper) SetMaxOids(maxOids int) {
	_ = "STUB: not implemented"

	// SetMsgFlags provides a mock function with given fields: msgFlags
	return
}

func (_m *MockGoSNMPWrapper) SetMsgFlags(msgFlags gosnmp.SnmpV3MsgFlags) {
	_ = "STUB: not implemented"
	return

	// SetPort provides a mock function with given fields: port
}

func (_m *MockGoSNMPWrapper) SetPort(port uint16) {
	_ = "STUB: not implemented"

	// SetSecurityModel provides a mock function with given fields: securityModel
	return
}

func (_m *MockGoSNMPWrapper) SetSecurityModel(securityModel gosnmp.SnmpV3SecurityModel) {
	_ = "STUB: not implemented"
	return
}

// SetSecurityParameters provides a mock function with given fields: securityParameters
func (_m *MockGoSNMPWrapper) SetSecurityParameters(securityParameters gosnmp.SnmpV3SecurityParameters) {
	_ = "STUB: not implemented"
	return
}

// SetTarget provides a mock function with given fields: target
func (_m *MockGoSNMPWrapper) SetTarget(target string) {
	_ = "STUB: not implemented"

	// SetTimeout provides a mock function with given fields: timeout
	return
}

func (_m *MockGoSNMPWrapper) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"

	// SetTransport provides a mock function with given fields: transport
	return
}

func (_m *MockGoSNMPWrapper) SetTransport(transport string) { _ = "STUB: not implemented"; return }

// SetVersion provides a mock function with given fields: version
func (_m *MockGoSNMPWrapper) SetVersion(version gosnmp.SnmpVersion) {
	_ = "STUB: not implemented"
	return

	// WalkAll provides a mock function with given fields: rootOid
}

func (_m *MockGoSNMPWrapper) WalkAll(rootOid string) ([]gosnmp.SnmpPDU, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type mockNewGoSNMPWrapperT interface {
	mock.TestingT
	Cleanup(func())
}

// newMockGoSNMPWrapper creates a new instance of goSNMPWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockGoSNMPWrapper(t mockNewGoSNMPWrapperT) *MockGoSNMPWrapper {
	_ = "STUB: not implemented"
	return nil
}
