// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	_ = "STUB: not implemented"
	return nil
}

// SetContainerID sets provided value as "container.id" attribute.
func (rb *ResourceBuilder) SetContainerID(val string) { _ = "STUB: not implemented"; return }

// SetContainerImageName sets provided value as "container.image.name" attribute.
func (rb *ResourceBuilder) SetContainerImageName(val string) { _ = "STUB: not implemented"; return }

// SetContainerImageRepoDigests sets provided value as "container.image.repo_digests" attribute.
func (rb *ResourceBuilder) SetContainerImageRepoDigests(val []any) {
	_ = "STUB: not implemented"
	return
}

// SetContainerImageTag sets provided value as "container.image.tag" attribute.
func (rb *ResourceBuilder) SetContainerImageTag(val string) { _ = "STUB: not implemented"; return }

// SetContainerImageTags sets provided value as "container.image.tags" attribute.
func (rb *ResourceBuilder) SetContainerImageTags(val []any) { _ = "STUB: not implemented"; return }

// SetK8sClusterUID sets provided value as "k8s.cluster.uid" attribute.
func (rb *ResourceBuilder) SetK8sClusterUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sContainerName sets provided value as "k8s.container.name" attribute.
func (rb *ResourceBuilder) SetK8sContainerName(val string) { _ = "STUB: not implemented"; return }

// SetK8sCronjobName sets provided value as "k8s.cronjob.name" attribute.
func (rb *ResourceBuilder) SetK8sCronjobName(val string) { _ = "STUB: not implemented"; return }

// SetK8sCronjobUID sets provided value as "k8s.cronjob.uid" attribute.
func (rb *ResourceBuilder) SetK8sCronjobUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sDaemonsetName sets provided value as "k8s.daemonset.name" attribute.
func (rb *ResourceBuilder) SetK8sDaemonsetName(val string) { _ = "STUB: not implemented"; return }

// SetK8sDaemonsetUID sets provided value as "k8s.daemonset.uid" attribute.
func (rb *ResourceBuilder) SetK8sDaemonsetUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sDeploymentName sets provided value as "k8s.deployment.name" attribute.
func (rb *ResourceBuilder) SetK8sDeploymentName(val string) { _ = "STUB: not implemented"; return }

// SetK8sDeploymentUID sets provided value as "k8s.deployment.uid" attribute.
func (rb *ResourceBuilder) SetK8sDeploymentUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sJobName sets provided value as "k8s.job.name" attribute.
func (rb *ResourceBuilder) SetK8sJobName(val string) { _ = "STUB: not implemented"; return }

// SetK8sJobUID sets provided value as "k8s.job.uid" attribute.
func (rb *ResourceBuilder) SetK8sJobUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sNamespaceName sets provided value as "k8s.namespace.name" attribute.
func (rb *ResourceBuilder) SetK8sNamespaceName(val string) { _ = "STUB: not implemented"; return }

// SetK8sNodeName sets provided value as "k8s.node.name" attribute.
func (rb *ResourceBuilder) SetK8sNodeName(val string) { _ = "STUB: not implemented"; return }

// SetK8sNodeUID sets provided value as "k8s.node.uid" attribute.
func (rb *ResourceBuilder) SetK8sNodeUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sPodHostname sets provided value as "k8s.pod.hostname" attribute.
func (rb *ResourceBuilder) SetK8sPodHostname(val string) { _ = "STUB: not implemented"; return }

// SetK8sPodIP sets provided value as "k8s.pod.ip" attribute.
func (rb *ResourceBuilder) SetK8sPodIP(val string) { _ = "STUB: not implemented"; return }

// SetK8sPodName sets provided value as "k8s.pod.name" attribute.
func (rb *ResourceBuilder) SetK8sPodName(val string) { _ = "STUB: not implemented"; return }

// SetK8sPodStartTime sets provided value as "k8s.pod.start_time" attribute.
func (rb *ResourceBuilder) SetK8sPodStartTime(val string) { _ = "STUB: not implemented"; return }

// SetK8sPodUID sets provided value as "k8s.pod.uid" attribute.
func (rb *ResourceBuilder) SetK8sPodUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sReplicasetName sets provided value as "k8s.replicaset.name" attribute.
func (rb *ResourceBuilder) SetK8sReplicasetName(val string) { _ = "STUB: not implemented"; return }

// SetK8sReplicasetUID sets provided value as "k8s.replicaset.uid" attribute.
func (rb *ResourceBuilder) SetK8sReplicasetUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sStatefulsetName sets provided value as "k8s.statefulset.name" attribute.
func (rb *ResourceBuilder) SetK8sStatefulsetName(val string) { _ = "STUB: not implemented"; return }

// SetK8sStatefulsetUID sets provided value as "k8s.statefulset.uid" attribute.
func (rb *ResourceBuilder) SetK8sStatefulsetUID(val string) { _ = "STUB: not implemented"; return }

// SetServiceInstanceID sets provided value as "service.instance.id" attribute.
func (rb *ResourceBuilder) SetServiceInstanceID(val string) { _ = "STUB: not implemented"; return }

// SetServiceName sets provided value as "service.name" attribute.
func (rb *ResourceBuilder) SetServiceName(val string) { _ = "STUB: not implemented"; return }

// SetServiceNamespace sets provided value as "service.namespace" attribute.
func (rb *ResourceBuilder) SetServiceNamespace(val string) { _ = "STUB: not implemented"; return }

// SetServiceVersion sets provided value as "service.version" attribute.
func (rb *ResourceBuilder) SetServiceVersion(val string) { _ = "STUB: not implemented"; return }

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	_ = "STUB: not implemented"
	return *new(pcommon.Resource)
}
