// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"encoding"
	"fmt"
	"regexp"
)

type Args struct {
	BasePrefix     string
	Dir            string
	SkippedModules CommaSeparatedSet
}

// CommaSeparatedSet is a custom type for parsing comma-separated values.
// Duplicate entries are ignored.
type CommaSeparatedSet map[string]struct{}

var _ encoding.TextMarshaler = (*CommaSeparatedSet)(nil)

func (c CommaSeparatedSet) MarshalText() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _ encoding.TextUnmarshaler = (*CommaSeparatedSet)(nil)

func (c *CommaSeparatedSet) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func setupCLI() (Args, error) { _ = "STUB: not implemented"; return *new(Args), nil }

func main() {
	args, err := setupCLI()
	if err != nil {
		fmt.Println("Error:", err)
		return
	}

	// Generate the .codecov.yaml
	config, err := walkTree(args)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}

	// Add component list to the config
	err = addComponentList(config, args)
	if err != nil {
		fmt.Println("Error adding component list:", err)
	}
}

// component represents a component in the Codecov configuration.
type component struct {
	ComponentID string   `yaml:"component_id"`
	Name        string   `yaml:"name"`
	Paths       []string `yaml:"paths"`
}

type componentManagement struct {
	IndividualComponents []component `yaml:"individual_components"`
}

type codecovConfig struct {
	ComponentManagement componentManagement `yaml:"component_management"`
}

var (
	// validFlagRegexp is a regular expression to validate codecov flags.
	// It is mentioned here: https://docs.codecov.com/docs/flags
	// It's unclear if components fit this pattern, but they seem to work with it.
	validFlagRegexp = regexp.MustCompile(`^[\w.\-]{1,45}$`)

	// defaultSuffixList is a list of suffixes to remove from the module name.
	// We remove the suffixes so that the component ID is shorter.
	defaultSuffixList = []string{
		"receiver",
		"exporter",
		"extension",
		"processor",
		"connector",
		"scraper",
	}
)

func generateComponentID(moduleName string, cli Args) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// walkTree uses filepath.Walk to recursively traverse the base directory looking for go.mod files
func walkTree(cli Args) (*codecovConfig, error) { _ = "STUB: not implemented"; return nil, nil }

// Skip non-directories

// Skip if the module is in the skipped list

// Create component and add it to the config

// readModuleName reads the go.mod file and returns the module's name
func readModuleName(goModPath string) (string, error) { _ = "STUB: not implemented"; return "", nil }

const (
	codecovFileName    = ".codecov.yml"
	startComponentList = `# Start autogenerated components list`
	endComponentList   = `# End autogenerated components list`
)

var matchComponentSection = regexp.MustCompile("(?s)" + startComponentList + ".*" + endComponentList)

func addComponentList(config *codecovConfig, cli Args) error { _ = "STUB: not implemented"; return nil }
