// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ResourceAttributesConfig provides config for resourcedetectionprocessor/system resource attributes.
type ResourceAttributesConfig struct {
	HostArch           ResourceAttributeConfig `mapstructure:"host.arch"`
	HostCPUCacheL2Size ResourceAttributeConfig `mapstructure:"host.cpu.cache.l2.size"`
	HostCPUFamily      ResourceAttributeConfig `mapstructure:"host.cpu.family"`
	HostCPUModelID     ResourceAttributeConfig `mapstructure:"host.cpu.model.id"`
	HostCPUModelName   ResourceAttributeConfig `mapstructure:"host.cpu.model.name"`
	HostCPUStepping    ResourceAttributeConfig `mapstructure:"host.cpu.stepping"`
	HostCPUVendorID    ResourceAttributeConfig `mapstructure:"host.cpu.vendor.id"`
	HostID             ResourceAttributeConfig `mapstructure:"host.id"`
	HostInterface      ResourceAttributeConfig `mapstructure:"host.interface"`
	HostIP             ResourceAttributeConfig `mapstructure:"host.ip"`
	HostMac            ResourceAttributeConfig `mapstructure:"host.mac"`
	HostName           ResourceAttributeConfig `mapstructure:"host.name"`
	OsBuildID          ResourceAttributeConfig `mapstructure:"os.build.id"`
	OsDescription      ResourceAttributeConfig `mapstructure:"os.description"`
	OsName             ResourceAttributeConfig `mapstructure:"os.name"`
	OsType             ResourceAttributeConfig `mapstructure:"os.type"`
	OsVersion          ResourceAttributeConfig `mapstructure:"os.version"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	_ = "STUB: not implemented"
	return *new(ResourceAttributesConfig)
}
