// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	_ = "STUB: not implemented"
	return nil
}

// SetFlinkJobName sets provided value as "flink.job.name" attribute.
func (rb *ResourceBuilder) SetFlinkJobName(val string) { _ = "STUB: not implemented"; return }

// SetFlinkResourceTypeJobmanager sets "flink.resource.type=jobmanager" attribute.
func (rb *ResourceBuilder) SetFlinkResourceTypeJobmanager() { _ = "STUB: not implemented"; return }

// SetFlinkResourceTypeTaskmanager sets "flink.resource.type=taskmanager" attribute.
func (rb *ResourceBuilder) SetFlinkResourceTypeTaskmanager() { _ = "STUB: not implemented"; return }

// SetFlinkSubtaskIndex sets provided value as "flink.subtask.index" attribute.
func (rb *ResourceBuilder) SetFlinkSubtaskIndex(val string) { _ = "STUB: not implemented"; return }

// SetFlinkTaskName sets provided value as "flink.task.name" attribute.
func (rb *ResourceBuilder) SetFlinkTaskName(val string) { _ = "STUB: not implemented"; return }

// SetFlinkTaskmanagerID sets provided value as "flink.taskmanager.id" attribute.
func (rb *ResourceBuilder) SetFlinkTaskmanagerID(val string) { _ = "STUB: not implemented"; return }

// SetHostName sets provided value as "host.name" attribute.
func (rb *ResourceBuilder) SetHostName(val string) { _ = "STUB: not implemented"; return }

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	_ = "STUB: not implemented"
	return *new(pcommon.Resource)
}
