// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package dockerobserver // import "github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/dockerobserver"

import (
	"context"

	ctypes "github.com/moby/moby/api/types/container"
	"github.com/moby/moby/api/types/network"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/extension"
	"go.uber.org/zap"
	"golang.org/x/sync/errgroup"

	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/endpointswatcher"
	"github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker"
)

var (
	defaultDockerAPIVersion         = "1.44"
	minimumRequiredDockerAPIVersion = docker.MustNewAPIVersion(defaultDockerAPIVersion)
)

var (
	_ extension.Extension = (*dockerObserver)(nil)
	_ observer.Observable = (*dockerObserver)(nil)
)

type dockerObserver struct {
	*endpointswatcher.EndpointsWatcher
	logger  *zap.Logger
	config  *Config
	cancel  context.CancelFunc
	wg      errgroup.Group
	dClient *docker.Client
}

// newObserver creates a new docker observer extension.
func newObserver(logger *zap.Logger, config *Config) (extension.Extension, error) {
	_ = "STUB: not implemented"
	return *new(extension.Extension), nil
}

// Safe value provided on initialisation

// Start will instantiate required components needed by the Docker observer
func (d *dockerObserver) Start(ctx context.Context, _ component.Host) error {
	_ = "STUB: not implemented"
	return nil
}

// Create new Docker client

func (d *dockerObserver) Shutdown(_ context.Context) error { _ = "STUB: not implemented"; return nil }

func (d *dockerObserver) ListEndpoints() []observer.Endpoint { _ = "STUB: not implemented"; return nil }

// containerEndpoints generates a list of observer.Endpoint given a Docker InspectResponse.
// This function will only generate endpoints if a container is in the Running state and not Paused.
func (d *dockerObserver) containerEndpoints(c *ctypes.InspectResponse) []observer.Endpoint {
	_ = "STUB: not implemented"
	return nil
}

// iterate over exposed ports and try to create endpoints

// the endpoint was not set, so we'll drop it

// endpointForContainer creates a port-less observer.Endpoint for the container itself.
// It is emitted when IncludeAllContainers is enabled so that receiver_creator rules
// matching `type == "container"` can attach receivers to every running container,
// including those that expose no ports.
func (d *dockerObserver) endpointForContainer(c *ctypes.InspectResponse) *observer.Endpoint {
	_ = "STUB: not implemented"
	return nil
}

// containerHost resolves a host string for a container without considering port bindings.
func (d *dockerObserver) containerHost(c *ctypes.InspectResponse) string {
	_ = "STUB: not implemented"
	return ""
}

// endpointForPort creates an observer.Endpoint for a given port that is exposed in a Docker container.
// Each endpoint has a unique ID generated by the combination of the container.ID, container.Name,
// underlying host name, and the port number.
// Uses the user provided config settings to override certain fields.
func (d *dockerObserver) endpointForPort(portObj network.Port, c *ctypes.InspectResponse) *observer.Endpoint {
	_ = "STUB: not implemented"
	return nil
}

// unique ID per containerID:port

// Set our hostname based on config settings

// Use the IP Address of the first network we iterate over.
// This can be made configurable if so desired.

// If we still haven't gotten a host at this point and we are using
// host bindings, just make it localhost.

// If we are using HostBindings & port and IP are set, use those

// FindHostMappedPort returns the port number of the docker port binding to the
// underlying host, or 0 if none exists.  It also returns the mapped ip that the
// port is bound to on the underlying host, or "" if none exists.
func findHostMappedPort(c *ctypes.InspectResponse, exposedPort network.Port) (uint16, string) {
	_ = "STUB: not implemented"
	return 0, ""
}

// Valid proto for docker containers should be tcp, udp, sctp
// https://pkg.go.dev/github.com/moby/moby/api/types/network@v1.54.1#IPProtocol
func portProtoToTransport(proto string) observer.Transport {
	_ = "STUB: not implemented"
	return *new(observer.Transport)
}
