// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/processor"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"
)

func NewSettings(tt *componenttest.Telemetry) processor.Settings {
	_ = "STUB: not implemented"
	return *new(processor.Settings)
}

func AssertEqualProcessorSchemaTranslated(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaCacheHits(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaCacheMisses(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaLogsFailed(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaLogsSkipped(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaMetricsFailed(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaMetricsSkipped(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaResourceFailed(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaTracesFailed(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}

func AssertEqualProcessorSchemaTracesSkipped(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	_ = "STUB: not implemented"
	return
}
