// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	_ = "STUB: not implemented"
	return nil
}

// SetAwsVolumeID sets provided value as "aws.volume.id" attribute.
func (rb *ResourceBuilder) SetAwsVolumeID(val string) { _ = "STUB: not implemented"; return }

// SetContainerID sets provided value as "container.id" attribute.
func (rb *ResourceBuilder) SetContainerID(val string) { _ = "STUB: not implemented"; return }

// SetFsType sets provided value as "fs.type" attribute.
func (rb *ResourceBuilder) SetFsType(val string) { _ = "STUB: not implemented"; return }

// SetGcePdName sets provided value as "gce.pd.name" attribute.
func (rb *ResourceBuilder) SetGcePdName(val string) { _ = "STUB: not implemented"; return }

// SetGlusterfsEndpointsName sets provided value as "glusterfs.endpoints.name" attribute.
func (rb *ResourceBuilder) SetGlusterfsEndpointsName(val string) { _ = "STUB: not implemented"; return }

// SetGlusterfsPath sets provided value as "glusterfs.path" attribute.
func (rb *ResourceBuilder) SetGlusterfsPath(val string) { _ = "STUB: not implemented"; return }

// SetK8sContainerName sets provided value as "k8s.container.name" attribute.
func (rb *ResourceBuilder) SetK8sContainerName(val string) { _ = "STUB: not implemented"; return }

// SetK8sNamespaceName sets provided value as "k8s.namespace.name" attribute.
func (rb *ResourceBuilder) SetK8sNamespaceName(val string) { _ = "STUB: not implemented"; return }

// SetK8sNodeName sets provided value as "k8s.node.name" attribute.
func (rb *ResourceBuilder) SetK8sNodeName(val string) { _ = "STUB: not implemented"; return }

// SetK8sNodeSystemContainerName sets provided value as "k8s.node.system_container.name" attribute.
func (rb *ResourceBuilder) SetK8sNodeSystemContainerName(val string) {
	_ = "STUB: not implemented"
	return
}

// SetK8sPersistentvolumeclaimName sets provided value as "k8s.persistentvolumeclaim.name" attribute.
func (rb *ResourceBuilder) SetK8sPersistentvolumeclaimName(val string) {
	_ = "STUB: not implemented"
	return
}

// SetK8sPodName sets provided value as "k8s.pod.name" attribute.
func (rb *ResourceBuilder) SetK8sPodName(val string) { _ = "STUB: not implemented"; return }

// SetK8sPodUID sets provided value as "k8s.pod.uid" attribute.
func (rb *ResourceBuilder) SetK8sPodUID(val string) { _ = "STUB: not implemented"; return }

// SetK8sVolumeName sets provided value as "k8s.volume.name" attribute.
func (rb *ResourceBuilder) SetK8sVolumeName(val string) { _ = "STUB: not implemented"; return }

// SetK8sVolumeType sets provided value as "k8s.volume.type" attribute.
func (rb *ResourceBuilder) SetK8sVolumeType(val string) { _ = "STUB: not implemented"; return }

// SetPartition sets provided value as "partition" attribute.
func (rb *ResourceBuilder) SetPartition(val string) { _ = "STUB: not implemented"; return }

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	_ = "STUB: not implemented"
	return *new(pcommon.Resource)
}
