// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// SystemNetworkConnectionsMetricAttributeKey specifies the key of an attribute for the system.network.connections metric.
type SystemNetworkConnectionsMetricAttributeKey string

const (
	SystemNetworkConnectionsMetricAttributeKeyProtocol SystemNetworkConnectionsMetricAttributeKey = "protocol"
	SystemNetworkConnectionsMetricAttributeKeyState    SystemNetworkConnectionsMetricAttributeKey = "state"
)

// SystemNetworkConnectionsMetricConfig provides config for the system.network.connections metric.
type SystemNetworkConnectionsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                       `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkConnectionsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkConnectionsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemNetworkConnectionsMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// SystemNetworkConntrackCountMetricConfig provides config for the system.network.conntrack.count metric.
type SystemNetworkConntrackCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SystemNetworkConntrackCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// SystemNetworkConntrackMaxMetricConfig provides config for the system.network.conntrack.max metric.
type SystemNetworkConntrackMaxMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SystemNetworkConntrackMaxMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// SystemNetworkDroppedMetricAttributeKey specifies the key of an attribute for the system.network.dropped metric.
type SystemNetworkDroppedMetricAttributeKey string

const (
	SystemNetworkDroppedMetricAttributeKeyDevice    SystemNetworkDroppedMetricAttributeKey = "device"
	SystemNetworkDroppedMetricAttributeKeyDirection SystemNetworkDroppedMetricAttributeKey = "direction"
)

// SystemNetworkDroppedMetricConfig provides config for the system.network.dropped metric.
type SystemNetworkDroppedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkDroppedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkDroppedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemNetworkDroppedMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// SystemNetworkErrorsMetricAttributeKey specifies the key of an attribute for the system.network.errors metric.
type SystemNetworkErrorsMetricAttributeKey string

const (
	SystemNetworkErrorsMetricAttributeKeyDevice    SystemNetworkErrorsMetricAttributeKey = "device"
	SystemNetworkErrorsMetricAttributeKeyDirection SystemNetworkErrorsMetricAttributeKey = "direction"
)

// SystemNetworkErrorsMetricConfig provides config for the system.network.errors metric.
type SystemNetworkErrorsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkErrorsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkErrorsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemNetworkErrorsMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// SystemNetworkIoMetricAttributeKey specifies the key of an attribute for the system.network.io metric.
type SystemNetworkIoMetricAttributeKey string

const (
	SystemNetworkIoMetricAttributeKeyDevice    SystemNetworkIoMetricAttributeKey = "device"
	SystemNetworkIoMetricAttributeKeyDirection SystemNetworkIoMetricAttributeKey = "direction"
)

// SystemNetworkIoMetricConfig provides config for the system.network.io metric.
type SystemNetworkIoMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                              `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkIoMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkIoMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemNetworkIoMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// SystemNetworkPacketsMetricAttributeKey specifies the key of an attribute for the system.network.packets metric.
type SystemNetworkPacketsMetricAttributeKey string

const (
	SystemNetworkPacketsMetricAttributeKeyDevice    SystemNetworkPacketsMetricAttributeKey = "device"
	SystemNetworkPacketsMetricAttributeKeyDirection SystemNetworkPacketsMetricAttributeKey = "direction"
)

// SystemNetworkPacketsMetricConfig provides config for the system.network.packets metric.
type SystemNetworkPacketsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SystemNetworkPacketsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SystemNetworkPacketsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *SystemNetworkPacketsMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// MetricsConfig provides config for network metrics.
type MetricsConfig struct {
	SystemNetworkConnections    SystemNetworkConnectionsMetricConfig    `mapstructure:"system.network.connections"`
	SystemNetworkConntrackCount SystemNetworkConntrackCountMetricConfig `mapstructure:"system.network.conntrack.count"`
	SystemNetworkConntrackMax   SystemNetworkConntrackMaxMetricConfig   `mapstructure:"system.network.conntrack.max"`
	SystemNetworkDropped        SystemNetworkDroppedMetricConfig        `mapstructure:"system.network.dropped"`
	SystemNetworkErrors         SystemNetworkErrorsMetricConfig         `mapstructure:"system.network.errors"`
	SystemNetworkIo             SystemNetworkIoMetricConfig             `mapstructure:"system.network.io"`
	SystemNetworkPackets        SystemNetworkPacketsMetricConfig        `mapstructure:"system.network.packets"`
}

func DefaultMetricsConfig() MetricsConfig { _ = "STUB: not implemented"; return *new(MetricsConfig) }

// MetricsBuilderConfig is a configuration for network metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}
