// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/s3.go
//
// Generated by this command:
//
//	mockgen -source=./internal/s3.go -destination=./internal/mock_s3_service.go -package=internal
//

// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	io "io"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// Mocks3API is a mock of s3API interface.
type Mocks3API struct {
	ctrl     *gomock.Controller
	recorder *Mocks3APIMockRecorder
	isgomock struct{}
}

// Mocks3APIMockRecorder is the mock recorder for Mocks3API.
type Mocks3APIMockRecorder struct {
	mock *Mocks3API
}

// NewMocks3API creates a new mock instance.
func NewMocks3API(ctrl *gomock.Controller) *Mocks3API { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocks3API) EXPECT() *Mocks3APIMockRecorder {
	_ = "STUB: not implemented"

	// DeleteObject mocks base method.
	return nil
}

func (m *Mocks3API) DeleteObject(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *Mocks3APIMockRecorder) DeleteObject(ctx, params any, optFns ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetObject mocks base method.
func (m *Mocks3API) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetObject indicates an expected call of GetObject.
func (mr *Mocks3APIMockRecorder) GetObject(ctx, params any, optFns ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjectsV2 mocks base method.
func (m *Mocks3API) ListObjectsV2(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjectsV2 indicates an expected call of ListObjectsV2.
func (mr *Mocks3APIMockRecorder) ListObjectsV2(ctx, params any, optFns ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockS3Service is a mock of S3Service interface.
type MockS3Service struct {
	ctrl     *gomock.Controller
	recorder *MockS3ServiceMockRecorder
	isgomock struct{}
}

// MockS3ServiceMockRecorder is the mock recorder for MockS3Service.
type MockS3ServiceMockRecorder struct {
	mock *MockS3Service
}

// NewMockS3Service creates a new mock instance.
func NewMockS3Service(ctrl *gomock.Controller) *MockS3Service {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Service) EXPECT() *MockS3ServiceMockRecorder {
	_ = "STUB: not implemented"

	// DeleteObject mocks base method.
	return nil
}

func (m *MockS3Service) DeleteObject(ctx context.Context, bucketName, objectKey string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockS3ServiceMockRecorder) DeleteObject(ctx, bucketName, objectKey any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetReader mocks base method.
func (m *MockS3Service) GetReader(ctx context.Context, bucketName, objectKey string) (io.ReadCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), nil
}

// GetReader indicates an expected call of GetReader.
func (mr *MockS3ServiceMockRecorder) GetReader(ctx, bucketName, objectKey any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListObjects mocks base method.
func (m *MockS3Service) ListObjects(ctx context.Context, bucketName, continuationToken, prefix string) (*s3.ListObjectsV2Output, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockS3ServiceMockRecorder) ListObjects(ctx, bucketName, continuationToken, prefix any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadObject mocks base method.
func (m *MockS3Service) ReadObject(ctx context.Context, bucketName, objectKey string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadObject indicates an expected call of ReadObject.
func (mr *MockS3ServiceMockRecorder) ReadObject(ctx, bucketName, objectKey any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockS3Provider is a mock of S3Provider interface.
type MockS3Provider struct {
	ctrl     *gomock.Controller
	recorder *MockS3ProviderMockRecorder
	isgomock struct{}
}

// MockS3ProviderMockRecorder is the mock recorder for MockS3Provider.
type MockS3ProviderMockRecorder struct {
	mock *MockS3Provider
}

// NewMockS3Provider creates a new mock instance.
func NewMockS3Provider(ctrl *gomock.Controller) *MockS3Provider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Provider) EXPECT() *MockS3ProviderMockRecorder {
	_ = "STUB: not implemented"

	// GetService mocks base method.
	return nil
}

func (m *MockS3Provider) GetService(ctx context.Context) (S3Service, error) {
	_ = "STUB: not implemented"
	return *new(S3Service), nil
}

// GetService indicates an expected call of GetService.
func (mr *MockS3ProviderMockRecorder) GetService(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
