// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// TcpcheckDurationMetricConfig provides config for the tcpcheck.duration metric.
type TcpcheckDurationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *TcpcheckDurationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// TcpcheckErrorMetricAttributeKey specifies the key of an attribute for the tcpcheck.error metric.
type TcpcheckErrorMetricAttributeKey string

const (
	TcpcheckErrorMetricAttributeKeyTcpcheckEndpoint TcpcheckErrorMetricAttributeKey = "tcpcheck.endpoint"
	TcpcheckErrorMetricAttributeKeyErrorCode        TcpcheckErrorMetricAttributeKey = "error.code"
)

// TcpcheckErrorMetricConfig provides config for the tcpcheck.error metric.
type TcpcheckErrorMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []TcpcheckErrorMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *TcpcheckErrorMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *TcpcheckErrorMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// TcpcheckStatusMetricConfig provides config for the tcpcheck.status metric.
type TcpcheckStatusMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *TcpcheckStatusMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// MetricsConfig provides config for tcp_check metrics.
type MetricsConfig struct {
	TcpcheckDuration TcpcheckDurationMetricConfig `mapstructure:"tcpcheck.duration"`
	TcpcheckError    TcpcheckErrorMetricConfig    `mapstructure:"tcpcheck.error"`
	TcpcheckStatus   TcpcheckStatusMetricConfig   `mapstructure:"tcpcheck.status"`
}

func DefaultMetricsConfig() MetricsConfig { _ = "STUB: not implemented"; return *new(MetricsConfig) }

// MetricsBuilderConfig is a configuration for tcp_check metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}
