// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package translator // import "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver/internal/translator"

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/ptrace"

	awsxray "github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/xray"
	"github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/xray/telemetry"
)

const (
	// just a guess to avoid too many memory re-allocation
	initAttrCapacity = 15
)

// TODO: It might be nice to consolidate the `fromPdata` in x-ray exporter and
// `toPdata` in this receiver to a common package later

// ToTraces converts X-Ray segment (and its subsegments) to an OT ResourceSpans.
func ToTraces(rawSeg []byte, recorder telemetry.Recorder) (ptrace.Traces, int, error) {
	_ = "STUB: not implemented"
	return *new(ptrace.Traces), 0, nil
}

// return 1 as total segment (&subsegments) count
// because we can't parse the body the UDP packet.

// ## allocate a new ptrace.ResourceSpans for the segment document
// (potentially with embedded subsegments)

// ## initialize the fields in a ResourceSpans

// each segment (with its subsegments) is generated by one instrument
// library so only allocate one `ScopeSpans` in the
// `ScopeSpansSlice`.

// populating global attributes shared among segment and embedded subsegment(s)

// recursively traverse segment and embedded subsegments
// to populate the spans. We also need to pass in the
// TraceID of the root segment in because embedded subsegments
// do not have that information, but it's needed after we flatten
// the embedded subsegment to generate independent child spans.
// Sometimes, subsegments are sent separately in an async workflow,
// check segment type to determine the proper span kind.

func segToSpans(seg *awsxray.Segment, traceID, parentID *string, isSubsegment bool, spans ptrace.SpanSlice) (ptrace.Span, error) {
	_ = "STUB: not implemented"
	return *new(ptrace.Span), nil
}

// if seg.Cause is not nil, then one of the subsegments must contain a
// HTTP error code. Also, span.Status().Code() is already
// set to `StatusCodeUnknownError` by `addCause()` in
// `populateSpan()` above, so here we are just trying to figure out
// whether we can get an even more specific error code.

// update the error code to a possibly more specific code

func populateSpan(seg *awsxray.Segment, traceID, parentID *string, isSubsegment bool, span ptrace.Span) error {
	_ = "STUB: not implemented"
	return nil
}

// decode trace id

// if seg.TraceID is nil, then `seg` must be an embedded subsegment.

// decode parent id

// decode span id

func populateResource(seg *awsxray.Segment, rs pcommon.Resource) {
	_ = "STUB: not implemented"
	// allocate a new attribute map within the Resource in the ptrace.ResourceSpans allocated above
	return
}

func totalSegmentsCount(seg *awsxray.Segment) int { _ = "STUB: not implemented"; return 0 }

/*
decodeXRayTraceID decodes the traceid from xraysdk
one example of xray format: "1-5f84c7a1-e7d1852db8c4fd35d88bf49a"
decodeXRayTraceID transfers it to "5f84c7a1e7d1852db8c4fd35d88bf49a" and decode it from hex
*/
func decodeXRayTraceID(traceID *string) ([16]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// decodeXRaySpanID decodes the spanid from xraysdk
func decodeXRaySpanID(spanID *string) ([8]byte, error) { _ = "STUB: not implemented"; return nil, nil }
