// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	_ = "STUB: not implemented"
	return nil
}

// SetCloudProvider sets provided value as "cloud.provider" attribute.
func (rb *ResourceBuilder) SetCloudProvider(val string) { _ = "STUB: not implemented"; return }

// SetHerokuAppID sets provided value as "heroku.app.id" attribute.
func (rb *ResourceBuilder) SetHerokuAppID(val string) { _ = "STUB: not implemented"; return }

// SetHerokuDynoID sets provided value as "heroku.dyno.id" attribute.
func (rb *ResourceBuilder) SetHerokuDynoID(val string) { _ = "STUB: not implemented"; return }

// SetHerokuReleaseCommit sets provided value as "heroku.release.commit" attribute.
func (rb *ResourceBuilder) SetHerokuReleaseCommit(val string) { _ = "STUB: not implemented"; return }

// SetHerokuReleaseCreationTimestamp sets provided value as "heroku.release.creation_timestamp" attribute.
func (rb *ResourceBuilder) SetHerokuReleaseCreationTimestamp(val string) {
	_ = "STUB: not implemented"
	return
}

// SetServiceInstanceID sets provided value as "service.instance.id" attribute.
func (rb *ResourceBuilder) SetServiceInstanceID(val string) { _ = "STUB: not implemented"; return }

// SetServiceName sets provided value as "service.name" attribute.
func (rb *ResourceBuilder) SetServiceName(val string) { _ = "STUB: not implemented"; return }

// SetServiceVersion sets provided value as "service.version" attribute.
func (rb *ResourceBuilder) SetServiceVersion(val string) { _ = "STUB: not implemented"; return }

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	_ = "STUB: not implemented"
	return *new(pcommon.Resource)
}
