// Code generated by mockery v2.13.1. DO NOT EDIT.

package cluster

import (
	aerospike "github.com/aerospike/aerospike-client-go/v8"
	mock "github.com/stretchr/testify/mock"
)

// mockConnFactoryFunc is an autogenerated mock type for the connFactoryFunc type
type mockConnFactoryFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *mockConnFactoryFunc) Execute(_a0 *aerospike.ClientPolicy, _a1 *aerospike.Host) (asconn, aerospike.Error) {
	_ = "STUB: not implemented"
	return *new(asconn), *new(aerospike.Error)
}

type mockConstructorTestingTnewMockConnFactoryFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newMockConnFactoryFunc creates a new instance of mockConnFactoryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockConnFactoryFunc(t mockConstructorTestingTnewMockConnFactoryFunc) *mockConnFactoryFunc {
	_ = "STUB: not implemented"
	return nil
}
