// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	_ = "STUB: not implemented"
	return *new(metric.Meter)
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	_ = "STUB: not implemented"
	return *new(trace.Tracer)
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                             metric.Meter
	mu                                                sync.Mutex
	registrations                                     []metric.Registration
	ExporterPrometheusremotewriteConsumers            metric.Int64UpDownCounter
	ExporterPrometheusremotewriteFailedTranslations   metric.Int64Counter
	ExporterPrometheusremotewriteSentBatches          metric.Int64Counter
	ExporterPrometheusremotewriteTranslatedTimeSeries metric.Int64Counter
	ExporterPrometheusremotewriteWalBytesRead         metric.Int64Counter
	ExporterPrometheusremotewriteWalBytesWritten      metric.Int64Counter
	ExporterPrometheusremotewriteWalLag               metric.Int64Gauge
	ExporterPrometheusremotewriteWalReadLatency       metric.Int64Histogram
	ExporterPrometheusremotewriteWalReads             metric.Int64Counter
	ExporterPrometheusremotewriteWalReadsFailures     metric.Int64Counter
	ExporterPrometheusremotewriteWalWriteLatency      metric.Int64Histogram
	ExporterPrometheusremotewriteWalWrites            metric.Int64Counter
	ExporterPrometheusremotewriteWalWritesFailures    metric.Int64Counter
	ExporterPrometheusremotewriteWrittenExemplars     metric.Int64Counter
	ExporterPrometheusremotewriteWrittenHistograms    metric.Int64Counter
	ExporterPrometheusremotewriteWrittenSamples       metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	_ = "STUB: not implemented"

	// Shutdown unregister all registered callbacks for async instruments.
	return
}

func (builder *TelemetryBuilder) Shutdown() { _ = "STUB: not implemented"; return }

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
