// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package testbed // import "github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed"

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/ptrace"
)

// TestCaseValidator defines the interface for validating and reporting test results.
type TestCaseValidator interface {
	// Validate executes validation routines and test assertions.
	Validate(tc *TestCase)
	// RecordResults updates the TestResultsSummary for the test suite with results of a single test.
	RecordResults(tc *TestCase)
}

type LogPresentValidator struct {
	LogBody string
	Present bool
}

func (v *LogPresentValidator) Validate(tc *TestCase) { _ = "STUB: not implemented"; return }

func (*LogPresentValidator) RecordResults(tc *TestCase) { _ = "STUB: not implemented"; return }

// Remove "Test" prefix from test name.

// PerfTestValidator implements TestCaseValidator for test suites using PerformanceResults for summarizing results.
type PerfTestValidator struct {
	// IncludeLimitsInReport determines whether the summary generated by PerformanceResults should include the specified resource limits
	IncludeLimitsInReport bool
	// prevent unkeyed literal initialization
	_ struct{}
}

func (*PerfTestValidator) Validate(tc *TestCase) { _ = "STUB: not implemented"; return }

func (v *PerfTestValidator) RecordResults(tc *TestCase) { _ = "STUB: not implemented"; return }

// Remove "Test" prefix from test name.

// CorrectnessTestValidator implements TestCaseValidator for test suites using CorrectnessResults for summarizing results.
type CorrectnessTestValidator struct {
	dataProvider         DataProvider
	assertionFailures    []*TraceAssertionFailure
	ignoreSpanLinksAttrs bool
}

func NewCorrectTestValidator(senderName, receiverName string, provider DataProvider) *CorrectnessTestValidator {
	_ = "STUB: not implemented"
	// TODO: Fix Jaeger span links attributes and tracestate.
	return nil
}

func (v *CorrectnessTestValidator) Validate(tc *TestCase) { _ = "STUB: not implemented"; return }

func (v *CorrectnessTestValidator) RecordResults(tc *TestCase) { _ = "STUB: not implemented"; return }

// Remove "Test" prefix from test name.

func (v *CorrectnessTestValidator) assertSentRecdTracingDataEqual(tracesList []ptrace.Traces) {
	_ = "STUB: not implemented"
	return
}

// TODO: Remove this hack, and add a way to retrieve all sent data.

func (v *CorrectnessTestValidator) diffSpan(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanTraceID(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanSpanID(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanTraceState(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanParentSpanID(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanName(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	// Because of https://github.com/openzipkin/zipkin-go/pull/166 compare lower cases.
	return
}

func (v *CorrectnessTestValidator) diffSpanKind(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanTimestamps(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanAttributes(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanEvents(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanLinks(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffSpanStatus(sentSpan, recdSpan ptrace.Span) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) diffAttributeMap(spanName string,
	sentAttrs, recdAttrs pcommon.Map, fmtStr string,
) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) compareSimpleValues(spanName string, sentVal, recdVal pcommon.Value,
	fmtStr, attrKey string,
) {
	_ = "STUB: not implemented"
	return
}

func (v *CorrectnessTestValidator) compareKeyValueList(
	spanName string, sentVal, recdVal pcommon.Value, fmtStr, attrKey string,
) {
	_ = "STUB: not implemented"
	return
}

func convertEventsSliceToMap(events ptrace.SpanEventSlice) map[string][]ptrace.SpanEvent {
	_ = "STUB: not implemented"
	return nil
}

func sortEventsByTimestamp(eventList []ptrace.SpanEvent) { _ = "STUB: not implemented"; return }

func convertLinksSliceToMap(links ptrace.SpanLinkSlice) map[string]ptrace.SpanLink {
	_ = "STUB: not implemented"
	return nil
}

func notWithinOneMillisecond(sentNs, recdNs pcommon.Timestamp) bool {
	_ = "STUB: not implemented"
	return false
}

func populateSpansMap(spansMap map[string]ptrace.Span, tds []ptrace.Traces) {
	_ = "STUB: not implemented"
	return
}

func traceIDAndSpanIDToString(traceID pcommon.TraceID, spanID pcommon.SpanID) string {
	_ = "STUB: not implemented"
	return ""
}

type CorrectnessLogTestValidator struct {
	dataProvider DataProvider
}

func NewCorrectnessLogTestValidator(provider DataProvider) *CorrectnessLogTestValidator {
	_ = "STUB: not implemented"
	return nil
}

func (c *CorrectnessLogTestValidator) Validate(tc *TestCase) { _ = "STUB: not implemented"; return }

func (*CorrectnessLogTestValidator) RecordResults(tc *TestCase) { _ = "STUB: not implemented"; return }

// Remove "Test" prefix from test name.
