// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// ProcessContextSwitchesMetricAttributeKey specifies the key of an attribute for the process.context_switches metric.
type ProcessContextSwitchesMetricAttributeKey string

const (
	ProcessContextSwitchesMetricAttributeKeyContextSwitchType ProcessContextSwitchesMetricAttributeKey = "type"
)

// ProcessContextSwitchesMetricConfig provides config for the process.context_switches metric.
type ProcessContextSwitchesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []ProcessContextSwitchesMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *ProcessContextSwitchesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *ProcessContextSwitchesMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessCPUTimeMetricAttributeKey specifies the key of an attribute for the process.cpu.time metric.
type ProcessCPUTimeMetricAttributeKey string

const (
	ProcessCPUTimeMetricAttributeKeyState ProcessCPUTimeMetricAttributeKey = "state"
)

// ProcessCPUTimeMetricConfig provides config for the process.cpu.time metric.
type ProcessCPUTimeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                             `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []ProcessCPUTimeMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *ProcessCPUTimeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *ProcessCPUTimeMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// ProcessCPUUtilizationMetricAttributeKey specifies the key of an attribute for the process.cpu.utilization metric.
type ProcessCPUUtilizationMetricAttributeKey string

const (
	ProcessCPUUtilizationMetricAttributeKeyState ProcessCPUUtilizationMetricAttributeKey = "state"
)

// ProcessCPUUtilizationMetricConfig provides config for the process.cpu.utilization metric.
type ProcessCPUUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []ProcessCPUUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *ProcessCPUUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *ProcessCPUUtilizationMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessDiskIoMetricAttributeKey specifies the key of an attribute for the process.disk.io metric.
type ProcessDiskIoMetricAttributeKey string

const (
	ProcessDiskIoMetricAttributeKeyDirection ProcessDiskIoMetricAttributeKey = "direction"
)

// ProcessDiskIoMetricConfig provides config for the process.disk.io metric.
type ProcessDiskIoMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []ProcessDiskIoMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *ProcessDiskIoMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *ProcessDiskIoMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// ProcessDiskOperationsMetricAttributeKey specifies the key of an attribute for the process.disk.operations metric.
type ProcessDiskOperationsMetricAttributeKey string

const (
	ProcessDiskOperationsMetricAttributeKeyDirection ProcessDiskOperationsMetricAttributeKey = "direction"
)

// ProcessDiskOperationsMetricConfig provides config for the process.disk.operations metric.
type ProcessDiskOperationsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []ProcessDiskOperationsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *ProcessDiskOperationsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *ProcessDiskOperationsMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessHandlesMetricConfig provides config for the process.handles metric.
type ProcessHandlesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessHandlesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessMemoryUsageMetricConfig provides config for the process.memory.usage metric.
type ProcessMemoryUsageMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessMemoryUsageMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessMemoryUtilizationMetricConfig provides config for the process.memory.utilization metric.
type ProcessMemoryUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessMemoryUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessMemoryVirtualMetricConfig provides config for the process.memory.virtual metric.
type ProcessMemoryVirtualMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessMemoryVirtualMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessOpenFileDescriptorsMetricConfig provides config for the process.open_file_descriptors metric.
type ProcessOpenFileDescriptorsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessOpenFileDescriptorsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessPagingFaultsMetricAttributeKey specifies the key of an attribute for the process.paging.faults metric.
type ProcessPagingFaultsMetricAttributeKey string

const (
	ProcessPagingFaultsMetricAttributeKeyPagingFaultType ProcessPagingFaultsMetricAttributeKey = "type"
)

// ProcessPagingFaultsMetricConfig provides config for the process.paging.faults metric.
type ProcessPagingFaultsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []ProcessPagingFaultsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *ProcessPagingFaultsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *ProcessPagingFaultsMetricConfig) Validate() error { _ = "STUB: not implemented"; return nil }

// ProcessSignalsPendingMetricConfig provides config for the process.signals_pending metric.
type ProcessSignalsPendingMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessSignalsPendingMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessThreadsMetricConfig provides config for the process.threads metric.
type ProcessThreadsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessThreadsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ProcessUptimeMetricConfig provides config for the process.uptime metric.
type ProcessUptimeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *ProcessUptimeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// MetricsConfig provides config for process metrics.
type MetricsConfig struct {
	ProcessContextSwitches     ProcessContextSwitchesMetricConfig     `mapstructure:"process.context_switches"`
	ProcessCPUTime             ProcessCPUTimeMetricConfig             `mapstructure:"process.cpu.time"`
	ProcessCPUUtilization      ProcessCPUUtilizationMetricConfig      `mapstructure:"process.cpu.utilization"`
	ProcessDiskIo              ProcessDiskIoMetricConfig              `mapstructure:"process.disk.io"`
	ProcessDiskOperations      ProcessDiskOperationsMetricConfig      `mapstructure:"process.disk.operations"`
	ProcessHandles             ProcessHandlesMetricConfig             `mapstructure:"process.handles"`
	ProcessMemoryUsage         ProcessMemoryUsageMetricConfig         `mapstructure:"process.memory.usage"`
	ProcessMemoryUtilization   ProcessMemoryUtilizationMetricConfig   `mapstructure:"process.memory.utilization"`
	ProcessMemoryVirtual       ProcessMemoryVirtualMetricConfig       `mapstructure:"process.memory.virtual"`
	ProcessOpenFileDescriptors ProcessOpenFileDescriptorsMetricConfig `mapstructure:"process.open_file_descriptors"`
	ProcessPagingFaults        ProcessPagingFaultsMetricConfig        `mapstructure:"process.paging.faults"`
	ProcessSignalsPending      ProcessSignalsPendingMetricConfig      `mapstructure:"process.signals_pending"`
	ProcessThreads             ProcessThreadsMetricConfig             `mapstructure:"process.threads"`
	ProcessUptime              ProcessUptimeMetricConfig              `mapstructure:"process.uptime"`
}

func DefaultMetricsConfig() MetricsConfig { _ = "STUB: not implemented"; return *new(MetricsConfig) }

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ResourceAttributesConfig provides config for process resource attributes.
type ResourceAttributesConfig struct {
	ProcessCgroup         ResourceAttributeConfig `mapstructure:"process.cgroup"`
	ProcessCommand        ResourceAttributeConfig `mapstructure:"process.command"`
	ProcessCommandLine    ResourceAttributeConfig `mapstructure:"process.command_line"`
	ProcessExecutableName ResourceAttributeConfig `mapstructure:"process.executable.name"`
	ProcessExecutablePath ResourceAttributeConfig `mapstructure:"process.executable.path"`
	ProcessOwner          ResourceAttributeConfig `mapstructure:"process.owner"`
	ProcessParentPid      ResourceAttributeConfig `mapstructure:"process.parent_pid"`
	ProcessPid            ResourceAttributeConfig `mapstructure:"process.pid"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	_ = "STUB: not implemented"
	return *new(ResourceAttributesConfig)
}

// MetricsBuilderConfig is a configuration for process metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}
