// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// NginxConnectionsAcceptedMetricConfig provides config for the nginx.connections_accepted metric.
type NginxConnectionsAcceptedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NginxConnectionsAcceptedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NginxConnectionsCurrentMetricAttributeKey specifies the key of an attribute for the nginx.connections_current metric.
type NginxConnectionsCurrentMetricAttributeKey string

const (
	NginxConnectionsCurrentMetricAttributeKeyState NginxConnectionsCurrentMetricAttributeKey = "state"
)

// NginxConnectionsCurrentMetricConfig provides config for the nginx.connections_current metric.
type NginxConnectionsCurrentMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []NginxConnectionsCurrentMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *NginxConnectionsCurrentMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *NginxConnectionsCurrentMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// NginxConnectionsHandledMetricConfig provides config for the nginx.connections_handled metric.
type NginxConnectionsHandledMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NginxConnectionsHandledMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// NginxRequestsMetricConfig provides config for the nginx.requests metric.
type NginxRequestsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *NginxRequestsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// MetricsConfig provides config for nginx metrics.
type MetricsConfig struct {
	NginxConnectionsAccepted NginxConnectionsAcceptedMetricConfig `mapstructure:"nginx.connections_accepted"`
	NginxConnectionsCurrent  NginxConnectionsCurrentMetricConfig  `mapstructure:"nginx.connections_current"`
	NginxConnectionsHandled  NginxConnectionsHandledMetricConfig  `mapstructure:"nginx.connections_handled"`
	NginxRequests            NginxRequestsMetricConfig            `mapstructure:"nginx.requests"`
}

func DefaultMetricsConfig() MetricsConfig { _ = "STUB: not implemented"; return *new(MetricsConfig) }

// MetricsBuilderConfig is a configuration for nginx metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}
