// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Aerospike is an autogenerated mock type for the Aerospike type
type Aerospike struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Aerospike) Close() {
	_ = "STUB: not implemented"

	// Info provides a mock function with given fields:
	return
}

func (_m *Aerospike) Info() map[string]map[string]string { _ = "STUB: not implemented"; return nil }

// NamespaceInfo provides a mock function with given fields:
func (_m *Aerospike) NamespaceInfo() map[string]map[string]map[string]string {
	_ = "STUB: not implemented"
	return nil
}

type mockConstructorTestingTNewAerospike interface {
	mock.TestingT
	Cleanup(func())
}

// NewAerospike creates a new instance of Aerospike. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAerospike(t mockConstructorTestingTNewAerospike) *Aerospike {
	_ = "STUB: not implemented"
	return nil
}
