// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// AerospikeNamespaceDiskAvailableMetricConfig provides config for the aerospike.namespace.disk.available metric.
type AerospikeNamespaceDiskAvailableMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNamespaceDiskAvailableMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceGeojsonRegionQueryCellsMetricConfig provides config for the aerospike.namespace.geojson.region_query_cells metric.
type AerospikeNamespaceGeojsonRegionQueryCellsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNamespaceGeojsonRegionQueryCellsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceGeojsonRegionQueryFalsePositiveMetricConfig provides config for the aerospike.namespace.geojson.region_query_false_positive metric.
type AerospikeNamespaceGeojsonRegionQueryFalsePositiveMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNamespaceGeojsonRegionQueryFalsePositiveMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceGeojsonRegionQueryPointsMetricConfig provides config for the aerospike.namespace.geojson.region_query_points metric.
type AerospikeNamespaceGeojsonRegionQueryPointsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNamespaceGeojsonRegionQueryPointsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceGeojsonRegionQueryRequestsMetricConfig provides config for the aerospike.namespace.geojson.region_query_requests metric.
type AerospikeNamespaceGeojsonRegionQueryRequestsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNamespaceGeojsonRegionQueryRequestsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceMemoryFreeMetricConfig provides config for the aerospike.namespace.memory.free metric.
type AerospikeNamespaceMemoryFreeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNamespaceMemoryFreeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceMemoryUsageMetricAttributeKey specifies the key of an attribute for the aerospike.namespace.memory.usage metric.
type AerospikeNamespaceMemoryUsageMetricAttributeKey string

const (
	AerospikeNamespaceMemoryUsageMetricAttributeKeyNamespaceComponent AerospikeNamespaceMemoryUsageMetricAttributeKey = "component"
)

// AerospikeNamespaceMemoryUsageMetricConfig provides config for the aerospike.namespace.memory.usage metric.
type AerospikeNamespaceMemoryUsageMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AerospikeNamespaceMemoryUsageMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AerospikeNamespaceMemoryUsageMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *AerospikeNamespaceMemoryUsageMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceQueryCountMetricAttributeKey specifies the key of an attribute for the aerospike.namespace.query.count metric.
type AerospikeNamespaceQueryCountMetricAttributeKey string

const (
	AerospikeNamespaceQueryCountMetricAttributeKeyQueryType   AerospikeNamespaceQueryCountMetricAttributeKey = "type"
	AerospikeNamespaceQueryCountMetricAttributeKeyIndexType   AerospikeNamespaceQueryCountMetricAttributeKey = "index"
	AerospikeNamespaceQueryCountMetricAttributeKeyQueryResult AerospikeNamespaceQueryCountMetricAttributeKey = "result"
)

// AerospikeNamespaceQueryCountMetricConfig provides config for the aerospike.namespace.query.count metric.
type AerospikeNamespaceQueryCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                           `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AerospikeNamespaceQueryCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AerospikeNamespaceQueryCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *AerospikeNamespaceQueryCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceScanCountMetricAttributeKey specifies the key of an attribute for the aerospike.namespace.scan.count metric.
type AerospikeNamespaceScanCountMetricAttributeKey string

const (
	AerospikeNamespaceScanCountMetricAttributeKeyScanType   AerospikeNamespaceScanCountMetricAttributeKey = "type"
	AerospikeNamespaceScanCountMetricAttributeKeyScanResult AerospikeNamespaceScanCountMetricAttributeKey = "result"
)

// AerospikeNamespaceScanCountMetricConfig provides config for the aerospike.namespace.scan.count metric.
type AerospikeNamespaceScanCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AerospikeNamespaceScanCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AerospikeNamespaceScanCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *AerospikeNamespaceScanCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNamespaceTransactionCountMetricAttributeKey specifies the key of an attribute for the aerospike.namespace.transaction.count metric.
type AerospikeNamespaceTransactionCountMetricAttributeKey string

const (
	AerospikeNamespaceTransactionCountMetricAttributeKeyTransactionType   AerospikeNamespaceTransactionCountMetricAttributeKey = "type"
	AerospikeNamespaceTransactionCountMetricAttributeKeyTransactionResult AerospikeNamespaceTransactionCountMetricAttributeKey = "result"
)

// AerospikeNamespaceTransactionCountMetricConfig provides config for the aerospike.namespace.transaction.count metric.
type AerospikeNamespaceTransactionCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AerospikeNamespaceTransactionCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AerospikeNamespaceTransactionCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *AerospikeNamespaceTransactionCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNodeConnectionCountMetricAttributeKey specifies the key of an attribute for the aerospike.node.connection.count metric.
type AerospikeNodeConnectionCountMetricAttributeKey string

const (
	AerospikeNodeConnectionCountMetricAttributeKeyConnectionType AerospikeNodeConnectionCountMetricAttributeKey = "type"
	AerospikeNodeConnectionCountMetricAttributeKeyConnectionOp   AerospikeNodeConnectionCountMetricAttributeKey = "operation"
)

// AerospikeNodeConnectionCountMetricConfig provides config for the aerospike.node.connection.count metric.
type AerospikeNodeConnectionCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                           `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AerospikeNodeConnectionCountMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AerospikeNodeConnectionCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *AerospikeNodeConnectionCountMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNodeConnectionOpenMetricAttributeKey specifies the key of an attribute for the aerospike.node.connection.open metric.
type AerospikeNodeConnectionOpenMetricAttributeKey string

const (
	AerospikeNodeConnectionOpenMetricAttributeKeyConnectionType AerospikeNodeConnectionOpenMetricAttributeKey = "type"
)

// AerospikeNodeConnectionOpenMetricConfig provides config for the aerospike.node.connection.open metric.
type AerospikeNodeConnectionOpenMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []AerospikeNodeConnectionOpenMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *AerospikeNodeConnectionOpenMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

func (ms *AerospikeNodeConnectionOpenMetricConfig) Validate() error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNodeMemoryFreeMetricConfig provides config for the aerospike.node.memory.free metric.
type AerospikeNodeMemoryFreeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNodeMemoryFreeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// AerospikeNodeQueryTrackedMetricConfig provides config for the aerospike.node.query.tracked metric.
type AerospikeNodeQueryTrackedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *AerospikeNodeQueryTrackedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// MetricsConfig provides config for aerospike metrics.
type MetricsConfig struct {
	AerospikeNamespaceDiskAvailable                   AerospikeNamespaceDiskAvailableMetricConfig                   `mapstructure:"aerospike.namespace.disk.available"`
	AerospikeNamespaceGeojsonRegionQueryCells         AerospikeNamespaceGeojsonRegionQueryCellsMetricConfig         `mapstructure:"aerospike.namespace.geojson.region_query_cells"`
	AerospikeNamespaceGeojsonRegionQueryFalsePositive AerospikeNamespaceGeojsonRegionQueryFalsePositiveMetricConfig `mapstructure:"aerospike.namespace.geojson.region_query_false_positive"`
	AerospikeNamespaceGeojsonRegionQueryPoints        AerospikeNamespaceGeojsonRegionQueryPointsMetricConfig        `mapstructure:"aerospike.namespace.geojson.region_query_points"`
	AerospikeNamespaceGeojsonRegionQueryRequests      AerospikeNamespaceGeojsonRegionQueryRequestsMetricConfig      `mapstructure:"aerospike.namespace.geojson.region_query_requests"`
	AerospikeNamespaceMemoryFree                      AerospikeNamespaceMemoryFreeMetricConfig                      `mapstructure:"aerospike.namespace.memory.free"`
	AerospikeNamespaceMemoryUsage                     AerospikeNamespaceMemoryUsageMetricConfig                     `mapstructure:"aerospike.namespace.memory.usage"`
	AerospikeNamespaceQueryCount                      AerospikeNamespaceQueryCountMetricConfig                      `mapstructure:"aerospike.namespace.query.count"`
	AerospikeNamespaceScanCount                       AerospikeNamespaceScanCountMetricConfig                       `mapstructure:"aerospike.namespace.scan.count"`
	AerospikeNamespaceTransactionCount                AerospikeNamespaceTransactionCountMetricConfig                `mapstructure:"aerospike.namespace.transaction.count"`
	AerospikeNodeConnectionCount                      AerospikeNodeConnectionCountMetricConfig                      `mapstructure:"aerospike.node.connection.count"`
	AerospikeNodeConnectionOpen                       AerospikeNodeConnectionOpenMetricConfig                       `mapstructure:"aerospike.node.connection.open"`
	AerospikeNodeMemoryFree                           AerospikeNodeMemoryFreeMetricConfig                           `mapstructure:"aerospike.node.memory.free"`
	AerospikeNodeQueryTracked                         AerospikeNodeQueryTrackedMetricConfig                         `mapstructure:"aerospike.node.query.tracked"`
}

func DefaultMetricsConfig() MetricsConfig { _ = "STUB: not implemented"; return *new(MetricsConfig) }

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ResourceAttributesConfig provides config for aerospike resource attributes.
type ResourceAttributesConfig struct {
	AerospikeNamespace ResourceAttributeConfig `mapstructure:"aerospike.namespace"`
	AerospikeNodeName  ResourceAttributeConfig `mapstructure:"aerospike.node.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	_ = "STUB: not implemented"
	return *new(ResourceAttributesConfig)
}

// MetricsBuilderConfig is a configuration for aerospike metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	_ = "STUB: not implemented"
	return *new(MetricsBuilderConfig)
}
