// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeConnectionOp specifies the value connection_op attribute.
type AttributeConnectionOp int

const (
	_ AttributeConnectionOp = iota
	AttributeConnectionOpClose
	AttributeConnectionOpOpen
)

// String returns the string representation of the AttributeConnectionOp.
func (av AttributeConnectionOp) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeConnectionOp is a helper map of string to AttributeConnectionOp attribute value.
var MapAttributeConnectionOp = map[string]AttributeConnectionOp{
	"close": AttributeConnectionOpClose,
	"open":  AttributeConnectionOpOpen,
}

// AttributeConnectionType specifies the value connection_type attribute.
type AttributeConnectionType int

const (
	_ AttributeConnectionType = iota
	AttributeConnectionTypeClient
	AttributeConnectionTypeFabric
	AttributeConnectionTypeHeartbeat
)

// String returns the string representation of the AttributeConnectionType.
func (av AttributeConnectionType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeConnectionType is a helper map of string to AttributeConnectionType attribute value.
var MapAttributeConnectionType = map[string]AttributeConnectionType{
	"client":    AttributeConnectionTypeClient,
	"fabric":    AttributeConnectionTypeFabric,
	"heartbeat": AttributeConnectionTypeHeartbeat,
}

// AttributeIndexType specifies the value index_type attribute.
type AttributeIndexType int

const (
	_ AttributeIndexType = iota
	AttributeIndexTypePrimary
	AttributeIndexTypeSecondary
)

// String returns the string representation of the AttributeIndexType.
func (av AttributeIndexType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeIndexType is a helper map of string to AttributeIndexType attribute value.
var MapAttributeIndexType = map[string]AttributeIndexType{
	"primary":   AttributeIndexTypePrimary,
	"secondary": AttributeIndexTypeSecondary,
}

// AttributeNamespaceComponent specifies the value namespace_component attribute.
type AttributeNamespaceComponent int

const (
	_ AttributeNamespaceComponent = iota
	AttributeNamespaceComponentData
	AttributeNamespaceComponentIndex
	AttributeNamespaceComponentSetIndex
	AttributeNamespaceComponentSecondaryIndex
)

// String returns the string representation of the AttributeNamespaceComponent.
func (av AttributeNamespaceComponent) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeNamespaceComponent is a helper map of string to AttributeNamespaceComponent attribute value.
var MapAttributeNamespaceComponent = map[string]AttributeNamespaceComponent{
	"data":            AttributeNamespaceComponentData,
	"index":           AttributeNamespaceComponentIndex,
	"set_index":       AttributeNamespaceComponentSetIndex,
	"secondary_index": AttributeNamespaceComponentSecondaryIndex,
}

// AttributeQueryResult specifies the value query_result attribute.
type AttributeQueryResult int

const (
	_ AttributeQueryResult = iota
	AttributeQueryResultAbort
	AttributeQueryResultComplete
	AttributeQueryResultError
	AttributeQueryResultTimeout
)

// String returns the string representation of the AttributeQueryResult.
func (av AttributeQueryResult) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeQueryResult is a helper map of string to AttributeQueryResult attribute value.
var MapAttributeQueryResult = map[string]AttributeQueryResult{
	"abort":    AttributeQueryResultAbort,
	"complete": AttributeQueryResultComplete,
	"error":    AttributeQueryResultError,
	"timeout":  AttributeQueryResultTimeout,
}

// AttributeQueryType specifies the value query_type attribute.
type AttributeQueryType int

const (
	_ AttributeQueryType = iota
	AttributeQueryTypeAggregation
	AttributeQueryTypeBasic
	AttributeQueryTypeShort
	AttributeQueryTypeLongBasic
	AttributeQueryTypeShortBasic
	AttributeQueryTypeOpsBackground
	AttributeQueryTypeUdfBackground
)

// String returns the string representation of the AttributeQueryType.
func (av AttributeQueryType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeQueryType is a helper map of string to AttributeQueryType attribute value.
var MapAttributeQueryType = map[string]AttributeQueryType{
	"aggregation":    AttributeQueryTypeAggregation,
	"basic":          AttributeQueryTypeBasic,
	"short":          AttributeQueryTypeShort,
	"long_basic":     AttributeQueryTypeLongBasic,
	"short_basic":    AttributeQueryTypeShortBasic,
	"ops_background": AttributeQueryTypeOpsBackground,
	"udf_background": AttributeQueryTypeUdfBackground,
}

// AttributeScanResult specifies the value scan_result attribute.
type AttributeScanResult int

const (
	_ AttributeScanResult = iota
	AttributeScanResultAbort
	AttributeScanResultComplete
	AttributeScanResultError
)

// String returns the string representation of the AttributeScanResult.
func (av AttributeScanResult) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeScanResult is a helper map of string to AttributeScanResult attribute value.
var MapAttributeScanResult = map[string]AttributeScanResult{
	"abort":    AttributeScanResultAbort,
	"complete": AttributeScanResultComplete,
	"error":    AttributeScanResultError,
}

// AttributeScanType specifies the value scan_type attribute.
type AttributeScanType int

const (
	_ AttributeScanType = iota
	AttributeScanTypeAggregation
	AttributeScanTypeBasic
	AttributeScanTypeOpsBackground
	AttributeScanTypeUdfBackground
)

// String returns the string representation of the AttributeScanType.
func (av AttributeScanType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeScanType is a helper map of string to AttributeScanType attribute value.
var MapAttributeScanType = map[string]AttributeScanType{
	"aggregation":    AttributeScanTypeAggregation,
	"basic":          AttributeScanTypeBasic,
	"ops_background": AttributeScanTypeOpsBackground,
	"udf_background": AttributeScanTypeUdfBackground,
}

// AttributeTransactionResult specifies the value transaction_result attribute.
type AttributeTransactionResult int

const (
	_ AttributeTransactionResult = iota
	AttributeTransactionResultError
	AttributeTransactionResultFilteredOut
	AttributeTransactionResultNotFound
	AttributeTransactionResultSuccess
	AttributeTransactionResultTimeout
)

// String returns the string representation of the AttributeTransactionResult.
func (av AttributeTransactionResult) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeTransactionResult is a helper map of string to AttributeTransactionResult attribute value.
var MapAttributeTransactionResult = map[string]AttributeTransactionResult{
	"error":        AttributeTransactionResultError,
	"filtered_out": AttributeTransactionResultFilteredOut,
	"not_found":    AttributeTransactionResultNotFound,
	"success":      AttributeTransactionResultSuccess,
	"timeout":      AttributeTransactionResultTimeout,
}

// AttributeTransactionType specifies the value transaction_type attribute.
type AttributeTransactionType int

const (
	_ AttributeTransactionType = iota
	AttributeTransactionTypeDelete
	AttributeTransactionTypeRead
	AttributeTransactionTypeUdf
	AttributeTransactionTypeWrite
)

// String returns the string representation of the AttributeTransactionType.
func (av AttributeTransactionType) String() string { _ = "STUB: not implemented"; return "" }

// MapAttributeTransactionType is a helper map of string to AttributeTransactionType attribute value.
var MapAttributeTransactionType = map[string]AttributeTransactionType{
	"delete": AttributeTransactionTypeDelete,
	"read":   AttributeTransactionTypeRead,
	"udf":    AttributeTransactionTypeUdf,
	"write":  AttributeTransactionTypeWrite,
}

var MetricsInfo = metricsInfo{
	AerospikeNamespaceDiskAvailable: metricInfo{
		Name: "aerospike.namespace.disk.available",
	},
	AerospikeNamespaceGeojsonRegionQueryCells: metricInfo{
		Name: "aerospike.namespace.geojson.region_query_cells",
	},
	AerospikeNamespaceGeojsonRegionQueryFalsePositive: metricInfo{
		Name: "aerospike.namespace.geojson.region_query_false_positive",
	},
	AerospikeNamespaceGeojsonRegionQueryPoints: metricInfo{
		Name: "aerospike.namespace.geojson.region_query_points",
	},
	AerospikeNamespaceGeojsonRegionQueryRequests: metricInfo{
		Name: "aerospike.namespace.geojson.region_query_requests",
	},
	AerospikeNamespaceMemoryFree: metricInfo{
		Name: "aerospike.namespace.memory.free",
	},
	AerospikeNamespaceMemoryUsage: metricInfo{
		Name: "aerospike.namespace.memory.usage",
	},
	AerospikeNamespaceQueryCount: metricInfo{
		Name: "aerospike.namespace.query.count",
	},
	AerospikeNamespaceScanCount: metricInfo{
		Name: "aerospike.namespace.scan.count",
	},
	AerospikeNamespaceTransactionCount: metricInfo{
		Name: "aerospike.namespace.transaction.count",
	},
	AerospikeNodeConnectionCount: metricInfo{
		Name: "aerospike.node.connection.count",
	},
	AerospikeNodeConnectionOpen: metricInfo{
		Name: "aerospike.node.connection.open",
	},
	AerospikeNodeMemoryFree: metricInfo{
		Name: "aerospike.node.memory.free",
	},
	AerospikeNodeQueryTracked: metricInfo{
		Name: "aerospike.node.query.tracked",
	},
}

type metricsInfo struct {
	AerospikeNamespaceDiskAvailable                   metricInfo
	AerospikeNamespaceGeojsonRegionQueryCells         metricInfo
	AerospikeNamespaceGeojsonRegionQueryFalsePositive metricInfo
	AerospikeNamespaceGeojsonRegionQueryPoints        metricInfo
	AerospikeNamespaceGeojsonRegionQueryRequests      metricInfo
	AerospikeNamespaceMemoryFree                      metricInfo
	AerospikeNamespaceMemoryUsage                     metricInfo
	AerospikeNamespaceQueryCount                      metricInfo
	AerospikeNamespaceScanCount                       metricInfo
	AerospikeNamespaceTransactionCount                metricInfo
	AerospikeNodeConnectionCount                      metricInfo
	AerospikeNodeConnectionOpen                       metricInfo
	AerospikeNodeMemoryFree                           metricInfo
	AerospikeNodeQueryTracked                         metricInfo
}

type metricInfo struct {
	Name string
}

type metricAerospikeNamespaceDiskAvailable struct {
	data     pmetric.Metric                              // data buffer for generated metric.
	config   AerospikeNamespaceDiskAvailableMetricConfig // metric config provided by user.
	capacity int                                         // max observed number of data points added to the metric.
}

// init fills aerospike.namespace.disk.available metric with initial data.
func (m *metricAerospikeNamespaceDiskAvailable) init() {
	m.data.SetName("aerospike.namespace.disk.available")
	m.data.SetDescription("Minimum percentage of contiguous disk space free to the namespace across all devices")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
}

func (m *metricAerospikeNamespaceDiskAvailable) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceDiskAvailable) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceDiskAvailable) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceDiskAvailable(cfg AerospikeNamespaceDiskAvailableMetricConfig) metricAerospikeNamespaceDiskAvailable {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceDiskAvailable)
}

type metricAerospikeNamespaceGeojsonRegionQueryCells struct {
	data     pmetric.Metric                                        // data buffer for generated metric.
	config   AerospikeNamespaceGeojsonRegionQueryCellsMetricConfig // metric config provided by user.
	capacity int                                                   // max observed number of data points added to the metric.
}

// init fills aerospike.namespace.geojson.region_query_cells metric with initial data.
func (m *metricAerospikeNamespaceGeojsonRegionQueryCells) init() {
	m.data.SetName("aerospike.namespace.geojson.region_query_cells")
	m.data.SetDescription("Number of cell coverings for query region queried")
	m.data.SetUnit("{cells}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricAerospikeNamespaceGeojsonRegionQueryCells) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceGeojsonRegionQueryCells) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceGeojsonRegionQueryCells) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceGeojsonRegionQueryCells(cfg AerospikeNamespaceGeojsonRegionQueryCellsMetricConfig) metricAerospikeNamespaceGeojsonRegionQueryCells {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceGeojsonRegionQueryCells)
}

type metricAerospikeNamespaceGeojsonRegionQueryFalsePositive struct {
	data     pmetric.Metric                                                // data buffer for generated metric.
	config   AerospikeNamespaceGeojsonRegionQueryFalsePositiveMetricConfig // metric config provided by user.
	capacity int                                                           // max observed number of data points added to the metric.
}

// init fills aerospike.namespace.geojson.region_query_false_positive metric with initial data.
func (m *metricAerospikeNamespaceGeojsonRegionQueryFalsePositive) init() {
	m.data.SetName("aerospike.namespace.geojson.region_query_false_positive")
	m.data.SetDescription("Number of points outside the region.")
	m.data.SetUnit("{points}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricAerospikeNamespaceGeojsonRegionQueryFalsePositive) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceGeojsonRegionQueryFalsePositive) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceGeojsonRegionQueryFalsePositive) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceGeojsonRegionQueryFalsePositive(cfg AerospikeNamespaceGeojsonRegionQueryFalsePositiveMetricConfig) metricAerospikeNamespaceGeojsonRegionQueryFalsePositive {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceGeojsonRegionQueryFalsePositive)
}

type metricAerospikeNamespaceGeojsonRegionQueryPoints struct {
	data     pmetric.Metric                                         // data buffer for generated metric.
	config   AerospikeNamespaceGeojsonRegionQueryPointsMetricConfig // metric config provided by user.
	capacity int                                                    // max observed number of data points added to the metric.
}

// init fills aerospike.namespace.geojson.region_query_points metric with initial data.
func (m *metricAerospikeNamespaceGeojsonRegionQueryPoints) init() {
	m.data.SetName("aerospike.namespace.geojson.region_query_points")
	m.data.SetDescription("Number of points within the region.")
	m.data.SetUnit("{points}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricAerospikeNamespaceGeojsonRegionQueryPoints) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceGeojsonRegionQueryPoints) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceGeojsonRegionQueryPoints) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceGeojsonRegionQueryPoints(cfg AerospikeNamespaceGeojsonRegionQueryPointsMetricConfig) metricAerospikeNamespaceGeojsonRegionQueryPoints {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceGeojsonRegionQueryPoints)
}

type metricAerospikeNamespaceGeojsonRegionQueryRequests struct {
	data     pmetric.Metric                                           // data buffer for generated metric.
	config   AerospikeNamespaceGeojsonRegionQueryRequestsMetricConfig // metric config provided by user.
	capacity int                                                      // max observed number of data points added to the metric.
}

// init fills aerospike.namespace.geojson.region_query_requests metric with initial data.
func (m *metricAerospikeNamespaceGeojsonRegionQueryRequests) init() {
	m.data.SetName("aerospike.namespace.geojson.region_query_requests")
	m.data.SetDescription("Number of geojson queries on the system since the uptime of the node.")
	m.data.SetUnit("{queries}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricAerospikeNamespaceGeojsonRegionQueryRequests) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceGeojsonRegionQueryRequests) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceGeojsonRegionQueryRequests) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceGeojsonRegionQueryRequests(cfg AerospikeNamespaceGeojsonRegionQueryRequestsMetricConfig) metricAerospikeNamespaceGeojsonRegionQueryRequests {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceGeojsonRegionQueryRequests)
}

type metricAerospikeNamespaceMemoryFree struct {
	data     pmetric.Metric                           // data buffer for generated metric.
	config   AerospikeNamespaceMemoryFreeMetricConfig // metric config provided by user.
	capacity int                                      // max observed number of data points added to the metric.
}

// init fills aerospike.namespace.memory.free metric with initial data.
func (m *metricAerospikeNamespaceMemoryFree) init() {
	m.data.SetName("aerospike.namespace.memory.free")
	m.data.SetDescription("Percentage of the namespace's memory which is still free")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
}

func (m *metricAerospikeNamespaceMemoryFree) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceMemoryFree) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceMemoryFree) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceMemoryFree(cfg AerospikeNamespaceMemoryFreeMetricConfig) metricAerospikeNamespaceMemoryFree {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceMemoryFree)
}

type metricAerospikeNamespaceMemoryUsage struct {
	data          pmetric.Metric                            // data buffer for generated metric.
	config        AerospikeNamespaceMemoryUsageMetricConfig // metric config provided by user.
	capacity      int                                       // max observed number of data points added to the metric.
	aggDataPoints []int64                                   // slice containing number of aggregated datapoints at each index
}

// init fills aerospike.namespace.memory.usage metric with initial data.
func (m *metricAerospikeNamespaceMemoryUsage) init() {
	m.data.SetName("aerospike.namespace.memory.usage")
	m.data.SetDescription("Memory currently used by each component of the namespace")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAerospikeNamespaceMemoryUsage) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, namespaceComponentAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceMemoryUsage) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceMemoryUsage) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceMemoryUsage(cfg AerospikeNamespaceMemoryUsageMetricConfig) metricAerospikeNamespaceMemoryUsage {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceMemoryUsage)
}

type metricAerospikeNamespaceQueryCount struct {
	data          pmetric.Metric                           // data buffer for generated metric.
	config        AerospikeNamespaceQueryCountMetricConfig // metric config provided by user.
	capacity      int                                      // max observed number of data points added to the metric.
	aggDataPoints []int64                                  // slice containing number of aggregated datapoints at each index
}

// init fills aerospike.namespace.query.count metric with initial data.
func (m *metricAerospikeNamespaceQueryCount) init() {
	m.data.SetName("aerospike.namespace.query.count")
	m.data.SetDescription("Number of query operations performed on the namespace")
	m.data.SetUnit("{queries}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAerospikeNamespaceQueryCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, queryTypeAttributeValue string, indexTypeAttributeValue string, queryResultAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceQueryCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceQueryCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceQueryCount(cfg AerospikeNamespaceQueryCountMetricConfig) metricAerospikeNamespaceQueryCount {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceQueryCount)
}

type metricAerospikeNamespaceScanCount struct {
	data          pmetric.Metric                          // data buffer for generated metric.
	config        AerospikeNamespaceScanCountMetricConfig // metric config provided by user.
	capacity      int                                     // max observed number of data points added to the metric.
	aggDataPoints []int64                                 // slice containing number of aggregated datapoints at each index
}

// init fills aerospike.namespace.scan.count metric with initial data.
func (m *metricAerospikeNamespaceScanCount) init() {
	m.data.SetName("aerospike.namespace.scan.count")
	m.data.SetDescription("Number of scan operations performed on the namespace")
	m.data.SetUnit("{scans}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAerospikeNamespaceScanCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, scanTypeAttributeValue string, scanResultAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceScanCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceScanCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceScanCount(cfg AerospikeNamespaceScanCountMetricConfig) metricAerospikeNamespaceScanCount {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceScanCount)
}

type metricAerospikeNamespaceTransactionCount struct {
	data          pmetric.Metric                                 // data buffer for generated metric.
	config        AerospikeNamespaceTransactionCountMetricConfig // metric config provided by user.
	capacity      int                                            // max observed number of data points added to the metric.
	aggDataPoints []int64                                        // slice containing number of aggregated datapoints at each index
}

// init fills aerospike.namespace.transaction.count metric with initial data.
func (m *metricAerospikeNamespaceTransactionCount) init() {
	m.data.SetName("aerospike.namespace.transaction.count")
	m.data.SetDescription("Number of transactions performed on the namespace")
	m.data.SetUnit("{transactions}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAerospikeNamespaceTransactionCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, transactionTypeAttributeValue string, transactionResultAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNamespaceTransactionCount) updateCapacity() {
	_ = "STUB: not implemented"
	return
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNamespaceTransactionCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNamespaceTransactionCount(cfg AerospikeNamespaceTransactionCountMetricConfig) metricAerospikeNamespaceTransactionCount {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNamespaceTransactionCount)
}

type metricAerospikeNodeConnectionCount struct {
	data          pmetric.Metric                           // data buffer for generated metric.
	config        AerospikeNodeConnectionCountMetricConfig // metric config provided by user.
	capacity      int                                      // max observed number of data points added to the metric.
	aggDataPoints []int64                                  // slice containing number of aggregated datapoints at each index
}

// init fills aerospike.node.connection.count metric with initial data.
func (m *metricAerospikeNodeConnectionCount) init() {
	m.data.SetName("aerospike.node.connection.count")
	m.data.SetDescription("Number of connections opened and closed to the node")
	m.data.SetUnit("{connections}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAerospikeNodeConnectionCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, connectionTypeAttributeValue string, connectionOpAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNodeConnectionCount) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNodeConnectionCount) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNodeConnectionCount(cfg AerospikeNodeConnectionCountMetricConfig) metricAerospikeNodeConnectionCount {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNodeConnectionCount)
}

type metricAerospikeNodeConnectionOpen struct {
	data          pmetric.Metric                          // data buffer for generated metric.
	config        AerospikeNodeConnectionOpenMetricConfig // metric config provided by user.
	capacity      int                                     // max observed number of data points added to the metric.
	aggDataPoints []int64                                 // slice containing number of aggregated datapoints at each index
}

// init fills aerospike.node.connection.open metric with initial data.
func (m *metricAerospikeNodeConnectionOpen) init() {
	m.data.SetName("aerospike.node.connection.open")
	m.data.SetDescription("Current number of open connections to the node")
	m.data.SetUnit("{connections}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricAerospikeNodeConnectionOpen) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, connectionTypeAttributeValue string) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNodeConnectionOpen) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNodeConnectionOpen) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNodeConnectionOpen(cfg AerospikeNodeConnectionOpenMetricConfig) metricAerospikeNodeConnectionOpen {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNodeConnectionOpen)
}

type metricAerospikeNodeMemoryFree struct {
	data     pmetric.Metric                      // data buffer for generated metric.
	config   AerospikeNodeMemoryFreeMetricConfig // metric config provided by user.
	capacity int                                 // max observed number of data points added to the metric.
}

// init fills aerospike.node.memory.free metric with initial data.
func (m *metricAerospikeNodeMemoryFree) init() {
	m.data.SetName("aerospike.node.memory.free")
	m.data.SetDescription("Percentage of the node's memory which is still free")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
}

func (m *metricAerospikeNodeMemoryFree) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNodeMemoryFree) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNodeMemoryFree) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNodeMemoryFree(cfg AerospikeNodeMemoryFreeMetricConfig) metricAerospikeNodeMemoryFree {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNodeMemoryFree)
}

type metricAerospikeNodeQueryTracked struct {
	data     pmetric.Metric                        // data buffer for generated metric.
	config   AerospikeNodeQueryTrackedMetricConfig // metric config provided by user.
	capacity int                                   // max observed number of data points added to the metric.
}

// init fills aerospike.node.query.tracked metric with initial data.
func (m *metricAerospikeNodeQueryTracked) init() {
	m.data.SetName("aerospike.node.query.tracked")
	m.data.SetDescription("Number of queries tracked by the system.")
	m.data.SetUnit("{queries}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricAerospikeNodeQueryTracked) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	_ = "STUB: not implemented"
	return
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricAerospikeNodeQueryTracked) updateCapacity() { _ = "STUB: not implemented"; return }

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricAerospikeNodeQueryTracked) emit(metrics pmetric.MetricSlice) {
	_ = "STUB: not implemented"
	return
}

func newMetricAerospikeNodeQueryTracked(cfg AerospikeNodeQueryTrackedMetricConfig) metricAerospikeNodeQueryTracked {
	_ = "STUB: not implemented"
	return *new(metricAerospikeNodeQueryTracked)
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                                  MetricsBuilderConfig // config of the metrics builder.
	startTime                                               pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                                         int                  // maximum observed number of metrics per resource.
	metricsBuffer                                           pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                               component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter                          map[string]filter.Filter
	resourceAttributeExcludeFilter                          map[string]filter.Filter
	metricAerospikeNamespaceDiskAvailable                   metricAerospikeNamespaceDiskAvailable
	metricAerospikeNamespaceGeojsonRegionQueryCells         metricAerospikeNamespaceGeojsonRegionQueryCells
	metricAerospikeNamespaceGeojsonRegionQueryFalsePositive metricAerospikeNamespaceGeojsonRegionQueryFalsePositive
	metricAerospikeNamespaceGeojsonRegionQueryPoints        metricAerospikeNamespaceGeojsonRegionQueryPoints
	metricAerospikeNamespaceGeojsonRegionQueryRequests      metricAerospikeNamespaceGeojsonRegionQueryRequests
	metricAerospikeNamespaceMemoryFree                      metricAerospikeNamespaceMemoryFree
	metricAerospikeNamespaceMemoryUsage                     metricAerospikeNamespaceMemoryUsage
	metricAerospikeNamespaceQueryCount                      metricAerospikeNamespaceQueryCount
	metricAerospikeNamespaceScanCount                       metricAerospikeNamespaceScanCount
	metricAerospikeNamespaceTransactionCount                metricAerospikeNamespaceTransactionCount
	metricAerospikeNodeConnectionCount                      metricAerospikeNodeConnectionCount
	metricAerospikeNodeConnectionOpen                       metricAerospikeNodeConnectionOpen
	metricAerospikeNodeMemoryFree                           metricAerospikeNodeMemoryFree
	metricAerospikeNodeQueryTracked                         metricAerospikeNodeQueryTracked
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	_ = "STUB: not implemented"

	// WithStartTime sets startTime on the metrics builder.
	return
}

func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	_ = "STUB: not implemented"
	return *new(MetricBuilderOption)
}

func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	_ = "STUB: not implemented"
	return nil
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	_ = "STUB: not implemented"
	return nil
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"
	return
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	_ = "STUB: not implemented"

	// WithResource sets the provided resource on the emitted ResourceMetrics.
	// It's recommended to use ResourceBuilder to create the resource.
	return
}

func WithResource(res pcommon.Resource) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	_ = "STUB: not implemented"
	return *new(ResourceMetricsOption)
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	_ = "STUB: not implemented"
	return
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	_ = "STUB: not implemented"
	return *new(pmetric.Metrics)
}

// RecordAerospikeNamespaceDiskAvailableDataPoint adds a data point to aerospike.namespace.disk.available metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceDiskAvailableDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceGeojsonRegionQueryCellsDataPoint adds a data point to aerospike.namespace.geojson.region_query_cells metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceGeojsonRegionQueryCellsDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceGeojsonRegionQueryFalsePositiveDataPoint adds a data point to aerospike.namespace.geojson.region_query_false_positive metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceGeojsonRegionQueryFalsePositiveDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceGeojsonRegionQueryPointsDataPoint adds a data point to aerospike.namespace.geojson.region_query_points metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceGeojsonRegionQueryPointsDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceGeojsonRegionQueryRequestsDataPoint adds a data point to aerospike.namespace.geojson.region_query_requests metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceGeojsonRegionQueryRequestsDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceMemoryFreeDataPoint adds a data point to aerospike.namespace.memory.free metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceMemoryFreeDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceMemoryUsageDataPoint adds a data point to aerospike.namespace.memory.usage metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceMemoryUsageDataPoint(ts pcommon.Timestamp, inputVal string, namespaceComponentAttributeValue AttributeNamespaceComponent) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceQueryCountDataPoint adds a data point to aerospike.namespace.query.count metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceQueryCountDataPoint(ts pcommon.Timestamp, inputVal string, queryTypeAttributeValue AttributeQueryType, indexTypeAttributeValue AttributeIndexType, queryResultAttributeValue AttributeQueryResult) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceScanCountDataPoint adds a data point to aerospike.namespace.scan.count metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceScanCountDataPoint(ts pcommon.Timestamp, inputVal string, scanTypeAttributeValue AttributeScanType, scanResultAttributeValue AttributeScanResult) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNamespaceTransactionCountDataPoint adds a data point to aerospike.namespace.transaction.count metric.
func (mb *MetricsBuilder) RecordAerospikeNamespaceTransactionCountDataPoint(ts pcommon.Timestamp, inputVal string, transactionTypeAttributeValue AttributeTransactionType, transactionResultAttributeValue AttributeTransactionResult) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNodeConnectionCountDataPoint adds a data point to aerospike.node.connection.count metric.
func (mb *MetricsBuilder) RecordAerospikeNodeConnectionCountDataPoint(ts pcommon.Timestamp, inputVal string, connectionTypeAttributeValue AttributeConnectionType, connectionOpAttributeValue AttributeConnectionOp) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNodeConnectionOpenDataPoint adds a data point to aerospike.node.connection.open metric.
func (mb *MetricsBuilder) RecordAerospikeNodeConnectionOpenDataPoint(ts pcommon.Timestamp, inputVal string, connectionTypeAttributeValue AttributeConnectionType) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNodeMemoryFreeDataPoint adds a data point to aerospike.node.memory.free metric.
func (mb *MetricsBuilder) RecordAerospikeNodeMemoryFreeDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordAerospikeNodeQueryTrackedDataPoint adds a data point to aerospike.node.query.tracked metric.
func (mb *MetricsBuilder) RecordAerospikeNodeQueryTrackedDataPoint(ts pcommon.Timestamp, inputVal string) error {
	_ = "STUB: not implemented"
	return nil
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) { _ = "STUB: not implemented"; return }
