// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	_ = "STUB: not implemented"
	return nil
}

// ResourceAttributesConfig provides config for resourcedetectionprocessor/kubeadm resource attributes.
type ResourceAttributesConfig struct {
	K8sClusterName ResourceAttributeConfig `mapstructure:"k8s.cluster.name"`
	K8sClusterUID  ResourceAttributeConfig `mapstructure:"k8s.cluster.uid"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	_ = "STUB: not implemented"
	return *new(ResourceAttributesConfig)
}
